### ISSUE TITLE
Error in Getting Started: `trunk serve --open` gives error: `no storage space`

### ISSUE THREAD

**Issue by t1lde** [leptos-rs/leptos#1003]
I opened an Issue on this in trunk, as it's likely on their end, but I thought I should open one here, too.

See: https://github.com/thedodd/trunk/issues/542

**Comment by gbj** [comment]
I'm happy to leave this open until you feel like it's resolved, but I don't think there's anything I can do for you.

**Comment by agilarity** [comment]
I got into a similar situation while exploring the examples. I ran `trunk` and `cargo leptos` one too many times and bang -- `no storage space`. The problem was real. My `leptos/examples` director was huge. I ran `cargo clean` and `trunk clean` on a few projects and that resolved my issue.

You can run `cargo make clean-examples` from the **leptos** root to free up storage space.

**Comment by gbj** [comment]
I'm going to close this issue, as I don't think it has anything to do with Leptos itself.
