### ISSUE TITLE
Support for aysnc `StoredValue.with_value`?

### ISSUE THREAD

**Issue by bluenote10** [leptos-rs/leptos#1018]
I'm wondering if it would make sense to offer an async API for values stored inside a `StoredValue`. I'm currently scratching my head, how to make something like this work, and I have the feeling that it would need some special support in the `StoredValue` API. I'm trying to wrap some wgpu rendering that are inherently async in an abstraction like this:

```rust
pub struct Renderer {
    canvas: HtmlCanvasElement,
    // more stuff related to wgpu devices/surfaces/... that prevent `Clone`
}

impl Renderer {
    pub fn new(canvas: HtmlCanvasElement) -> Self {
        Self { canvas }
    }
    pub async fn render(&self) {
        // all kinds of async rendering stuff here...
    }
}
``` 

In the leptos component I'm trying to do something like this:

```rust
#[component]
pub fn CanvasWrapper(cx: Scope) -> impl IntoView {
    let canvas: NodeRef<Canvas> = create_node_ref(cx);

    let renderer: StoredValue<Option<Renderer>> = store_value(cx, None);

    let on_mount = move |parent: HtmlElement<Div>| {
        // [...] somewhere initialize the renderer instance.
        if let Some(canvas) = canvas.get() {
            let canvas: &HtmlCanvasElement = canvas.deref();
            renderer.set_value(Some(Renderer::new(canvas.clone())));
        }
    };

    let on_click = move |_| {
        spawn_local(async move {
            renderer.with_value(|renderer| {
                if let Some(renderer) = renderer {
                    Some(renderer.render())
                } else {
                    None
                }
            });
        });
    };

    view! { cx,
        <>
            {
                view! { cx,
                    <div>
                        <canvas node_ref=canvas />
                    </div>
                }.on_mount(on_mount)
            }
            <button on:click=on_click>"Render"</button>
        </>
    }
}
```

This doesn't compile however, because the reference exposed by `with_value` doesn't live long enough to allow returning a future from it.

I might be missing something, but perhaps it would be necessary to offer some kind of `with_value_async` that allows to pass in an async function, and it internally takes care of the `spawn_local`. Since this function holds the `&T` itself, it could make sure that the reference lives long enough for the future to complete by internally awaiting the future completion.

**Comment by gbj** [comment]
Hm... I think the issue here is more that, because the reactive system is built on interiorly-mutable types internally, even if you could do an async `.with()` you'd be doing the equivalent of holding the lock across an `.await`, which means that for some indeterminate period of time it would be impossible to update not just this stored value, but other stored values, without a panic. (Other stored values because they're all stored in one data structure in the reactive system, which is why you get a `Copy`able index into it.)

This is why none of the signal or stored values accessor or updaters are async; they basically take a RefCell borrow of the reactive system, so they can't be preempted by anything else.   

I wonder whether in your situation, a better solution might be to 
```rust
let renderer: Rc<RefCell<Option<Renderer>>> = Default::default();
```
Because this particular variable is the only one you need to worry about it's easy to use interior mutability across the await here.
```
    let on_mount = {
      let renderer = Rc::clone(&renderer);
      move |parent: HtmlElement<Div>| {
        // [...] somewhere initialize the renderer instance.
        if let Some(canvas) = canvas.get() {
            let canvas: &HtmlCanvasElement = canvas.deref();
            *renderer.borrow_mut() = Some(Renderer::new(canvas.clone()));
        }
      }
    };

    let on_click = move |_| {
        spawn_local(async move {
            let renderer = renderer.borrow();
                if let Some(renderer) = renderer {
                    Some(renderer.render())
                } else {
                    None
                }
        });
    };
```
(Apologies for formatting, am typing this into GitHub)

**Comment by bluenote10** [comment]
Ah indeed that's a good idea! I still need to wrap my head around when to use `StoredValue` in contrast a regular `Rc<RefCell<T>>`.

I think this should mean that explicit async support in `StoredValue` is probably not needed or even counter-productive, so I would close this issue.

Side note: When trying to implement it, I noticed that I had to clone the renderer twice (and even repeatedly, because I need it in multiple callbacks) like that:

```rust
    let renderer_clone = renderer.clone();
    let cb = move || {
        let renderer = renderer.clone();
        spawn_local(async move {
            let renderer = renderer.borrow();
            if let Some(ref renderer) = *renderer {
                Some(renderer.render())
            } else {
                None
            };
        });
    };
```

The reason is that event handlers want a `impl FnMut() + 'static` but without the double clone the closure becomes a true `FnOnce`. This makes me wonder, what are the reasons to use `FnMut() + 'static` vs `FnOnce() + 'static + Clone` in the APIs in general? Would the latter be easier to use in such use cases?

**Comment by gbj** [comment]
Re the function types: a `FnOnce` can really only run once, so by definition it can't be used for something like an event listener. There may be cases in which I've accidentally made requirements stricter than they need to be, in which case we can relax them, but something like a click listener needs to be `Fn` or `FnMut`.

Multiple clones are annoying but cheap for something like an `Rc`

**Comment by bluenote10** [comment]
I thought the design of leptos using move closure everywhere is to rather rely on `Copy` and `Clone` to achieve multiple function calls. I.e., an `FnOnce` can be called multiple times if it is `Clone`:

```rust
fn take_clonable_fn_once(f: impl FnOnce() + Clone + 'static) {
    // can call FnOnce multiple times
    f.clone()();
    f.clone()();
}
```

Aren't all the event handlers a user writes with `move |_| {...}` inherently an `FnOnce` because they move things into the closure, and the compiler can only accept it as `FnMut` thanks to this stuff typically being `Copy`? At least this works:

```rust
#[component]
fn Works(cx: Scope) -> impl IntoView {
    let x = 42;

    let toggle = move |_| {
        let y = x; // Works because x is Copy
    };

    view! { cx,
        <button on:click=toggle>"Toggle"</button>
    }
}
```

but this doesn't:

```
#[component]
fn DoesNotWork(cx: Scope) -> impl IntoView {
    let x = "foo".to_string();

    let toggle = move |_| {
        let y = x; // Fails because x is only Clone
    };

    view! { cx,
        <button on:click=toggle>"Toggle"</button>
    }
}
```

**Comment by gbj** [comment]
Closures are one of the most mind-bending and coolest parts of Rust in my opinion.

So first, here's the signature for `event_handler` in [`HtmlElement::on()`](https://docs.rs/leptos/latest/leptos/struct.HtmlElement.html#method.on), which is used for `on:click` and so on:
```rust
event_handler: impl FnMut(E::EventType) + 'static
```

`window_event_listener` takes `cb: impl Fn(web_sys::Event) + 'static` (note to self: this should be `FnMut`)

and so on.

All functions implement `FnOnce`, which means they can be called once, if you own them: `FnOnce` has a method `call(self)`, so it consumes the function. Some functions implement `FnMut`, which means they can be called many times if you have an exclusive reference to them; `FnMut` has a method `call(&mut self)`. An even smaller subset implement `Fn`, which means they can be called many times even if you only have a shared reference (they have `call(&self)`)

A closure is a struct of everything it captures. The "magic" (it's not at all magic) that Leptos does with `Copy` types is that when you move a bunch of signals into a closure, that closure itself is `Copy + 'static`, which means it owns all its data and all its data is `Copy`. This means that it's basically `Fn` by default, because the closure itself can just be automatically copied if necessary.

That's due to the types we give you that you can move into closures. When `renderer` is an `Rc<_>` and not a `StoredValue<_>`, though, the closure is no longer `Copy`, it is only `Clone` (because an `Rc` is not `Copy`) The same goes for your `toggle` example with a `String`. It can only ever be called once, because it moves its captured `x` into a local variable which is dropped at the end of that particular click, and then can never be called again; you've moved `x` out of the struct, and `x` isn't `Copy` and you haven't cloned it, so this can only be valid if `call` takes `self` as owned, i.e., is `FnOnce::call()` not `FnMut::call()` or `Fn::call()`
