### ISSUE TITLE
`Location::search` is not consistent between the server and browser

### ISSUE THREAD

**Issue by Skyliegirl33** [leptos-rs/leptos#1071]
For example, on the client, this is the result:
`?hello=world&foo=bar`
But on the server, it's different:
`hello=world&foo=bar`

**Comment by gbj** [comment]
Thanks! I had to choose between including the `?` in both and excluding it from both. I chose to exclude it from both by removing it on the browser side. This means any server-side logic should still work as previously. Browser-side logic with `use_query` etc. should work, because that was already using the browser's built-in `searchParams` iterator, not the raw search string. Libraries like `serde_qs` omit the opening `?` because it's not a part of the search proper, so I decided to just remove `?` from the `search` memo in `Location` across the board.

**Comment by Skyliegirl33** [comment]
Appreciate this! I do think omitting the `?` was the right choice.
