### ISSUE TITLE
Could `MaybeSignal` be made `Copy` to simplify generalization `T` vs `Signal<T>`?

### ISSUE THREAD

**Issue by bluenote10** [leptos-rs/leptos#1072]
I'm struggling a lot with generalizing the `T` vs `Signal<T>` decision for component props. I'd assume as a library author we should strive for `MaybeSignal<T>`, because it offers users the maximum flexibility.

What makes working with `MaybeSignal<T>` relatively awkward is that it isn't really consistent with `Signal<T>` in terms of `Copy` / `Clone`. Let's imagine an existing component that takes some `my_prop: Signal<MyData>` and `MyData` is costly to clone (or isn't clonable at all). As long as the component uses `Signal<MyData>` it can get away with using move closures everywhere, because `Signal` is copy and everything works fine. But trying to refactoring the component to use `my_prop: MaybeSignal<MyData>` feels almost impossible in some cases, because now `my_prop` is neither `Copy` and we also don't want to (or cannot) manually clone `my_prop` before each invocation of a move closure. In such cases I don't really find a good way how to proceed. All options I see look pretty bad:
- If I stick to just `Signal<MyData>` it will cause pain for users who only have a plain `MyData` (do I force them into creating dummy signals just to satisfy the prop type?)
- I could start wrapping things perhaps into `Signal<Rc<MyData>>` to enable clonability (or make it cheap). But that is painful on user side as well, because they have to wrap everything on their side. And the refactoring of the component is also not straightforward, because lack of `Copy` requires lots of explicit `.clone()` calls (one for each move closure).

I'm wondering if it would be possible to use the same trick as in `StoredValue` for the `T` "side" of `MaybeSignal`, so that it could become `Copy` as well (only reading side)? I'd assume that this should make it much easier to refactor from `Signal` to `MaybeSignal`.

**Comment by gbj** [comment]
Hm... So the "clone into closure" pattern is a very normal, albeit unfortunate, one in Rust UI libraries. It's something that Leptos tries to make easier on users by making signals `Copy`, but this is a matter of convenience—there's nothing *wrong* with
```rust
let on_click = {
  let data = my_data.clone();
  move |_| {
    do_something_with(data);
  }
};
```
`MaybeSignal<T>` *could* be backed by `StoredValue<T>`. However, there's an overhead to creating those stored values, and if `T: Copy` they don't even add any convenience. If `T: Clone` they add some convenience for you as a library author, at the expense of some runtime cost for users.

I don't really want to make a global change to how this is implemented in the framework, because that forces everything into the less-optimal pattern.

I guess it would be possible to provide a `CopyMaybeSignal<T>` type
```rust
pub enum CopyMaybeSignal<T>
where
    T: 'static,
{
    Static(StoredValue<T>),
    Dynamic(Signal<T>),
}
```
and a function you can call in your components to convert `MaybeSignal<T>` into `CopyMaybeSignal<T>`. In fact you can create this type in your own library and use it internally.

So I think there are a two good ways for you to handle this without a change on the framework end:
- Define `CopyMaybeSignal<T>` and convert things into it
- Use a `clone!` macro (they exist in a bunch of UI libraries, but [something like this](https://docs.rs/clone-macro/latest/clone_macro/)) that makes it easier for you to clone things into closures.

**Comment by bluenote10** [comment]
Thanks for the ideas! I'll have to experiment with the `CopyMaybeSignal` a bit more.

It still feels a bit inconsequential. One of the main features of letpos compared to other libraries is that it actually tries to avoid the cloning madness. In principle, we _should_ default to using `MaybeSignal` because it is the only really usable property type. However, this basically gives up the entire convenience around copyable signals in general. This discourages to actually use `MaybeSignal`. Isn't it harmful for the ecosystem if component authors start writing a component using `Signal<T>` and it then becomes a significant hurdle to use it with a plain `T`?

As a general comment: Coming from the JS (rather TypeScript) world, having to make this choice of dynamic vs non-dynamic props feels rather dull. I'm wondering all the time, why they don't have to make this distinction -- in Solid/Svelte a plain `T` can simply be either dynamic or non-dynamic without any code change necessary. It feels like a major productivity loss, if switching from dynamic to static and vice versa becomes a non-trivial refactoring. To avoid this, and to write maximally reusable components, basically all props should allow for dynamic values, because sooner or later a user may request to switch a certain prop from static to dynamic anyway. That's why I was hoping that the general solution is inviting and convenient to use. But `MaybeSignal` isn't a very inviting name, and the inconsistent `Copy` semantics make it even less appealing to use.

**Comment by gbj** [comment]
> As a general comment: Coming from the JS (rather TypeScript) world, having to make this choice of dynamic vs non-dynamic props feels rather dull. I'm wondering all the time, why they don't have to make this distinction -- in Solid/Svelte a plain `T` can simply be either dynamic or non-dynamic without any code change necessary. It feels like a major productivity loss, if switching from dynamic to static and vice versa becomes a non-trivial refactoring.

Yeah there's a technical answer and a values answer to this.

Technically, Solid and Svelte achieve this in two different ways, each of which is different from (for example) the reason React allows dynamic/static props: Solid by treating props as a reactive proxy object, Svelte because it compiles SvelteScript to something completely different (i.e., `export let` has no meaning in JavaScript, and Svelte compiles it to have a particular meaning), and React because none of its reactive types are wrapped anyway, because that's how its model works. Rust doesn't have a proxy type so we can't quite do the Solid approach, we don't do anywhere near the level of code transformation that Svelte is doing, and the execution model's quite different from React.

On the level of values: from my perspective, one of the core values of Rust is the concept of zero-cost abstractions, i.e., that you only pay the cost of what you need. `MaybeSignal<T>` is a zero-cost abstraction: if you need a signal (which has some cost to create and track), it's a signal; otherwise, you only pay the cost of the plain `T`. Likewise, allowing someone to have a prop that's just `String` or just `bool` means they don't pay the cost of a `StoredValue` or a `Signal` for it, just a string or a bool. In my own application and in our public APIs there are plenty of times you only want/need a static prop, so it makes sense to me not to require the cost of it possibly being dynamic if it really doesn't need to be.  

> To avoid this, and to write maximally reusable components, basically all props should allow for dynamic values, because sooner or later a user may request to switch a certain prop from static to dynamic anyway. That's why I was hoping that the general solution is inviting and convenient to use. But `MaybeSignal` isn't a very inviting name, and the inconsistent `Copy` semantics make it even less appealing to use.

On the name, fair enough and if there's a more inviting name, feel free to suggest one; we can even make it a separate, `Copy` type with a better name!

> It still feels a bit inconsequential. One of the main features of letpos compared to other libraries is that it actually tries to avoid the cloning madness. In principle, we _should_ default to using `MaybeSignal` because it is the only really usable property type. However, this basically gives up the entire convenience around copyable signals in general. This discourages to actually use `MaybeSignal`. Isn't it harmful for the ecosystem if component authors start writing a component using `Signal<T>` and it then becomes a significant hurdle to use it with a plain `T`?

In terms of ergonomics I'd probably make a distinction between what's ergonomic for a library author and a library user, i.e., if you're creating a component library and you use `MaybeSignal<T>`, it's more inconvenient for you but more performant for your users. If you use `CopyMaybeSignal<T>` (or a better named version :smile:) it's more convenient for you and less convenient for your users. That may be the right trade-off, and the small performance difference may be worth it, but that's the trade-off. 

> Would there be a possibility to optimize `StoredValue<T>` for the `T: Copy` case to become a noop?

Just to be clear, actually copying a `Copy` type and putting a `Copy` type in a `StoredValue` do different things. Copying a `bool` type into two different closures copies it by value; mutating one of them won't mutate the other. Copying a `StoredValue<bool>` into two different closures is basically copying the original bool by reference; mutating the `StoredValue` in one and then reading it in the other will give you the mutated value. `StoredValue` is like a `Copy`able interior-mutable type (`Rc<RefCell<T>>`) so making it a noop would mean the semantics of `StoredValue<_>` are different depending on whether the type is `Copy` or not.

***

I'm very open to including it in the copyable version in the library as a distinct type from `MaybeSignal` if you think it's useful in general... Thoughts on naming?

**Comment by gbj** [comment]
Oh I should add one note: the main advantage of `MaybeSignal` over a version backed by a `StoredValue` is that with the raw `T` you own `T`, whereas with `StoredValue` you can only either clone it or get a reference.

**Comment by gbj** [comment]
Good news. 0.5.0 no longer requires a `Scope` argument to create a signal or stored value. This makes it easier to work with a bunch of Rust traits, as we no longer need a special additional argument for many things. This means I can implement `From<T> for Signal<T>`, which means that you can do something like
```
#[prop(into)] name: Signal<String>
```
and pass it a `String` prop rather than `Signal::derive(cx, || value)`

The overhead of this is ~a `StoredValue`.

This means that basically on 0.5.0-alpha3 and forward, `Signal<T>` will be the correct way to do what you're asking: get a `Copy` signal that may or may not actually be reactive as a prop. `MaybeSignal` will still exist and is technically more efficient in the non-reactive case but both will be available.

**Comment by gbj** [comment]
Closing this as "completed in 0.5.0-beta" even though it hasn't been merged into main yet.
