### ISSUE TITLE
Suspense fallback not loading when wrapped in in a router view

### ISSUE THREAD

**Issue by ogesaku** [leptos-rs/leptos#1100]
Hi,

I want to wrap a view declared in PostsListing and used in a Route. When I do so the suspense element does not render fallback and I can see a strange error in devtools. Everything works correctly when I skip the `<Wrapper>`.  Could you help?

```rs
#[component(transparent)]
pub fn Blog(cx: Scope, prefix: &'static str) -> impl IntoView {
    // ...
    view! { cx,
        <Route path=prefix view=|cx| view!{cx, <Outlet />} >
            <Route path="" view=move |cx| view! {cx, <PostsListing prefix=prefix.clone()/> } />
            // ...
        </Route>
    }
}

#[component]
fn Wrapper(cx: Scope, children: Children) -> impl IntoView {
    view! { cx,
        <p>"HEADER"</p>
        {children(cx)}
        <p>"FOOTER"</p>
    }
}

#[component]
fn PostsListing(cx: Scope, prefix: &'static str) -> impl IntoView {
    // load the posts
    let posts = create_resource(cx, || (), |_| async { list_post_metadata().await });
    let posts_view = move || {
        posts.with(cx, |posts| posts
            .clone()
            .map(|posts| {
                posts.iter()
                .map(|post| view! { cx, <li><a href=format!("{}/{}", prefix, post.id)>{&post.title}</a></li>})
                .collect_view(cx)
            })
        )
    };

    view! { cx,
        <Wrapper>
            <h1>"My Great Blog"</h1>
            <Suspense fallback=move || view! { cx, <p>"Loading posts..."</p> }>
                <ul>{posts_view}</ul>
            </Suspense>
        </Wrapper>
    }
}
```
([full example](https://github.com/ogesaku/start-axum/blob/main/src/blog.rs))

Error in chrome developer tools:
```
At src/blog.rs:39:15, you are reading a resource in `hydrate` mode outside a <Suspense/> or <Transition/>. This can cause hydration mismatch errors and loses out on a significant performance optimization. To fix this issue, you can either: 
1. Wrap the place where you read the resource in a <Suspense/> or <Transition/> component, or 
2. Switch to using create_local_resource(), which will wait to load the resource until the app is hydrated on the client side. (This will have worse performance in most cases.)
```

Error is strange because the resource loading is executed in line src/blog.rs:53 (inside `<Suspense>`)

**Comment by gbj** [comment]
I'm fairly sure this is just because the Scope (`cx`) that you are moving into `posts_view` here is the Scope of the outer `PostsListing` component, not the scope of the Suspense. 

If you make it 
```rust
let posts_view = move |cx| {
        posts.with(cx, |posts| posts
            .clone()
            .map(|posts| {
                posts.iter()
                .map(|post| view! { cx, <li><a href=format!("{}/{}", prefix, post.id)>{&post.title}</a></li>})
                .collect_view(cx)
            })
        )
    };
```
and 
```rust
view! { cx,
        <Wrapper>
            <h1>"My Great Blog"</h1>
            <Suspense fallback=move || view! { cx, <p>"Loading posts..."</p> }>
                <ul>{posts_view(cx)}</ul>
            </Suspense>
        </Wrapper>
    }
```
does that change anything?

**Comment by ogesaku** [comment]
Thanks again. Now it works perfectly.

Could you tell what is the rule of thumb when it comes to passing the scope?
Most of my example come from [ssr_modes_axum](https://github.com/leptos-rs/leptos/blob/main/examples/ssr_modes_axum/src/app.rs#L123), where the scope is not passed from suspended element.

Do we need to pass the scope only when the suspended component is wrapped in another one?

**Comment by gbj** [comment]
> Could you tell what is the rule of thumb when it comes to passing the scope? Most of my example come from [ssr_modes_axum](https://github.com/leptos-rs/leptos/blob/main/examples/ssr_modes_axum/src/app.rs#L123), where the scope is not passed from suspended element.

Thanks, I'll fix the example to reflect a better way of doing it.

> Do we need to pass the scope only when the suspended component is wrapped in another one?

Basically, either moving the `move || { ...` that reads the inside the `<Suspense/>` or having it take a `Scope` argument works. Reading a resource checks for Suspense nodes that are in the same scope or a parent scope. In your example, the `move` moves the `Scope` of `PostsListing`, which doesn't have a Suspense anywhere in it; instead, the Suspense is under the child scope of the child component `Wrapper`. 

So the rule of thumb for now should be to either do
```rust
<Suspense>
{move || posts.with(cx, |posts| posts /* etc */ )}
</Suspense>
```
or 
```rust
let posts_view = move |cx| move || {
   posts.with(cx, |posts| posts /* etc */ );
}; 
// ...
<Suspense>
{posts_view}
</Suspense>
```

This is slightly awkward and I hope to solve it eventually with #918 but that will take some time. 

Note in the second example, I switched it to a function that takes `Scope` and returns another closure. At the moment, this second closure is technically unnecessary (because Suspense re-renders its children each time) but we usually use a dynamic child closure inside Suspense to keep open the possibility of not re-rendering the children and just doing a reactive update.

(I'm surprised the `ssr_modes_axum` example wasn't already broken, actually, but it may be that we don't initially create a new scope for Suspense and it just uses the parent component, I'd have to check.)

**Comment by ogesaku** [comment]
Thanks a lot!
