### ISSUE TITLE
Do you have any theme examples? 

### ISSUE THREAD

**Issue by songlinshu** [leptos-rs/leptos#1148]
Do you have any theme examples? For example:switch to dark mode 、light mode

**Comment by gbj** [comment]
[Here's an example using built-in dark-mode](https://github.com/leptos-rs/example-darkmode) via a `<meta>` tag. Otherwise, doing this will basically depend on what approach you take to styling. It's pretty straightforward to use the [`<Body/>` component](https://docs.rs/leptos_meta/latest/leptos_meta/fn.Body.html) to set a global class to manage this kind of theming.
