### ISSUE TITLE
feat: Put and Delete request options for Server functions

### ISSUE THREAD

**Issue by AnthonyMichaelTDM** [leptos-rs/leptos#1159]
**Describe the solution you'd like**
To be able to create server functions that operate on Put or Delete http requests in addition to existing Post and Get request types

**Describe alternatives you've considered**
Just using the existing get and post request types is possible, but is not ideal because it makes it harder to properly document the API (e.g., with the [Utoipa crate](https://github.com/juhaku/utoipa)). 
Generally, the type of request should indicate what will happen on the server-end, GET fetches some data, POST creates new data, PUT updates existing data, and DELETE deletes data. Without being able to make server functions that use PUT or DELETE, it is not possible to create a REST API while adhering to best practices.

**Comment by gbj** [comment]
My concern here is that PUT and DELETE requests are very bad from the perspective of progressive enhancement/graceful degradation, because they cannot be used with HTML `<form>` elements. Server functions are intended for a kind of ad hoc API call that's geared toward its use in user interfaces. 

For example, in the todo app examples, [`delete_todo`](https://github.com/leptos-rs/leptos/blob/3d75c71bfabc229ced6b22b862f65467977307e8/examples/todo_app_sqlite/src/todo.rs#L82) is implemented with a normal POST request server function. From one perspective this is "wrong," and should be a DELETE. From another perspective, because HTML forms don't support DELETE, this is significantly better, because it means that you can actually delete todos while WASM is still loading, on devices that don't support WASM, and on devices that have JavaScript disabled. From my perspective, adding maintenance burden, code complexity, and some runtime binary size to make it easier for people to have use server functions that can't gracefully degrade sounds like all downside.

**Comment by AnthonyMichaelTDM** [comment]
I definitely see your point here, maybe mentioning that specifically in the documentation/readme/guide ?
