### ISSUE TITLE
Add on(...) / watch(...)

### ISSUE THREAD

**Issue by maccesch** [leptos-rs/leptos#1177]
SolidJS has 

```js
createEffect(
  on(a, (value, prevValue) => { ... })
);
```

and Vue has

```js
watch(a, (value, prevValue)  => { ... })
```

SolidJS-USE actually provides a `watch` that is just a shorthand for `createEffect(on(...))`.

I kind of hacked a `watch` together in leptos-use but wouldn't it make sense to have sth like this in core leptos? IMO ideally like the `watch` from Vue where the returned function removes the watcher.

If you agree I'd like to try my hand at this.

**Comment by gbj** [comment]
I haven't used either of these functions. Is the idea to be able to provide an explicit list of dependencies you want to track, instead of using the usual automatic dependency tracking? 

Does it need to be implemented in the core? i.e., can it be implemented in `leptos-use` or is there some missing API?

**Comment by bram209** [comment]
> I haven't used either of these functions. Is the idea to be able to provide an explicit list of dependencies you want to track, instead of using the usual automatic dependency tracking?

Yes indeed, see:

> For convenience, Solid has an on helper that enables setting explicit dependencies for our computations. This is mostly used as a terse way to be even more explicit about which Signals are tracked (and not track any other Signals, even if they are read). In addition, on provides a defer option that allows the computation not to execute immediately and only run on first change.

https://www.solidjs.com/tutorial/reactivity_on

**Comment by maccesch** [comment]
@gbj It can be (is already) implemented in leptos-use but to "stop" the watch it requires an `is_active` signal that is checked in the closure of the `create_effect` and if `false` the closure returns. So the handler is not really removed. And since it has to be done all inside a `create_effect` the signals accessed inside the handler are still tracked. 

This is the implementation: https://github.com/Synphonyte/leptos-use/blob/main/src/watch.rs
Docs: https://leptos-use.rs/watch/watch.html

Another very useful thing is to have in the `watch` function is convenient access to the previous value in the handle.

If we decide to implement this I'd like to vote for `immediate` as Vue has it instead of `defer`. To me that is just more understandable / readable. But I might be biased, coming from Vue.

**Comment by gbj** [comment]
Hey, sorry for my slow response here. I wanted to make sure I had time to really look at the `watch` implementation you have already.

I am usually hesitant to add additional things to the core if they can be implemented in a library, because it just adds to the maintenance burden and makes it harder to change APIs because it then requires a semver update for the whole library and the rest of the ecosystem.

In this case, though, I can see how the implementation would benefit from at least one `leptos_reactive` internal, which is related to your point about the `is_active` signal. 

First off, re: the current implementation: note that because dependencies are dynamic, when the `is_active` signal flips to `false`, the watcher effect is now no longer subscribed to any of the dependencies, only to `is_active` (which could, hypothetically, flip to `true` again, although of course that's not actually possible given the API here.) So the memory used for the effect is not reclaimed, but the effect will not even attempt to re-run when any of the dependencies change; it no longer depends on them.

However, being able to explicitly `.dispose()` of the effect would be a bit better. It's possible to call `.dispose()` on a signal or a memo, but `create_effect` doesn't actually return anything, so you don't get something that can be disposed. Internally, however, these are all just reactive nodes, so `leptos_reactive` *can* dispose of an effect in this situation.

The benefits to implementing this internally, then, would be 
1) saving the cost of creating the `is_active` signal,
2) reclaim the cost of the effect if/when it's stopped

This seems reasonable to me to accept, if you want to try implementing it.

One more note w.r.t. the behavior: it seems to me that `wrapped_callback` maybe should add an untrack (something like `cx.untrack(move || callback(/* */))`). Otherwise, I think this will track *both* the dependencies, *and* any other signals accessed inside the callback. Not sure if that's the intended behavior but it's slightly different from what at least Solid does here. (Not sure what Vue does.)

**Comment by maccesch** [comment]
No worries at all. Thanks for taking the time! 

I totally agree. I’ll try to implement it ASAP.
