### ISSUE TITLE
lazy loading and resumability ala qwik

### ISSUE THREAD

**Issue by tzual** [leptos-rs/leptos#12]
consider adopting ideas from qwik framework.

leverage seralization on the client to enable:
* lazy loading components - makes the app a lot faster to start
* resumability between sessions - better user experience

i believe qwik is bringing some inovative ideas into the web app world and since this project is still in early development you can still possibly incorporate them.

**Comment by gbj** [comment]
Oh, totally! In fact one of the reasons the reactive system in this library uses index-based arena allocation is that it means the whole reactive system can be serialized and deserialized. 

I've experimented in the past with Qwik-style resumability in Rust. The main blocker right now is the Wasm bundle splitting story, which is not great. There's been some progress with the wasm-split tool from binaryen recently, and talk of integrating that with wasm-bindgen. 

So, Leptos isn't resumable at the moment but has been designed so far for future resumability.

**Comment by benwis** [comment]
Very cool! I too have been eyeing wasm split with the idea of Qwik-style resumability. Hoping we can get that soon

**Comment by matthewharwood** [comment]
Is how qwik serializes events to HTML on the server side to client. They call this resumability
https://github.com/google/jsaction

**Comment by gbj** [comment]
> Just wondering how feasible it is really...
> Javascript can serialize most functions (not all but most) and deserialize them using eval.
>
> How does one do the same thing for rust functions?

You don't need to serialize the functions, per se. You just need to know which signals are updated from which callback functions (this is by far the hardest part), and be able to code split such that you can load the correct function from Wasm as needed (this is also hard.)

Qwik has put a ton of work into both of these things in a language they're *much* easier in.

> Seems to me that this is only a possibly valid approach for javascript and then again I jave doubt about the arguments that this is much better... The resumability approach, while interesting, seems to be at best an early optimization of app startup time.
> 
> There are probably other tradeoffs. Just wondering there as I'm trying to see below the marketing.

You're 100% correct here. Qwik's team pushes resumability as the answer to every problem and the best thing ever. In reality, we can probably get a *lot* of the benefit with much-lower-hanging fruit like partial hydration/islands, and hybrid routing like Solid is working on right now.

**Comment by saolof** [comment]
Resumability may have other advantages beyond just bundling/lazy loading, such as saving state in local storage. 

Even if you don't load the code as granularly as qwik, resumability still makes hydration a lot easier.

**Comment by blueray453** [comment]
Just curious, Qwik Optimizer is written in Rust. Is leptos reusing that?

**Comment by gbj** [comment]
> Just curious, Qwik Optimizer is written in Rust. Is leptos reusing that? 

I don't think this would be plausible. Qwik's optimizer may be written in Rust, but it's a tool for doing static analysis of JavaScript files to do code extraction, etc. Some of the same principles may well apply to trying to build resumability into a Rust framework but the optimizer itself couldn't be reused in any meaningful sense, I don't think.

**Comment by jbms** [comment]
I've built a prototype implementation of code splitting with lazy async loading for rust wasm32-unknown-unknown.  See https://github.com/rustwasm/wasm-bindgen/issues/3939

**Comment by gbj** [comment]
@jbms This is extremely good news. I've only skimmed your post so far but explicit module splitting is exactly what we need, not so much for resumability as for route-level code splitting, which would be fantastic. I will look at this more deeply.

**Comment by gbj** [comment]
Despite the interest, I'm going to close this as a mixture of "not planned" and "on the radar."

**Lazy loading**: This part is very much on our radar, and we have plans to incorporate the excellent `wasm-split` work by jbms above into cargo-leptos. The new router has been designed to work well with async/lazy-loaded components, and I have made some demos showing that this is a plausible path forward for us.

**Resumability**: Qwik-style resumability *sounds* good, but over the last two years I've come to the conclusion that it is a net negative, especially for a WASM-based framework. In the end, this mostly comes down to the cost of serialization/deserialization. Qwik ends up storing a large amount of data in HTML, to be lazily deserialized. That's not awful in and of itself, but deserialization is relatively expensive for WASM frameworks in terms of bundle size. Ironically this means that in the pursuit of faster load times, you slow load times down significantly because the binary that needs to be loaded to deserialize the resumable bits is much larger.

I have put a *lot* of thought over the last three years or so into ways to make a resumable Rust/WASM framework — research into serializing/deserializing closures so we know what signals are used in an event listener, etc. In fact I started a prototype of a resumable framework six months or so before I started working on Leptos. Over this time I've come to the conclusion that it's just not worth it.

We do have a very good partial-hydration solution with islands, which allow you to remove a large % of the client-side WASM. The combination of islands and lazy-loading will be my strategy going forward for fast loading/fast TTI.

**Comment by matthewharwood** [comment]
Hey @gbj,

Thank you for your thoughtful insights and the work you've put into this! I was wondering if you could share your research in a more packaged format—perhaps as a blog post or some documentation. I’m really eager to understand what makes serialization so costly in WebAssembly. Maybe there is a feature where your research along with progress on compression or whatever bottlenecks you identified open up wider...

I’m not suggesting that the community should take this on more than you already have; rather, I believe we could all benefit from your depth of research to avoid reinventing the wheel. 

Looking forward to your thoughts, and thanks again for your contributions!

**Comment by atdiar** [comment]
Not @gbj but having thought about it as well in go, I think the model of resumabilitt is simply that of a vm where one has full control over the adress space.

So fairly low level. There should be way to make the connections between a serialized wasm address space and the browser dom address space but then this is exactly back to square one: the connection in question is what is colloquially called 'hydration' .

If we had full control over a page address space we could just copy paste the state and be done with it.

Maybe that will be possible in the future if it's not endangering the sandbox security model. That could be some kind of virtual model using offsets.

But more than that, replayability has advantages beyond implementing ssr: livereloading and debugging. 
So it's not a net negative at all. It's even unlikely to be the slowest part anyway. 
But again, my impression might be colored, I do think that this is some form of premature optimization.

**Comment by gbj** [comment]
> Thank you for your thoughtful insights and the work you've put into this! I was wondering if you could share your research in a more packaged format—perhaps as a blog post or some documentation.

@matthewharwood You're welcome! I'm not sure where this would exist as documentation (documentation on what? it's an explanation of a non-feature, after all) and I don't have a blog, but I'll write this up here for now.

I am going to write my response starting from the premise that Qwik-style resumability is essentially a performance optimization that has to do with minimizing the amount of blocking work that needs to be done between the moment the HTTP response returns to your browser and the moment that your application becomes interactive, i.e., optimizing for TTI (time to interactive) and similar metrics. Qwik achieves this by avoiding "hydration" (running the same application code in the client, to make the application interactive, that you ran on the server to render it to HTML.)

I think this is an accurate description of the goals of Qwik/resumability. To the extent others see other benefits, those probably won't be covered here.

That said:

> I’m really eager to understand what makes serialization so costly in WebAssembly. 

There are two components here that play into it:
**1. Binary/bundle size**: `JSON.parse` is built into the web browser. It has 0kb cost in terms of binary size. Because JavaScript is a dynamically-typed language, this means you can deserialize from a string in a custom attribute to a JavaScript object with 0kb of JS dowloaded or parsed. Because the framework controls both ends, it can assume that the JSON in that element is correctly formed and do very little validation.

On the other hand, JSON serialization from a `String` into an arbitrary Rust type is *not* shipped in the browser. It must be compiled to WASM that is shipped to the browser, downloaded, and compiled before any deserialization of resumable types can happen. In my experience, typed JSON parsing crates (whether `serde_json` or `serde_lite` or `miniserde`) have quite significant binary-size cost. I don't have numbers at hand; feel free to run experiments yourself.

Could this potentially be minimized by building a custom deserializer that builds on top of `JSON.parser` and then assumes that it's well formed and avoids validating it? Sure, but it will be larger than 0kb, naturally. And also...

**2. Runtime cost**: WASM does not have access to strings: it only has floats and ints, essentially. The way that crates like `wasm-bindgen` work for all other data types is essentially by keeping a heap of data in JS-land, and giving numeric references to it in WASM. Moving strings back and forth across the JS/WASM barrier is the primary runtime performance cost of using WASM, because it requires both a bytewise copy and (in the case of Rust→WASM) also transcoding (JavaScript uses UTF-16 strings, Rust uses UTF-8). 

Taken together, these two factors mean that, all else being equal, any strategy like "read string values out of the DOM and parse them" is going to take significantly more time if you do it from Rust/WASM than if you do it from JS. "How much more time?" is a reasonable question and will, of course, vary. I definitely think other people should do experiments to try to figure out if this is a plausible path forward for any Rust/WASM framework!

It's also important to note that 
**3. Resumability has a cost.** Resumability is often framed as a pure win. Surely, executing less JavaScript on startup is good? It is! However, resumability also requires serializing large amounts of data into HTML. Just for reference, here's the landing page of qwik.dev, showing the amount of additional "Qwik stuff" that needs to be injected into HTML

<img width="544" alt="Screenshot 2024-10-13 at 7 06 46 PM" src="https://github.com/user-attachments/assets/d074df68-d6d8-4bbf-b773-b974da8e670d">

Marker comments aren't inherently wrong, and I've been guilty of adding more things into HTML in versions 0.1-0.6 than is strictly necessary. 0.7 makes pretty significant moves toward removing that as much as possible.

Downloading additional bytes of HTML is not zero-cost; nor is parsing it. The attributes here actually exist in the DOM, which has a cost; etc.

That's not to say that this outweighs the benefits. What I'm saying is that there is a cost to serializing data into HTML; and given that the benefits of resumability are smaller for WASM than they are for JS (due to the additional costs above), the tradeoff seems worse to me.

**Comment by matthewharwood** [comment]
@gbj this is a fantastic write up. Fully understand now!

**Comment by dxps** [comment]
@gbj  With resumability set aside, the lazy loading seems doable as per your [wasm-split-prototype](https://github.com/gbj/wasm-split-prototype), but I assume it's a matter of having [this](solved). Is that correct?
And speaking about your prototype, for anyone that would like to play with it locally, can you please put the minimal instructions to get it started (like `trunk serve` but from which location)?

Thanks in advance for the feedback!

**Comment by gbj** [comment]
@dxps There are working prototypes; it does *not* require direct support from `wasm-bindgen` as discussed in the linked issue. I've slowly been plugging away at building the wasm-splitting code directly into a future version of `cargo-leptos` but it is not in a state that's publicly useful right now.

If you want to run the prototype you can to [this versioh](https://github.com/gbj/rustnation2025/tree/main/wasm-split-prototype) and run `./run.sh` (or run `build.py` and then use any static file server you want.)

**Comment by dxps** [comment]
@gbj Many thanks for the feedback and example! 🙏 
I'll dive into the example to understand how it works.
Just played with it, it looks very promising, even if it crashes when you go from view C to any other (view A or B) with a generic error: _Uncaught RuntimeError: null function or function signature mismatch_.

**Comment by gbj** [comment]
@dxps One of the drawbacks here with `wasm-bindgen` not wanting to integrate the tool, and the original creator not interested in maintaining it, is that things like this will pop up over time; this error did not exist in February when I created and showed off the demo, but I do see it now 😅 I have encountered similar weird things when running other experiments with it. It is in a very early stage and I have very limited time, hence why it has been so slow to move along.

**Comment by jbms** [comment]
I might be able to look into the problem --- I have very limited time but I do intend to use wasm-split for a project later so I'd like to see it working.

**Comment by dxps** [comment]
@gbj & @jbms  I thank you both for the feedback! 🙏 

Having a modularized WASM based web app - done with Leptos in this case - gives you the confidence that you can build any sized (medium or big) webapp and have it manageable from UX perspective.

---

PS 

That cryptic (ok not that cryptic, but it doesn't give you more details, not to mention a stack trace) reminds me of a recent experience developing a (close to) medium web app ([this one](https://github.com/dxps/cognitive)) using Dioxus. The bottom line was that - ignoring the compile times (which ranged from 1s to 5s) - I had to add UI code in baby steps, since otherwise, those WASM errors thrown in the browser were totally useless. 

I did very similar web app using a Golang based framework ([go-app](https://go-app.dev/)) and the development experience was amazing. Besides the compile times (which took at most 1s), the WASM errors in the browser were very explicit, giving you the stack trace.

So, I believe this might be doable with Rust based projects as well.

If this would be doable in Leptos, I would really like to write a book about it 🤓 
(since I postponned the writing for a book using using Axum + Dioxus, due to the aforementioned (and others) issues.
