### ISSUE TITLE
`Transition` doesn't like closures in variables with SSR

### ISSUE THREAD

**Issue by M1cha** [leptos-rs/leptos#1231]
**Describe the bug**
This is quite specific.
- When using SSR
- and using a `create_resource` that uses a signal
- and using a `Transition`
- and moving the closure that renders the resources data out of `view!` into a variable

Then the initial load is empty with warnings like these:
```
element with id 1-4 not found, ignoring it for hydration [ssr_modes.js:483:9](http://127.0.0.1:3000/pkg/ssr_modes.js)

At src/app.rs:17:15, you are reading a resource in `hydrate` mode outside a <Suspense/> or <Transition/>. This can cause hydration mismatch errors and loses out on a significant performance optimization. To fix this issue, you can either: 
1. Wrap the place where you read the resource in a <Suspense/> or <Transition/> component, or 
2. Switch to using create_local_resource(), which will wait to load the resource until the app is hydrated on the client side. (This will have worse performance in most cases.)
```

**Leptos Dependencies**
main branch at c55067ab7ca04540344a48d788b2ba9e7805e732

**To Reproduce**
Based on ssr_modes_axum:
```rust
use leptos::*;
use leptos_meta::*;

#[server(ListPostMetadata, "/api")]
pub async fn list_post_metadata() -> Result<usize, ServerFnError> {
    Ok(42)
}

#[component]
pub fn App(cx: Scope) -> impl IntoView {
    provide_meta_context(cx);

    let refresh = create_rw_signal(cx, 0usize);
    let posts = create_resource(cx, refresh, |_| async { list_post_metadata().await });

    let render_posts = move || {
        posts.with(cx, |res| view!{cx, <p>{format!("{res:?}")}</p>})
    };

    view! { cx,
        <Stylesheet id="leptos" href="/pkg/ssr_modes.css"/>
        <Title text="Welcome to Leptos"/>

        <h1>"My Great Blog"</h1>
        <button on:click=move |_| refresh.update(|n| *n += 1)>"Refresh"</button>
        <Transition fallback=move || view! { cx, <p>"Loading posts..."</p> }>
            <ul>
                {render_posts}
            </ul>
        </Transition>
    }
}
```

**Expected behavior**
The Render should work on the first load.

**Additional context**
- It works with a Suspense
- It works when not using a signal for the resource
- It works when the client triggers the signal

**Comment by gbj** [comment]
This works correctly with the following changes:
```rust
let render_posts = move |cx| move || {
    posts.with(cx, |res| view!{cx, <p>{format!("{res:?}")}</p>})
};
// ...
<ul>
    {render_posts(cx)}
</ul>
```
This also works:
```rust
<Transition fallback=move || view! { cx, <p>"Loading posts..."</p> }>
    <ul>
        {move || {
            posts.with(cx, |res| view!{cx, <p>{format!("{res:?}")}</p>})
        }}
    </ul>
</Transition>
```
The reason for this is somewhat unfortunate and is part of what will be resolved eventually by #918. Basically, in your version, the `render_posts` closure captures and uses `cx`, the `Scope` of the `App` component, but this is actually the parent scope of the `Transition` component, not the scope of the `Transition` itself. This means that when the resource checks "am I inside a Suspense/Transition?" the answer is "no." 

In my first solution, `render_posts` becomes a function that returns a function — and is then called with the scope of the `Transition`. In the second solution, the closure is just inlined, and also receives the correct scope. This is because being "under" the `Transition` in the `view` macro means it actually receives a shadowed `cx`, which is the correct `Scope` for that `Transition`.

Like I said, this is a known but unfortunate state of affairs and is part of the goal of the larger changes in #918.

***

However, your additional context is interesting.
> * It works when the client triggers the signal
Expected, this is just a "hydrating server-rendered content" issue, not a "rendering in the browser" issue.
> * It works when not using a signal for the resource
I'm actually not able to reproduce that—it does still cause an issue if I use `|| ()`—and that's reassuring, as I would have no idea why this was the case.
> * It works with a Suspense
This is really interesting and not something I would have realized. This is because `Suspense` right now is defined as a "transparent component" and `Transition` is not. This means that `Suspense` doesn't actually get its own child `Scope`, but shares the parent's, which means it avoids this very particular issue. I should be able to adapt `Transition` to do the same thing without causing any real issues.

This will not solve the larger problem, but is quite useful for avoiding these kind of weird behaviors in the simpler cases like this!
