### ISSUE TITLE
shoud () really be IntoView ?

### ISSUE THREAD

**Issue by jrouaix** [leptos-rs/leptos#1248]
Not a bug, not a feature.

I just lost few hours because of a `;`
![image](https://github.com/leptos-rs/leptos/assets/2705498/fee29f97-600a-4bec-8cc0-63e8b1467028)

I think I could not be the only one, and perhaps () being IntoView is somehow more a trap than a nice to have feature ?

What do you think here ?

**Comment by gbj** [comment]
First off: Sorry that this happened. It is a real pain, and I've seen it bite 1-2 people before.

There are plenty of good use cases for `()` being `IntoView`. For example, it's the most straightforward way to say "render nothing"
```rust
view! { cx,
  <Suspense fallback=|| ()>
    {move || /* whatever */ }
  </Suspense>
}
```

The `#[component]` macro actually now checks to make sure you don't put a `;` after the end of a `view` macro and accidentally return `()`:

```rust
// doesn't compile
#[component] 
fn Button(cx: Scope) -> impl IntoView {
  view! { cx,
    <button/>
  }; // errors because of this semicolon
}
```
Unfortunately this couldn't catch yours because of how it's nested/where it is in the view.

It may be possible to add some "did you really mean to do this?" warnings in cases like this, but again, it's hard because sometimes `()` really is correct and expresses what you're trying to do. We could do a "must use" on views in general so that the bits you've blurred out would warn you. I'd have to explore that. So I'll leave this open and treat it as a tracking issue for ideas on how to prevent footguns like this.
