### ISSUE TITLE
A running list of small DX improvements

### ISSUE THREAD

**Issue by gbj** [leptos-rs/leptos#1310]
I'm going to start compiling a list of small tips and DX improvements, for eventual inclusion in the docs. Feel free to post things here that you've found helpful along these lines.

## Autocompletion inside `#[component]` and `#[server]`

Because of the nature of macros (they can expand from anything to anything, but only if the input is exactly correct at that instant) it can be hard for rust-analyzer to do proper autocompletion and other support.

A user on Discord (Sadra) suggested a great workaround. You can tell rust-analyzer to ignore certain proc macros. For `#[component]` and `#[server]` especially, which annotate function bodies but don't actually transform anything inside the body of your function, this can be really helpful. Here's the syntax for a VS Code `settings.json`. There are probably equivalent ways to do this for other editors.
```json
    "rust-analyzer.procMacro.ignored": {
        "leptos_macro": [
            "server",
            "component"
        ],
    }
```

**Comment by stewartadam** [comment]
I'm getting started with Leptos and if it helps, here are few things I would have found very helpful:

1. A more streamlined way (or, step-by-step examples) of providing values to the server-side context - a common use case would be some form of provider or session manager during initialization that server functions need to access.

   In particular, more details on Axum `.with_state()` and Leptos route handler state extraction. My naive assumption was that `.with_state()` was something you could layer multiple times, but evidently there's only *one* state struct that gets configured so you have to write your own struct, compose any existing state (like `LeptosOptions`) into it, and then write your own handler to extract your new state type. This also means you have to write a similar custom handler for server function routes if you want the state available there too.

   An example implementing this is available in the [session_auth_axum](https://github.com/leptos-rs/leptos/blob/main/examples/session_auth_axum/src/main.rs#L24C56-L24C64) example, but it would be nice to have these steps/implications spelled out in the docs.

   There's also lots of docs-worthy interesting tidbits about server state in this thread: https://discord.com/channels/1031524867910148188/1072251332448223343

4. Explicit guidance not to use `./` prefix on any Leptos-related relative paths specified in `Cargo.toml` until https://github.com/leptos-rs/cargo-leptos/issues/99 can be addressed - otherwise, `cargo leptos watch` fails to monitor files correctly.

5. Although not *strictly* about a pure Leptos deployment, additional guidance on configuring TailwindCSS would be welcome.
   1. Examples have varying setup instructions as reported here: https://github.com/leptos-rs/cargo-leptos/issues/161.

      It would be ideal to document a canonical tailwind setup (not just in examples) that integrates with cargo-leptos, e.g. in `Cargo.toml`:

      ```toml
      # Optional, tailwind configuration. Activates the tailwind build.
      tailwind-input-file = "style/tailwind.css"
      ```

      and the `style/tailwind.css` file:

      ```css
      @tailwind base;
      @tailwind components;
      @tailwind utilities;
      ```

   2. Tailwind also expects `node_modules` to be next to its `tailwind.config.css`, which for most of the samples is at the root of the crate.

      This makes installing plugins non-obvious, because running `npm install plugin` in the root makes that plugin's javascript unavailable from the asset directory, and running it from the asset directory requires using an explicit relative path starting with `./` in the tailwind config to get the import right (and so varies from the typical setup docs for the plugin).

      Here's an example:

      ```js
      /** @type {import('tailwindcss').Config} */
      module.exports = {
      darkMode: 'class',
      content: {
         relative: true,
         files: [
         "*.html",
         "**/*.rs",
         "public/node_modules/preline/dist/*.js"
         ],
      },
      theme: {
         extend: {},
      },
      plugins: [
         require('./public/node_modules/preline/plugin')
      ],
      }
      ```

**Comment by RottenFishbone** [comment]
For anyone using neovim with [lspconfig](https://github.com/neovim/nvim-lspconfig), the provided vscode config can be written as:

```lua
require('lspconfig').rust_analyzer.setup {
  -- Other Configs ...
  settings = {
    ["rust-analyzer"] = {
      -- Other Settings ...
      procMacro = {
        ignored = {
            leptos_macro = {
                "server",
                "component",
            },
        },
      },
    },
  }
}
```

**Comment by peteringram0** [comment]
Helix Users

.helix/languages.toml
```text
[[language]]
name = "rust"
config = { procMacro = {ignored = {leptos_macro = ["component"]}}}
```
