### ISSUE TITLE
Async renders head meta twice

### ISSUE THREAD

**Issue by alexichepura** [leptos-rs/leptos#1317]
**Describe the bug**
Examples ssr_modes and ssr_modes_axum both render this twice in `Async`:
```html
<title>My first post</title><link id="leptos" href="/pkg/ssr_modes.css" rel="stylesheet" leptos-hk="_0-3"/><meta name="description" content="This is my first post" id="_2-7"/>
```

**Leptos Dependencies**
Main branch, 0.4.2 same

**Screenshots**
![leptos-async-2x-meta-bug](https://github.com/leptos-rs/leptos/assets/5582266/2a6e1856-0ea4-4530-86c6-71a5e7b6c406)

**Comment by gbj** [comment]
Thanks for noticing this, and good work! It should be relatively easy to fix — at one point I moved the metadata from being inserted at the end of the head to the beginning of the head, because of an issue related to the ordering of script tags relative to the hydration code (#694). Sounds like this was a leave-behind, ie it’s just being inserted in *both* places. 

Which… as much as we all love meta tags, is probably overkill :smile:

**Comment by alexichepura** [comment]
Fix confirmed. Thank you very much 👍
