### ISSUE TITLE
Need : Transforming data using pipes - like angular

### ISSUE THREAD

**Issue by leefordjudes** [leptos-rs/leptos#1322]
**Is your feature request related to a problem? Please describe.**
Need Transforming data using pipes - like angular
Ex: https://angular.io/guide/pipes

**Describe the solution you'd like**
I need to show the date with the format on display, but I keep it as datetime in struct,
and need to show f64 with format(currency, with cr & dr) on display.
and it's very useful for many situations 

**Describe alternatives you've considered**
and need to create custom transforming data pipe

**Additional context**
Kindly add this feature as early as possible.
or Is there any way to achieve this pipe functionality?

Thank you.

**Comment by gbj** [comment]
It sounds to me like this would best be implemented by you implementing `Display` or an appropriate method on your struct, and calling that to get the string you need for the view. 

What is the problem you're trying to solve that can't be solved in this way and requires additional support from the framework?

**Comment by leefordjudes** [comment]
yes, it's true, but for a single variable or calculated variable which came from signal, or derived signal - it needs a struct to implement display trait. if it came from the framework means it's helpful. anyway if you have any future plans on that, 
kindly implement that. 
and you can close this issue - if there's nothing to do.
thank you.

**Comment by gbj** [comment]
Maybe I'm misunderstanding. The idiomatic way that behavior is implemented for different types in Rust is via traits. I'm not sure how we'd create something like a pipe
```rust
let my_date = Date { /* some custom date struct */ }
view! { cx,
  <p>{ my_date | date }</p>
}
```
without this requiring the invention of something like 
```rust
trait DatePipeable {
  fn to_formatted_date(&self) → String { }
}
```
(and then you'd implement that for whatever your struct is.)

My understanding is that using Angular pipes, rather than simply calling a function in the template, is largely a performance thing — pure pipes can be memoized away. That's completely fair but we have different idiomatic ways of doing that.

I guess I'd say, when you're developing an app with Leptos and you're coming from Angular, whenever you'd reach for a pipe you should probably instead call a function. I don't have any plans to implement something like pipes, with a special meaning inside the template.
