### ISSUE TITLE
CSP Headers / unsafe-inline vs nonce's

### ISSUE THREAD

**Issue by gbj** [leptos-rs/leptos#1334]
### Discussed in https://github.com/leptos-rs/leptos/discussions/1333

<div type='discussions-op-text'>

<sup>Originally posted by **sebadob** July 12, 2023</sup>
I am currently evaluating Leptos for a bigger upcoming project.  
I do have the prod ready template almost fully set up, before I can actually build some components and I guess, if it turns out nicely, I can provide this template back to the community,  It builds up on the axum starter with a few more additions to make it prod ready.

The last step I am taking a look at now is the CSP settings.  
I usually keep `unsafe-inline` for CSS for practical reasons, but for the rest I want to get rid of all unsafe stuff.

Usually, I do this with inserting `nonce`s on the server side and set a proper CSP for each request to be able to set `strict-dynamic` and a `nonce`.

So, after all this talking:  
**Is there a way to get access to a custom `index.html` with out of order streaming, into which I could insert `nonce`s in all places with a templating engine, or does leptos maybe even provide a way to insert nonces into all inline scripts it injects?**

The last value I needed was `wasm-unsafe-eval`, which I guess is the normal way of working with wasm currently. Leptos is now my first attempt with a wasm framework.</div>

@sebadob This is so clearly a good idea that I've just converted it into an issue so I can track it here.

Here's my understanding of the various places a nonce would need to be inserted:
1. Loading the JS/WASM module for hydration
https://github.com/leptos-rs/leptos/blob/e9665b34e5f5f926343d5be97115d3c90a20f507/integrations/utils/src/lib.rs#L73
2. The initial "pending resources" script tags, for out-of-order and in-order streaming
https://github.com/leptos-rs/leptos/blob/e9665b34e5f5f926343d5be97115d3c90a20f507/leptos_dom/src/ssr.rs#L234-L238 https://github.com/leptos-rs/leptos/blob/e9665b34e5f5f926343d5be97115d3c90a20f507/leptos_dom/src/ssr_in_order.rs#L132-L136
3. Script to insert an HTML fragment during out-of-order streaming
https://github.com/leptos-rs/leptos/blob/e9665b34e5f5f926343d5be97115d3c90a20f507/leptos_dom/src/ssr.rs#L335-L340
4. Script to resolve a resource value
https://github.com/leptos-rs/leptos/blob/e9665b34e5f5f926343d5be97115d3c90a20f507/leptos_dom/src/ssr.rs#L688-L695

And the response needs to include it in a `Content-Security-Policy` header, correct?

Do you think nonces are best provided by the user, or should the generation be built into the framework? 

I'm very open to feedback and guidance here, as it is not my strong suit.

**Comment by sebadob** [comment]
Yes, correct.  
In a few other projects I am using Svelte exported to static HTML. In certain places I have placeholders like
```html
<script nonce="{{nonce}}">
```
I then render these templates with askama and insert some shorter crypto safe base64 random values.  
In the CSP header, you can add the nonces in the header value, for instance
```rust
let value = format!(
    "default-src 'self'; script-src 'strict-dynamic' 'nonce-{}'; \
    style-src 'nonce-{}'; frame-ancestors 'none'; object-src 'none'",
    nonce, nonce,
);
```

I did some quick research on the `wasm-unsafe-eval`, which seems to be the default, since wasm is basically just "some random bytes" when the payload arrives in the browser, which is unsafe by definition. But since this is my very first "real" attempt with wasm, I have no experience with it yet. Maybe the nonce's do even work here too.

Another solution for this are SHA hashes. Working with these is a bit more tedious I found out, but it may be an option for a release build, once we can actually calculate a hash for the wasm binary. I am not sure if this option does even exist yet for wasm payloads. If hashes are an option, the CSP could maybe be just turned off in DEV mode and only be used for PROD.

Regarding the question where they should come from - I would say a nice default with a good UX would be, when the framework itself can generate them. This could maybe be done automatically depending on some prefix, that could also be added to custom Stylesheet links and so on, so the user has just full flexibility with adding custom resources.

I don't know about others, but I set CSP headers in every project. Maybe some people do not want them on purpose, so this could be an optional feature, I guess.



*Something else* I just added to my new template is precompression of static files, especially the compiled wasm binary.
I am compressing all files in `target/site/` to `gzip` and `br` and serve the compressed files in a custom handler for the routes. I don't know if an issue for such a feature does already exist. It just came to my mind as another possibility. 
This small custom handler and precompression logic in the `build.rs` reduced the hello world example in my case from ~330kB wasm to ~131kB (with brotli).

**Comment by gbj** [comment]
I think most likely the best option here is for

A default `nonce` or `csp` feature in Leptos — users can opt out if they don't want it for some reason.

This would:
- [ ] generates a nonce per render
- [ ] sets the appropriate header in responses
- [ ] use it in Leptos's own inline scripts
- [ ] provide it via context during SSR as a `Nonce(String)` struct
- [ ] automatically add it to any `<Script/>` or `<Style/>` components from `leptos_meta`

As a result, the whole app is "nonced by default." 

If a Leptos user wants to insert their own inline `<script>` or `<style>` elements, they can simply
```rust
view! { cx,
  <script nonce=use_context::<Nonce>(cx)>
```
or, even better,
```rust
view! { cx,
  <script nonce=use_nonce(cx)>
```

The convenient thing about this is that because `use_context` simply returns `None` if something is not found, and passing `None` as an attribute value simply means the attribute isn't there, this works for either server rendering (with the nonce provided via context) or hydrated client rendering (nonce not found, so `nonce` attribute isn't added.)

Any thoughts on a good Rust crate for generating the appropriate nonces?

**Comment by sebadob** [comment]
That sounds great.  

The last thing that came to my mind while thinking about it is, that it would be nice, if we could provide kind of a "template header" to `LeptosOptions` maybe. Most of my projects have default value that works, but other times you may want to allow cross origin image fetches or something like that.

If we could provide a template header, for instance something like 
```rust
"default-src 'self'; script-src 'strict-dynamic' {{nonce}}; style-src {{nonce}}; frame-ancestors 'none'; object-src 'none'"
```
during leptos options setup, then we would not even need to handle this with its own custom handler.

Regarding good crates - it is important to have a crypto secure random generator. I usually have [rand](https://crates.io/crates/rand) in my projects, which I use in such a case. It provides different ways of generating random bytes, crypto secure and pseudo random. This could maybe even be behind a feature flag for leptos, since pseudo random is less secure, but of course way faster.

We would only need this dependency on the server side, so we don't increase the wasm size.

**Comment by sebadob** [comment]
Ah btw, the CSP can be set inside a `<meta>` tag as well. This is maybe an easier option, since leptos needs to create the HTML content anyway.

**Comment by gbj** [comment]
> Ah btw, the CSP can be set inside a `<meta>` tag as well. This is maybe an easier option, since leptos needs to create the HTML content anyway.

Ah nice, this is also great because of the `<Meta/>` component... You can 
```rust
use_nonce(cx).map(|nonce| view! { cx, 
  <Meta
    http_equiv="Content-Security-Policy"
    content=format!("default-src 'self'; script-src 'strict-dynamic' \
      {nonce}; style-src {nonce}; frame-ancestors 'none'; \
      object-src 'none'")
    />
})
```
presumably somewhere in the root of your app/

**Comment by sebadob** [comment]
With the `<Meta>` component, it is even a nicer user experience I guess and the user can fully customize any CSP, while the framework could maybe just scan the `<meta>` tags and insert a possibly defined nonce in a CSP.  
I guess this would be the easiest and cleaned approach to this.

**Comment by sebadob** [comment]
Commented in the PR already, it is working nicely and such a cool feature!
Thank you!
