### ISSUE TITLE
missing field `active_class` in initializer of `leptos_router::AProps<H>`\nmissing `active_class`

### ISSUE THREAD

**Issue by songlinshu** [leptos-rs/leptos#1366]
```toml
leptos = { version = "0.4.3", features = ["csr"] }
leptos_router = { version = "0.4.3"}


use leptos::*;
use leptos_router::*;
#[component]
pub fn Link<H>(
    cx: Scope,
    href: H,
    #[allow(unused)] // TODO: Remove this when leptos's A component supports the title attribute.
    #[prop(into, optional)] title: Option<AttributeValue>, // TODO: This should be limited to string attributes...
    #[prop(optional)]
    exact: bool,
    #[prop(optional)]
    state: Option<State>,
    #[prop(optional)]
    replace: bool,
    /// Sets the `id` attribute, making it easier to target.
    #[prop(into, optional)]
    id: Option<AttributeValue>,
    /// Sets the `class` attribute, making it easier to style.
    #[prop(into, optional)]
    class: Option<AttributeValue>,
    #[prop(into, optional)] style: Option<AttributeValue>,
    children: Children,
) -> impl IntoView
where
    H: ToHref + 'static,
{
    let a = leptos_router::A::<H>(
        cx, AProps::<H> {
            href,
            exact,
            state,
            replace,
            class: None,
            id: None,
            children,
        },
    )
    .into_view(cx);
    view! { cx,
        <leptonic-link id=id class=class style=style>
            { a }
        </leptonic-link>
    }
}

**Comment by gbj** [comment]
It looks to me like you are manually building `AProps` rather than using the builder syntax or the view macro. The error message you are receiving is just saying that you are missing the optional property `active_class`, which was added recently. You can simply add `active_class: None` to the `AProps` struct for it to compile.

Adding this field to the `AProps` struct was probably technically a breaking change, but it would not break code using either the `view! { cx, <A ... /> }` or `AProps::builder()` syntaxes, which are the two intended/documented forms for building component props, so I did not think of it as such. Apologies for the inconvenience.

***

In the future, it's really helpful for me if you use the bug report template and fill out the relevant sections rather than deleting it and starting afresh. In this case I am able to understand what you're trying to communicate, but it is not easy, as the formatting is completely broken (see below), and the initial version before editing included almost no context at all.

<img width="950" alt="Screenshot 2023-07-16 at 7 41 49 PM" src="https://github.com/leptos-rs/leptos/assets/286622/2768f65d-e3b8-4dc9-b5fa-a78fe6acf404">
