### ISSUE TITLE
Rework leptos_axum generate_routes() to not be async

### ISSUE THREAD

**Issue by benwis** [leptos-rs/leptos#1392]
There's no reason that the generate_route_list() function needs to run the inner function inside a LocalSet, and this doesn't need to be async. Noting this here for myself to return to

**Comment by gbj** [comment]
Couple thoughts:
- Re: LocalSet: I *think* you're now correct. Initially it needed to be done because `generate_route_list()` is basically a render of `/`, so any resources created would try to spawn local tasks as usual and panic because there was no LocalSet. I think I actually turned off resources running during `generate_route_list()` at some point because it makes little sense. So this should now be fine.
- Re: async — If there's a good argument about a situation where someone needs to run `generate_route_list()` but can't do it async, I guess I'd be open to it. But I'm imagining a situation like someone deciding to do file-based routing in the future and wanting to do async file I/O or something. Or say we decide to build in static site generation, and need to read from the DB to generate routes. (Idk.) Removing async from the function signature now would be a breaking change now, and if we ever did need it to be async, adding it back would be another breaking change. So it seems fine to me to leave it, unless there's a reason it actually needs to be sync, rather than just that it doesn't need to be async.
