### ISSUE TITLE
AProps: inactive_class

### ISSUE THREAD

**Issue by bbstilson** [leptos-rs/leptos#1394]
**Is your feature request related to a problem? Please describe.**

There are times when you want some classes to be applied only when the link is inactive. For example, from [this tailwindui example](https://tailwindui.com/components/application-ui/application-shells/stacked):

```html
<div class="hidden sm:-my-px sm:ml-6 sm:flex sm:space-x-8">
  <!-- Current: "border-indigo-500 text-gray-900", Default: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700" -->
  <a href="#" class="border-indigo-500 text-gray-900 inline-flex items-center border-b-2 px-1 pt-1 text-sm font-medium" aria-current="page">Dashboard</a>
  <a href="#" class="border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center border-b-2 px-1 pt-1 text-sm font-medium">Team</a>
  <a href="#" class="border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center border-b-2 px-1 pt-1 text-sm font-medium">Projects</a>
  <a href="#" class="border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center border-b-2 px-1 pt-1 text-sm font-medium">Calendar</a>
</div>
```

You can see the active and inactive state shares classes, but they also have unique classes.

**Describe the solution you'd like**

An additional, optional prop on the `A` tag. 

**Describe alternatives you've considered**

Manually combining strings via `format!`

**Additional context**

I'm happy to take a crack at the implementation if this is a feature that would be welcome 🙂

**Comment by gbj** [comment]
You're very welcome to take a crack at it! One of the things that will be a consideration for me is the effect on WASM binary size. Every prop we add to a component involves has the potential to add binary size for all users.

In this particular case it seems to me that this is just
```
<A class="border-indigo-500 text-gray-900 inline-flex items-center border-b-2 px-1 pt-1 text-sm font-medium"
  active_class="border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700"
/>
```
i.e., that adding the `active_class` classes simply overrides the values of `border-indigo-500` and `text-gray-900`

I find it kind of frustrating that CSS frameworks push people toward solutions like this rather than styling your UI using CSS selectors like `[aria-current]`, which provides a really simple and correct way to do it, rather than adding additional runtime JS or Rust code to emulate CSS behavior. But I also know that I am shouting into the void here.
