### ISSUE TITLE
Server Function Extended HTTP Verb Support

### ISSUE THREAD

**Issue by dezren39** [leptos-rs/leptos#1409]
I request that server function encodings be expanded to allow user input of verbs, even if not recommended.
 
```
Why not PUT or DELETE? Why URL/form encoding, and not JSON?

    These are reasonable questions. Much of the web is built on REST API patterns that encourage the use of semantic HTTP methods like DELETE to delete an item from a database, and many devs are accustomed to sending data to APIs in the JSON format.

    The reason we use POST or GET with URL-encoded data by default is the <form> support. For better or for worse, HTML forms don’t support PUT or DELETE, and they don’t support sending JSON. This means that if you use anything but a GET or POST request with URL-encoded data, it can only work once WASM has loaded. As we’ll see [in a later chapter](https://leptos-rs.github.io/leptos/progressive_enhancement), this isn’t always a great idea.

    The CBOR encoding is suported for historical reasons; an earlier version of server functions used a URL encoding that didn’t support nested objects like structs or vectors as server function arguments, which CBOR did. But note that the CBOR forms encounter the same issue as PUT, DELETE, or JSON: they do not degrade gracefully if the WASM version of your app is not available.
```

I understand that WASM takes a while to load, I'm following a certain.. trend.. and have been looking into using leptos and axum with htmx. Htmx as a javascript library can possibly be embedded into an app and load faster than wasm, potentially allowing for form puts and deletes.

https://htmx.org/docs/#ajax

I'm not sure the stack is entirely the best idea, but as it's setup I'll be having to make my own delete endpoints separately from leptos to fully be able to build-out with htmx.

Maybe I'm really asking for an hxPut, hxPatch, and hxDelete encoding to be built in and autoload the js for me as-needed. ;-P

I would even wish for ActionForms that could hxDelete with a fallback to a post path that handled deletes or even if it just did nothing/showed-a-css-validation-error if the js didn't load somehow, but that starts getting messy. A lot can be integrated at the project level, but I think there might be some use for a leptos htmx cargo feature or something that adds some traits / features and a way to embed the htmx library automatically.

**Comment by sebadob** [comment]
I took a look at htmx myself some time ago and while is is an interesting approach on how to handle frontend building, I don't see a reason why I would would use it together with leptos. You simply just don't need it and I think it makes your stack over complicated and does not provide a real benefit.

I would either use just axum + httpx + askama (very important to have a good templating engine with it), or simply just leptos. And yes wasm takes some time to load, but it "feels" a lot faster, since it can do a lot on the server already before the hydration happens on the client side.

I tried both above mentioned solutions and I prefer "just leptos" a lot.
Btw you can do PUT and DELETE with htmx too, just use POST endpoints for that purpose. Basically, POST for everything that does any modification in the backend or should not be cached by a CDN or something, GET otherwise.

**Comment by gbj** [comment]
See #1159 for additional discussion. 

If you want to integrate HTMX and use other HTTP verbs it's perfectly possible to do that by creating PUT, DELETE, etc routes in Actix/Axum and using HTMX to make requests to them. 

I will not include this in Leptos itself unless the HTML spec itself one day expands to include forms or other HTML elements that make requests with verbs other than GET or POST. 

From my perspective this is quite simple: graceful degradation. As far as I can tell the HTMX approach here simply fails, silently, if HTMX's JS has not loaded for any reason (JS is off, device doesn't support it, you are on a subway and lost connectivity between receiving HTML and receiving JS, etc.)

I just don't see the reason to make it easier for people to ship fragile apps, in exchange for more of a maintenance burden and additional runtime complexity/binary size. Sounds like a lose-lose-lose to me.
