### ISSUE TITLE
Is "FileList" feature of web-sys in leptos_dom disabled on purpose?

### ISSUE THREAD

**Issue by legas7** [leptos-rs/leptos#1511]
Hello,

Having [FileList](https://docs.rs/web-sys/latest/web_sys/struct.FileList.html) (and File) in `web-sys` enabled would allow for using the `.files()` API on `NodeRef<Input>`, which can be useful with multifile pickers.

Cheers,
K.

**Comment by gbj** [comment]
To enable additional `web-sys` features you should add a `web-sys` dependency in your own project with the appropriate feature enabled. It's not that it's disabled on purpose in `leptos_dom`, it's that `leptos_dom` only enables the features it needs internally so that users don't pay the cost of every single `web-sys` feature if they don't need them.
