### ISSUE TITLE
Example with established UI component library

### ISSUE THREAD

**Issue by gitmalong** [leptos-rs/leptos#1534]
**Is your feature request related to a problem? Please describe.**
As someone who wants to bootstrap a new and modern looking website quickly without reinventing the wheel and with avoiding work that has not to be done in the pure JS world, I would love to see an example that integrates a popular UI component library such as https://mantine.dev/, Bootstrap etc.

**Comment by gbj** [comment]
Mantine is a React component library, i.e., a component library you can use with the React framework. Leptos is not React, so you can't use Mantine with Leptos.

Bootstrap is primarily a matter of importing some CSS and using its classes. I'm not sure why this would need an example.

We have Tailwind examples specifically because Tailwind requires some additional setup for its build tools.

Feel free to make a PR contributing any example that you'd like, but most component libraries are either 1) framework specific (so not suitable for use with a different framework) or 2) CSS or web-component-based (so trivial to integrate with a new framework), so not really sure what you're looking for here.

**Comment by gitmalong** [comment]
I found that https://github.com/leptos-rs/leptos/tree/main/examples/tailwind_csr_trunk with Daisy gave me a good starting point. I think what I was initially looking for was like a full blown website template.

**Comment by gbj** [comment]
You might enjoy looking at some of the website/blog examples in [`awesome-leptos`](https://github.com/leptos-rs/awesome-leptos/). I think I'll close the issue as I don't plan on adding a full-blown website template to the examples at this time.
