### ISSUE TITLE
Conditionally rendering a Router's `<Routes>` with `if`, `<Show>`, `<Suspense>` or other causes components to render twice in 0.5.0-beta

### ISSUE THREAD

**Issue by kik4444** [leptos-rs/leptos#1552]
**Describe the bug**
See title. The same does not happen on version 0.4.8. This bug happens on version 0.5.0-alpha, alpha2 and beta.

**Leptos Dependencies**

```toml
leptos = { version = "0.5.0-beta", features = ["csr", "nightly"] }
leptos_router = { version = "0.5.0-beta", features = ["csr", "nightly"] }
```

**To Reproduce**
Try this minimal reproduction
```rust
use leptos::*;
use leptos_router::*;

fn main() {
    console_log::init_with_level(log::Level::Debug).expect("setup logging");
    console_error_panic_hook::set_once();

    mount_to_body(App)
}

#[component]
fn App() -> impl IntoView {
    provide_context(create_rw_signal(0_usize));

    view! {
      <a href="/settings">"Settings"</a>
      <br/>
      <a href="/other">"Other"</a>
      <br/>
      <Router>

        // Imagine we're waiting for an async task to complete instead of 1 < 2
        <Show when=|| 1 < 2 fallback=|| view! { <p>"Loading"</p> }>
          <Routes>
            <Route path="/settings" view=Settings/>
            <Route path="/other" view=Other/>
          </Routes>
        </Show>

      </Router>
    }
}

#[component]
fn Settings() -> impl IntoView {
    log::debug!("settings");
    let counter = expect_context::<RwSignal<usize>>();
    counter.update(|c| *c += 1);

    view! { <p>"Hi from settings " {counter}</p> }
}

#[component]
fn Other() -> impl IntoView {
    log::debug!("other");
    let counter = expect_context::<RwSignal<usize>>();
    counter.update(|c| *c += 1);

    view! { <p>"Hi from other " {counter}</p> }
}
```
When you start the web page and click on the `Settings` or `Other` hrefs, they log *twice* to the console and the counter is incremented *twice* instead of doing both things *once*. However if you visit each page for the first time, e.g. by manually writing the URL `127.0.0.1:1420/settings` or `127.0.0.1:1420/other` and pressing enter, they log only once and the counter shows `1` instead of `2`. If you remove `<Show>` and render the `<Routes>` directly this bug does not occur. Switching back to version 0.4.8 also fixes this issue.

**Expected behavior**
The components above should only render once when visiting their pages from the href

**Comment by gbj** [comment]
Not saying that this isn't a bug or that it shouldn't be fixed. However, personally I'd say conditional route definition like this is kind of an "off-label use" of `<Routes>`. (See also #1488 for another example of conditional route definition causing problems). This is not the intended way to use the router, and for a very good reason: conditional route *definition* like this, as opposed to conditional route display, will break SSR (I'm pretty sure) because the server generates a route list on startup, so any conditional route definition may not make it to the server (Actix or Axum) router.

Instead, the pattern I'd suggest would be conditional route *display*. You can do this in the example given pretty easily with one level of nested routing. In the example below, the routes are always *defined*, but the two child routes are only *shown* when the condition is true. Conveniently, context works through Outlets (see example), so if you're doing something like loading a resource you can provide it as a context inside the Suspense, and expect that it's there in the child routes.

```rust
#[component]
pub fn App() -> impl IntoView {
    provide_context(create_rw_signal(0_usize));

    view! {
      <a href="/settings">"Settings"</a>
      <br/>
      <a href="/other">"Other"</a>
      <br/>
      <Router>

        // Imagine we're waiting for an async task to complete instead of 1 < 2
          <Routes>
            <Route path="/" view=|| view! {
                <Show when=|| 1 < 2 fallback=|| view! { <p>"Loading"</p> }>
                    {
                        provide_context(String::from("blueberry"));
                        view! { <Outlet/>}
                    }
                </Show>
            }>
                <Route path="/settings" view=Settings/>
                <Route path="/other" view=Other/>
            </Route>
          </Routes>

      </Router>
    }
}

#[component]
fn Settings() -> impl IntoView {
    log!("settings");
    let counter = expect_context::<RwSignal<usize>>();
    let ctx = expect_context::<String>();
    counter.update(|c| *c += 1);

    view! { <p>"Hi from settings " {ctx} {counter}</p> }
}

#[component]
fn Other() -> impl IntoView {
    log!("other");
    let counter = expect_context::<RwSignal<usize>>();
    let ctx = expect_context::<String>();
    counter.update(|c| *c += 1);

    view! { <p>"Hi from other " {ctx} {counter}</p> }
}
```
