### ISSUE TITLE
Using axum::request::Multipart with leptos_axum::extract

### ISSUE THREAD

**Issue by Panaetius** [leptos-rs/leptos#1602]
I'd like to upload a file to axum via leptos.

From what I can see, `leptos_axum::extract` requires `https://docs.rs/axum/latest/axum/extract/trait.FromRequestParts.html` to be implemented for the closure. But that is not implemented for https://docs.rs/axum/latest/axum/extract/struct.Multipart.html only for `Query` and some others.

Is there a way to use Multipart with the extract function or could support for it be added?

**Comment by gbj** [comment]
The appropriate way to do this is just with a regular Axum route, not a server function. Extractors that parse the body aren't supported in server functions because the body is consumed when parsing the server function arguments. Additionally, server functions don't really make sense with form uploads conceptually: what would it mean to "call" this function? What would its arguments be?

I'm open to the idea of something like an `#[api]` macro for easier colocated API routes but a plain Axum route is the way to go for now.

**Comment by Panaetius** [comment]
Thank you for the fast reply!

I was going off of https://github.com/leptos-rs/leptos/issues/744 and assumed that using a server function for axum in the same vein would also make sense. 

I'll go with a plain route for now. Having it easily colocated with a macro would be a nice addition.
I'll close this issue.

Oh and thank you very much for the great framework and the helpful youtube videos, I really love it!
