### ISSUE TITLE
Support writing custom renderers to use leptos anywhere

### ISSUE THREAD

**Issue by luoxiaozero** [leptos-rs/leptos#1743]
**Is your feature request related to a problem? Please describe.**

Hi, Are there any plans to support custom renderers to support new platforms outside of the web.  Like https://github.com/solidjs/solid/releases/tag/v1.2.0

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gbj** [comment]
No, there are no plans. It's something that could be considered during a future rewrite of the renderer.

**Comment by luoxiaozero** [comment]
ok

**Comment by gbj** [comment]
This is planned as part of the work I'm doing to rewrite the renderer for 0.6. If you want to follow along with that work you can check it out at https://github.com/gbj/tachys — it uses a universal rendering model very similar to Solid's, and you can see I have implementations at the moment for the DOM, a mock DOM that can be used in plain Rust tests, and GTK (totally incomplete but as a proof of concept).

**Comment by luoxiaozero** [comment]
Great. I need to study it.

**Comment by gbj** [comment]
Done in 0.7.

**Comment by PaulWagener** [comment]
This is closed as completed, but it seems to be impossible in the current code because the `Renderer` trait is hardcoded to take `web_sys::Element` objects which cannot be constructed outside of the browser.

This seems to be on purpose as explained in https://github.com/leptos-rs/leptos/pull/3015

This issue should be re-opened until we no longer abandon the dream ;)

**Comment by maciek134** [comment]
Or maybe a new one opened with a list of things that would have to change / be researched to go this direction?

**Comment by gbj** [comment]
@PaulWagener @maciek134 In general discussion on old issues is unlikely to be seen.

Additional work on this is not something I'm going to have capacity for.

If someone else wanted to work on it, there are a few possible approaches:
1) Pass around some kind of `Arc<dyn Renderer>` or similar rather than the (previous) generic or the (current) `Rndr` type alias. This would allow multiple types of renderers to coexist, but would also incur a runtime overhead on every single UI operation and probably prevent some compiler operations.
2) Only allow one kind of renderer per binary, and do it via conditional compilation: replacing the `Rndr` type alias with a different one for each renderer.

I was excited/curious about doing this when it was possible to do it as a generic, but the compiler just can't handle that in reality. I'm less interested in going back and trying to replicate that work again. It's a huge amount of work to try to build up a reasonable ecosystem around another rendering toolkit (like GTK as opposed to the DOM) and I just don't have the capacity to do it, or to maintain it. 

I'd be very open to helping someone who's interested in building out their own framework using some of the tools provided in Leptos like the reactive system, etc. but targeting another renderer, and am happy to make things as modular as we can. But I don't plan to work further on alternate renderers myself in the future.
