### ISSUE TITLE
Book hasn't been updated for the new `<For>`

### ISSUE THREAD

**Issue by maccesch** [leptos-rs/leptos#1813]
**Describe the bug**
The book and the example still has the `view` prop

**Comment by gbj** [comment]
Thanks. I'm going to do a small fix for now, just so the example as given compiles. The `let:` syntax doesn't lend itself *super* well to that example. There's a separate question of updating all the CodeSandboxes to 0.5, which is hard because CodeSandbox is so resource-constrained that updating to a new version, new nightly Rust, etc. for each sandbox example has proved challenging!

**Comment by maccesch** [comment]
I see. Yew has a Dockerfile for their code sandbox. Maybe sth like that would be better?
https://github.com/yewstack/yew-playground
