### ISSUE TITLE
MultiPart Server Functions

### ISSUE THREAD

**Issue by benwis** [leptos-rs/leptos#1868]
Basically I think it'd be great to have a Sever Function encoding called `MultiPartJson` and `MutltiPartCbor` with the goal of making multipart form submissions to server functions easier.

I think we could create a `MultipartActionForm` component to serialize form data and any uploaded files into a FormData object. That could be sent to the server function route, and arguments to that server fn could be deconstructed from that FormData object with crates like [axum_typed_multipart](https://github.com/murar8/axum_typed_multipart)

My primary motivator is to make the processing of file uploads super easy, while keeping the Server Fn infrastructure

**Comment by gbj** [comment]
Yes some kind of helper makes sense to me. I haven't worked with multipart forms much before, so I'm very open to API suggestions. Do you want to do some work on this one?

**Comment by benwis** [comment]
> Yes some kind of helper makes sense to me. I haven't worked with multipart forms much before, so I'm very open to API suggestions. Do you want to do some work on this one?

Sure, I think I see a way to build it. I'll reach out if I have any questions

**Comment by benwis** [comment]
So I've dug into this a bit, and see a few options

1. No change to server functions, just create one that takes nothing, and parse the Request or run an extractor on the Request to get the form data. Not sure how this would work with streaming files. You wouldn't be able to rerun this, but perhaps we could create an Action or some other tool to construct Requests to Leptos
2. Create a serde_multipart crate/implement Serialize/Deserialize for one of the existing MultiPart Form representations. Not sure how well serde handles streaming formats, 
3. Have Axum/Actix handle this, and create a helper/parser/custom handler to have them handle it and parse the data. This seems a bit silly

**Comment by gbj** [comment]
Related thought: While we're at it, it would be worth making parts of the server fn implementation generic rather than using an enum for Payload and so on. IIRC the encodings both for sending the request and decoding the response are stored in an enum which means they both need to be present at runtime. There could be WASM binary savings if we make it generic over the encoding (which shouldn't change at runtime anyway) instead. Especially if we're adding another encoding.

**Comment by benwis** [comment]
Actually this is something that I've been thinking about, if we could open up some of the bounds on Server Functions, we could provide a lot more options for encoding.

What if we moved away from a bound on Serialize/Deserialize, and instead created our own traits like IntoRequest/FromResponse? We could implement those for different encodings and for T: Serialize/Deserialize, and it would make some things like Multipart a LOT easier to write.

**Comment by dvc94ch** [comment]
trying to get file uploads working. it seems like there is an extractor `Multipart` in `axum`, but it only implements `FromRequest` instead of `FromRequestParts` because it consumes the request body, so the `leptos_axum` crate can't extract the `Multipart`. any ideas or examples of how to get file uploads working?

**Comment by benwis** [comment]
Yes, currently your best approach is to use a regular axum handler to handle multipart uploads

**Comment by gbj** [comment]
For anyone who's curious, our rewrite of server functions (https://github.com/gbj/server_fns) does, in fact, now support multipart uploads (and streaming responses), so this should be included in the next release.

**Comment by gbj** [comment]
Done in #2158.
