### ISSUE TITLE
`rel` attribute for anchor component

### ISSUE THREAD

**Issue by koopa1338** [leptos-rs/leptos#1927]
### Is your feature request related to a problem? Please describe.

I wanted to add an anchor element with `rel="prefetch"` but if I understood the `A` component correctly, there is currently no property for setting `rel`.

### Describe the solution you'd like

My suggestions would be to add an enum with variants that are [valid](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel) for an anchor tag `rel` attribute, and add an optional property to the anchor component. 

### Describe alternatives you've considered
In those cases, I can't use the anchor component and have to fallback to HTML anchor tag in view macro and set up the element myself.

Edit: would love to contribute and create a pr for this :wink:

**Comment by luoxiaozero** [comment]
Maybe we can complete all the other attributes of the [a tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a), like download, hreflang, ping, referrerpolicy, rel, type.

**Comment by gbj** [comment]
The appropriate way to add `rel` or other attributes would be to add a `#[prop(optional)] attributes: Vec<(&'static str, Attribute)>` and spread those onto the `<a>`, because otherwise there's a cost to every attribute added.

Remember also that the `<A>` component exists **only** for
1) marking which link is currently active, and
2) relative nested routing

In every other case, the `<a>` element is perfectly appropriate and behaves identically.
