### ISSUE TITLE
Derived signals can't be converted Into() Callbacks

### ISSUE THREAD

**Issue by pscott31** [leptos-rs/leptos#2041]
**Describe the bug**
I have a component that takes a callback prop using e.g. `#[prop(into)] on_click: Callback<()>`

When I pass in a closure that makes use of standard signal types, like `ReadSignal`, it works - however if my closure access a Derived signal (or indeed a signal made by create_slice), it complains with 

```
 within `{closure@src/app.rs:106:42: 106:50}`, the trait `callback::NotRawCallback` is not implemented for `(dyn std::ops::Fn() -> i32 + 'static)`
```

**Leptos Dependencies**

```toml
 leptos = { version = "0.5.2", features = ["csr", "nightly"] }
```

**To Reproduce**

Here's a little snippet that reproduces the problem

```
use leptos::logging::*;
use leptos::*;

fn main() {
    // This is fine
    let (signal, _) = create_signal::<i32>(1);
    let callback1 = Callback::<()>::from(move |_| log!("{}", signal()));

    // But this doesn't work:
    //  trait bound `(dyn std::ops::Fn() -> i32 + 'static): callback::NotRawCallback` is not satisfied
    let derived = Signal::derive(move || signal() + 1);
    let callback2 = Callback::<()>::from(move |_| log!("{}", derived()));
}
```

**Expected behavior**

The program above to compile! And hopefully if that compiles, my actual program will compile 

**Additional context**
I don't quite understand what the NotRawCallback trait is trying prevent me from doing; presumably it's to prevent me shooting myself in the foot and maybe what I'm trying to do I shouldn't be doing for some reason. I had a look at the code and it seems like the point of NotRawCallback is to prevent wrapping a Callback in another Callback but I might be mistaken.

It might also well be this is a bug in rust's negative trait implementation as it's not stable yet :)

**Comment by gbj** [comment]
> I don't quite understand what the NotRawCallback trait is trying prevent me from doing; presumably it's to prevent me shooting myself in the foot and maybe what I'm trying to do I shouldn't be doing for some reason. I had a look at the code and it seems like the point of NotRawCallback is to prevent wrapping a Callback in another Callback but I might be mistaken.

It allows implement `From<Fn(In) -> Out>` for `Callback<In, Out>` while also implementing `Fn(In) -> Out` for `Callback<In, Out>`, which would otherwise conflict with the global `From<T> for T` implementation. In other word, it isn't there to allow you to do anything or prevent you from doing anything.

Unfortunately this relies on the `auto_traits` and `negative_impls` unstable features of Rust in a way that, as far as I can tell, is broken in this specific instance. Any type that is not a `Callback<_, _>` should implement `NotRawCallback` (that's the auto trait part), and `Callback<_, _>` implements `!NotRawCallback` (that's the negative impls part). I'm pretty sure this is a rustc bug in these unstable features.

**Comment by bicarlsen** [comment]
Is there a canonical workaround for this?

**Comment by gbj** [comment]
@bicarlsen For this particular example (and similar examples), using `Callback::new()` instead of `Callback::from()` is fine. It's just the `From` implementation that is broken.
