### ISSUE TITLE
Deserialization error with multiple Suspense

### ISSUE THREAD

**Issue by winteler** [leptos-rs/leptos#2063]
Hi!

I think I found a bug that occurs when loading resources with different types through different paths (for instance one in a drawer that is always visible and one in the main window). It looks like Leptos mixes up the expected return types of the resources. Here is the error in question:

```panicked at /home/winteler/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.5.2/src/resource.rs:430:17:
could not deserialize Resource<core::result::Result<(), server_fn::error::ServerFnError>> JSON for ResourceId(2v1): Deserialize(Error("invalid type: string \"Test\", expected unit", line: 1, column: 12))
```

**Leptos Dependencies**

```toml
leptos = { version = "0.5.2", features = ["nightly"] }
leptos_axum = { version = "0.5.2", optional = true }
leptos_meta = { version = "0.5.2", features = ["nightly"] }
leptos_router = { version = "0.5.2", features = ["nightly"] }
```

**To Reproduce**

Here is an example to reproduce the issue:

```
use leptos::*;
use leptos_router::*;

#[server]
pub async fn get_user() -> Result<(), ServerFnError> {
    Ok(())
}

#[server]
pub async fn data() -> Result<(), ServerFnError> {
    Ok(())
}

#[server]
pub async fn other_data() -> Result<String, ServerFnError> { Ok(String::from("Test")) }

#[component]
pub fn App() -> impl IntoView {
    view! {
        <Router>
            <div>
                <main>
                    <div>
                        <Routes>
                            <Route path="" view=LoginGuard>
                                <Route path="" view=Child/>
                            </Route>
                        </Routes>
                    </div>
                    <div>
                        <Drawer/>
                    </div>
                    <div>
                        <div>
                            <button on:click=move |_| leptos::logging::log!("Did I hydrate?")>"Click"</button>
                        </div>
                    </div>
                </main>
            </div>
        </Router>
    }
}

#[component]
pub fn Drawer() -> impl IntoView {
    let other_nested_data = Resource::once(other_data);

    view! {
        <label>"Label"</label>
        <Suspense>
            <pre>{
                move || {
                    format!("{:?}", other_nested_data.get())
                }
            }</pre>
        </Suspense>
    }
}

#[component]
fn LoginGuard() -> impl IntoView {
    let guard_data = Resource::once(get_user);
    view! {
        <Suspense>
            {move || guard_data.and_then(|_| view! { <Outlet/> })}
        </Suspense>
    }
}

#[component]
pub fn Child() -> impl IntoView {
    let nested_data = Resource::once(data);
    view! {
        <Suspense>
            <pre>{
                move || {
                    format!("{:?}", nested_data.get())
                }
            }</pre>
        </Suspense>
    }
}```

Thanks a lot for your work on this great framework! :)

**Comment by gbj** [comment]
Thanks very much! I've been looking for a good reproduction of this particular issue for a couple months. I imagine it has been really annoying to debug, so apologies for that — hopefully this nice minimal reproduction will help me figure it out. Much appreciated.

**Comment by winteler** [comment]
I'm glad it helps then! ;) I quickly saw the resources' output were getting and I already had a minimal example similar to my application (that you made and showed me in another bug report actually '^^) so it was very simple to modify it a little bit and reproduce the issue. Thanks again for your help!

**Comment by gbj** [comment]
Ok so in this instance, it's relatively easy to fix the example, by changing this
```rust
move || guard_data.and_then(|_| view! { <Outlet/> })
```
to use `.with()` instead of `.and_then()`
```rust
move || guard_data.with(|_| view! { <Outlet/> })
```

The reason for this is that `.map` and `.and_then` on resources only run once the resource is resolved, but `.with` runs and takes an `Option` of the resource's current value. This means that the resources are actually created in a different order on the server and in the client, hence the mismatch in expected types.

On the server, you don't render `Child` until `guard_data` is loaded, so the resources are created in the order
1. `guard_data`
2. `other_nested_data`
3. (once guard data resolves) `nested_data`

On the client, by the time the page hydrates all resources have streamed in so the resources are created in the order
1. `guard_data`
2. `nested_data`
3. `other_nested_data`

Resources are assigned flat IDs, not scoped to anything else, which is why the types don't match: IDs 2 and 3 are reversed on client and server.

**Comment by winteler** [comment]
Thanks for the update :) 

After playing a bit with my application, I found this way to make it work using `.with`:

```
resource.with(|result| match result {
    Some(Ok(_)) => {
        view! { <Outlet/> }.into_view()
    },
    Some(Err(e)) => {
        log::info!("Error: {}", e);
    },
    None => {
        view! { <Outlet/> }.into_view()
    },
})
```

That way other resources in the `<Outlet/>` are still created before it finishes loading. Does this seem good to you or would you have another suggestion?

In my case, it was also possible to dodge the error by moving some parts of the html (a DaisyUI drawer) before the `<Routes>`  but using `.with` seems much safer.

**Comment by gbj** [comment]
> After playing a bit with my application, I found this way to make it work using `.with`

This is great to hear!

> That way other resources in the `<Outlet/>` are still created before it finishes loading. Does this seem good to you or would you have another suggestion?

This is totally ideal. The great thing about it is that it means that you remove a layer of waterfalls: if what's rendered in the `<Outlet/>` loads some data that doesn't depend on the guard, you begin loading that in parallel with the guard, rather than only after the guard is done.

Let's keep the issue open, because it's still a bug, but I'm glad you were able to refactor to avoid it.

**Comment by gbj** [comment]
Work as expected on 0.7

**Comment by winteler** [comment]
Great! Thanks for the work and I look forward to 0.7 :)
