### ISSUE TITLE
Islands not working with workspace

### ISSUE THREAD

**Issue by pintoflager** [leptos-rs/leptos#2083]
I'm following [islands](https://leptos-rs.github.io/leptos/islands.html) guide and it works perfectly when applied against [axum starter](https://github.com/leptos-rs/start-axum) but when I try to do the same against this workspace setup it produces following error on browser console:
```
Uncaught (in promise) TypeError: mod[("_island_" + l)] is not a function
```

Btw this workspaces example is waaaaay easier to understand than the all-in-one solution. Thanks

**Comment by benwis** [comment]
> To be honest I'm a bit confused where to report this kind of an issue. Filing it here here was my best guess.
> 
> Also thought of putting it on [cargo leptos](https://github.com/leptos-rs/cargo-leptos) which is the tool that builds and runs the contents of this repository.
> 
> I don't think [leptos](https://github.com/leptos-rs/leptos) itself can hold the issue here, workspace just enables code spitting for more complex projects and within the crate feature checking is done against 'itself' with
> 
> ```
> #[cfg(feature = "experimental-islands")]
> ```
> 
> I'm not aware of any rust feature checking against workspace Cargo.toml. My point being that if leptos works without workspace setup it should work with it as well.
> 
> I suspect it's the build tool that's ignoring the "experimental-islands" feature flag for some stage of frontend build.
> 
> BTW it's the feature flag on `leptos_axum = { version = "0.5", features = ["experimental-islands"]}` that produces the JS console error. Remove "experimental-islands" from that dependency and error goes away. Obviously nothing works but just to demonstrate that leptos itself is working fine, rendering `<leptos-island>` component, respecting the feature flag option.

I have experimental_islands working in a workspace. Out of curiosity, are you setting `resolver = "2" ` in you workspace Cargo.toml?

**Comment by NiklasEi** [comment]
I had this issue in a workspace, too. Greg helped me on Discord and found out that `frontend` needs to import the app.

This is my diff from the official example: https://github.com/NiklasEi/start-axum-workspace-islands-ssg/compare/main%5E%5E%5E...main

**Comment by gbj** [comment]
I think this can probably be closed. I had not realized, but the answer is:
- the frontend/lib crate being compiled to WASM needs to have the `app` crate as a dependency
- apparently it needs to `use app;`, if you're in a workspace and there's no use of the app crate otherwise. There seems to be some interaction between wasm-bindgen and cargo here — the islands all get added to the JS module generated as public functions, and if the module is a dependency but totally unused, the glue code doesn't get generated there.

**Comment by feathecutie** [comment]
> I think this can probably be closed. I had not realized, but the answer is:
> 
>     * the frontend/lib crate being compiled to WASM needs to have the `app` crate as a dependency
> 
>     * apparently it needs to `use app;`, if you're in a workspace and there's no use of the app crate otherwise. There seems to be some interaction between wasm-bindgen and cargo here — the islands all get added to the JS module generated as public functions, and if the module is a dependency but totally unused, the glue code doesn't get generated there.

It would be really nice if this could be documented somewhere. I ran into this issue as well, and I didn't realize it was because I removed the `use app::*;` from `frontend` until I finally found this issue.

I assume that more people will run into this, as `rust-analyzer` and `cargo check` both tell you that this use statement is completely unnecessary, and even just applying the automatic fix using `cargo check --fix` or something similar simply removes that use statement.

The only "fix" I found for this is to put an allow statement over the import like so:
```rust
#[allow(unused_imports)]
use app;
```

I might also try to open a PR for the book myself.

**Comment by benwis** [comment]
> > I think this can probably be closed. I had not realized, but the answer is:
> > ```
> > * the frontend/lib crate being compiled to WASM needs to have the `app` crate as a dependency
> > 
> > * apparently it needs to `use app;`, if you're in a workspace and there's no use of the app crate otherwise. There seems to be some interaction between wasm-bindgen and cargo here — the islands all get added to the JS module generated as public functions, and if the module is a dependency but totally unused, the glue code doesn't get generated there.
> > ```
> 
> It would be really nice if this could be documented somewhere. I ran into this issue as well, and I didn't realize it was because I removed the `use app::*;` from `frontend` until I finally found this issue.
> 
> I assume that more people will run into this, as `rust-analyzer` and `cargo check` both tell you that this use statement is completely unnecessary, and even just applying the automatic fix using `cargo check --fix` or something similar simply removes that use statement.
> 
> The only "fix" I found for this is to put an allow statement over the import like so:
> 
> ```rust
> #[allow(unused_imports)]
> use app;
> ```
> 
> I might also try to open a PR for the book myself.

That sounds like a great idea. Once we decide islands is not experimental(and it basically isn't now) we should make a couple starters as well

**Comment by gbj** [comment]
I've added a note about this to the Islands section of the book.
