### ISSUE TITLE
click() function of NodeRef<Button> leads to Uncaught Error: closure invoked recursively or after

### ISSUE THREAD

**Issue by ShubhranshuSanjeev** [leptos-rs/leptos#2104]
**Describe the bug**
For instance, in this component if we click `Btn1` what I assume should happen is `Btn2` should too receive a click event and `on:click` handler should be executed.

But this is leading to following error:
`Uncaught Error: closure invoked recursively or after being dropped`

```
#[component]
fn MyComponent() -> impl IntoView {
    let button_ref = create_node_ref::<html::Button>();

    view! {
        <div>
            <button
                node_ref=button_ref
                on:click=move |e: MouseEvent| {
                    e.prevent_default();
                    logging::log!("Btn 2 clicked");
                }
            >
                "Btn 2"
            </button>
            <button
                on:click=move |e: MouseEvent| {
                    e.prevent_default();
                    match button_ref.get() {
                        Some(b_ref) => { b_ref.click(); },
                        None => logging::log!("button ref not set"),
                    };
                }
            >
                "Btn 1"
            </button>
        </div>
    }
}
```

**Leptos Dependencies**
```
leptos = { version = "0.5.2" }
leptos_meta = { version = "0.5.2" }
leptos_actix = { version = "0.5.2", optional = true }
leptos_router = { version = "0.5.2" }
wasm-bindgen = "=0.2.89"
web-sys = "0.3.64"
js-sys = "0.3.65"
```

**To Reproduce**
1. Click button with text `Btn1`
2. See error

**Expected behavior**
If we click `Btn1` what I assume should happen is `Btn2` should too receive a click event and `on:click` handler should be executed

**Screenshots**
NA

**Additional context**
NA

**Comment by gbj** [comment]
Thanks. For posterity, or if anyone else encounters something similar, the issue here is that causing an event from inside a handler for the same event on a different element causes issues with our event delegation system. Specifically, all bubbling events are delegated by default to the `window`. But `wasm-bindgen` closures can't be invoked recursively. So when the `click` handler on one button fires a `click` on another button, that apparently constitutes the `click` listener on `window` recursively calling itself. At least I think that's what's happening.

The answer is just to make one or both of them `on:click:undelegated` (whether it needs to be one or both may depend on specific example) Event delegation and opting out with `:undelegated` need to be better documented but that's known and on the list to add to the book.

Beyond that, I think this is probably a can't/won't-fix, now that I understand it.
