### ISSUE TITLE
Upgrade to Axum 0.7

### ISSUE THREAD

**Issue by glennpierce** [leptos-rs/leptos#2111]
Are there any plans to upgrade to Axum 0.7 soon as it increases usability a lot. 
Or is it possble to use Axum 0.7 in combination with leptus-axum ?

Thanks

**Comment by gbj** [comment]
Have you read the discussion in the PR to do that? https://github.com/leptos-rs/leptos/pull/2082

You might consider, for now, just using the branch in that PR along with Axum. The issue is that the changes from 0.6 to 0.7 are pervasive enough that they would require a version bump for `leptos_axum` from `0.5.x` to `0.6`, which would then forever be out of sync with the rest of the Leptos libraries, or to bump everything to `0.6.0`, which creates a bunch of churn in the rest of the ecosystem that doesn't need to happen.

**Comment by glennpierce** [comment]
Thanks that makes sense. I will use that branch.
