### ISSUE TITLE
Trying to use (unsupported) equality constraint in component makes leptos ignore the component and its errors and report success

### ISSUE THREAD

**Issue by pheki** [leptos-rs/leptos#2133]
Hi, thanks a lot for creating/maintaining this leptos and happy holidays!

**Describe the bug**
Trying to use (unsupported) equality constraint makes leptos ignore the component and its errors and report compilation success

**Leptos Dependencies**

For example:
```toml
leptos = "0.5.4"
```

**To Reproduce**
Minimum reproducible example:

```rust
use leptos::*;

pub fn main() {
    mount_to_body(|| view! {
        // <BugExample />
    })
}

#[component]
pub fn BugExample<T>() -> impl IntoView
where
    T = String,
{
    is_let_even_required? = [1, 2];
    rust_looks_like_python_nowadays.get(3, default="abc");
    std::fs::File
}
```

1. Run `cargo check --target wasm32-unknown-unknown`
```console
$ cargo check --target wasm32-unknown-unknown
    Checking leptos-no-error v0.1.0 (/home/bilko/git/leptos-no-error)
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
$ echo $?
0
```

2. Run `cargo expand`
```console
$ cargo expand
    Checking leptos-no-error v0.1.0 (/home/bilko/git/leptos-no-error)
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s

#![feature(prelude_import)]
#[prelude_import]
use std::prelude::rust_2021::*;
#[macro_use]
extern crate std;
use leptos::*;
pub fn main() {
    mount_to_body(|| { leptos::leptos_dom::Unit })
}
```

3. Uncomment `// <BugExample />` and run again
```console
$ cargo check --target wasm32-unknown-unknown
    Checking leptos-no-error v0.1.0 (/home/bilko/git/leptos-no-error)
error[E0425]: cannot find value `BugExample` in this scope
 --> src/main.rs:5:10
  |
5 |         <BugExample />
  |          ^^^^^^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
error: could not compile `leptos-no-error` (bin "leptos-no-error") due to previous error
```

4. Remove or comment out `#[component]` and see all errors:
```console
$ cargo check --target wasm32-unknown-unknown
    Checking leptos-no-error v0.1.0 (/home/bilko/git/leptos-no-error)
error: equality constraints are not yet supported in `where` clauses
  --> src/main.rs:12:5
   |
12 |     T = String,
   |     ^^^^^^^^^^ not supported
   |
   = note: see issue #20041 <https://github.com/rust-lang/rust/issues/20041> for more information

error[E0425]: cannot find value `is_let_even_required` in this scope
  --> src/main.rs:14:5
   |
14 |     is_let_even_required? = [1, 2];
   |     ^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `rust_looks_like_python_nowadays` in this scope
  --> src/main.rs:15:5
   |
15 |     rust_looks_like_python_nowadays.get(3, default="abc");
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `default` in this scope
  --> src/main.rs:15:44
   |
15 |     rust_looks_like_python_nowadays.get(3, default="abc");
   |                                            ^^^^^^^
   |
help: you might have meant to introduce a new binding
   |
15 |     rust_looks_like_python_nowadays.get(3, let default="abc");
   |                                            +++

error[E0423]: expected value, found struct `std::fs::File`
   --> src/main.rs:16:5
    |
16  |     std::fs::File
    |     ^^^^^^^^^^^^^ help: use struct literal syntax instead: `std::fs::File { inner: val }`
    |
   ::: /home/bilko/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/fs.rs:100:1
    |
100 | pub struct File {
    | --------------- `std::fs::File` defined here

error[E0070]: invalid left-hand side of assignment
  --> src/main.rs:14:27
   |
14 |     is_let_even_required? = [1, 2];
   |     --------------------- ^
   |     |
   |     cannot assign to this expression

Some errors have detailed explanations: E0070, E0423, E0425.
For more information about an error, try `rustc --explain E0070`.
error: could not compile `leptos-no-error` (bin "leptos-no-error") due to 6 previous errors
```

5. Uncomment `#[component]`, comment the full where constraint and see all errors again (errors ommited, but same as above).

**Expected behavior**
On step 1. and 3., all errors should be reported. On step 1., compilation should not be successful.

**Additional context**
Although this does not happen for valid programs, it can be confusing when developing as you need to comment `#[component]` out to be able to debug it.

**Comment by gbj** [comment]
It's pretty important to decent rust-analyzer support that we continue emitting semi-broken versions of code that contain syntax errors. However, doing this correctly requires parsing at least a valid function signature in order to emit code a correctly-named body.

Your example is only broken when the function signature is not valid, i.e., can't be parsed by `syn` as a function signature.

An example with a valid signature correctly emits errors for all the other issues in the function body:
```rust
#[component]
pub fn BugExample<T>() -> impl IntoView {
    is_let_even_required? = [1, 2];
    rust_looks_like_python_nowadays.get(3, default = "abc");
    std::fs::File
}
```

For me, rust-analyzer points correctly to the place the syntax error occurs, although its error message is not super helpful 
<img width="306" alt="Screenshot 2023-12-24 at 6 58 38 PM" src="https://github.com/leptos-rs/leptos/assets/286622/f0eb7ab9-ff07-41c3-bb2b-8655babbc528">
<img width="603" alt="Screenshot 2023-12-24 at 6 58 46 PM" src="https://github.com/leptos-rs/leptos/assets/286622/ca67f873-d3a8-475c-a5e8-82027136d03f">

It may be possible to pass through the error messages more accurately. It seems the macro is emitting *nothing* when the function signature is invalid syntax like this, rather than omitting the original, broken code. (Which is why your `cargo check` works when the component is unused: the macro is emitting no code, rather than the broken code.) So that part should probably be fixed.

**Comment by pheki** [comment]
TYSM!
