### ISSUE TITLE
Have signals/StoredValues update/update_value functions return the callbacks return value

### ISSUE THREAD

**Issue by luxalpa** [leptos-rs/leptos#2149]
**Is your feature request related to a problem? Please describe.**
I want to use `update_value` in order to replace a value inside an `Option`:

```rs
let stored = store_value(None::<f64>);

// inside some effect:
if let Some(v) = stored.update_value(|v| v.take()) {
  // do something with v
}
```
currently I can do that with a full nest:
```rs
stored.update_value(|v| {
  if let Some(v) = v.take() {
    // do something with v
  }
});
```
or using `try_update_value`:
```rs
if let Some(v) = stored.try_update_value(|v| v.take()).unwrap() {
  // do something with v
}
```

**Describe the solution you'd like**
I think it would be intuitive if the update functions acted like their try and with counterparts and also returned the (optional) value from the callback.

**Describe alternatives you've considered**
- The nesting solution above sometimes can cause borrow issues, that's why it's preferrable to keep the callback as small as possible.
- The try solution expresses that the operation is fallible, but in my case it isn't.

**Additional context**
This applies at least to `StoredValue` struct and the `SignalUpdate` trait, the latter of which also would make this a breaking change.

**Comment by gbj** [comment]
Note also that I've resisted this for `.update()` on signals, because of the fact that event handlers require a function that returns `()`. Returning something from `.update()` means that `on:click=move |_| count.update(|n| *n += 1)` would need to be rewritten across the board to `on:click=move |_| { count.update(|n| *n += 1); }`, which is worse IMO.

We previously had an `.update_returning()`, which was deprecated and merged into `.try_update()`

I would actually suggest that 
```rust
// note the change to .flatten()
if let Some(v) = stored.try_update_value(|v| v.take()).flatten() {
  // do something with v
}
```
is the best solution here, as it won't panic.

**Comment by luxalpa** [comment]
> Returning something from `.update()` means that `on:click=move |_| count.update(|n| *n += 1)` would need to be rewritten across the board to `on:click=move |_| { count.update(|n| *n += 1); }`, which is worse IMO.

I don't think this is true. In my little test:

```rs
fn my_update<O>(f: impl FnOnce(&mut i32) -> O) -> O {
    todo!()
}

let _ = view! {
        <div on:click=move |_| my_update(move |v| *v += 1) />
    };
```

compiled with no problems. I think `fn() -> ()` and `fn()` are identical.

**Comment by gbj** [comment]
Sorry, I'm talking about the version that returns an Option. .update() currently does not panic if you update a signal that has been disposed. .update_value() does and that should probably be changed. I will not change .update() on signals to panic if disposed and return a value.

**Comment by luxalpa** [comment]
Since it seems the idiomatic use case would be to always use `try_update` in every scenario, what is the use case for `update` then? And why doesn't the same apply to `with` which does return the inner value? I think that's rather inconsistent and definitely counter intuitive.

**Comment by gbj** [comment]
> And why doesn't the same apply to `with` which does return the inner value?

The goal of the design decisions here is minimize panicking while making the most-common case the default one. `.with()` *must* return a value, or it's meaningless, so it defaults to panicking if disposed, and you can opt into `.try_with()` if that might be the case. `.update()` does *not* need to return a value in the overwhelming majority of cases, so it defaults to *not* panicking, and you can opt into `.try_update()` if you want the return value. 

Unless I'm mistaken you're suggesting changing the behavior of `.update()` so that it is essentially `.try_update().unwrap()`, right? This will increase the likelihood of panicking, which is bad because panics are unrecoverable in WASM.

> Since it seems the idiomatic use case would be to always use `try_update` in every scenario, what is the use case for `update` then?

I don't understand what you mean here, sorry.

**Comment by luxalpa** [comment]
ok, I think I understand the issue with this. Somehow I was under the impression that the callback was called every time, but ofc it makes sense that it's not being called when the signal is disposed.
