### ISSUE TITLE
Err(Deserialization("missing field `excluded_tags`"))

### ISSUE THREAD

**Issue by Vai3soh** [leptos-rs/leptos#2181]
Hello.

```
#[server(GetChildsWithFilter, "/api")]
pub async fn get_childs_with_filters(
  included_tags: Vec<String>,
  excluded_tags: Vec<String>,
) 
```
If we have an empty array (excluded_tags). At the query generation stage, the query itself does not include the excluded_tags field. Why? 
Is there any way to change this? 

p.s.
I just added it to the logic and the requests started coming through.
```
  if excluded_tags.is_empty() {
    excluded_tags.push("test_name".into())
  }
```

**Comment by gbj** [comment]
We use [`serde_qs`](https://github.com/samscott89/serde_qs) for serializing/deserializing URL-encoded data like this. It seems like this may be a case where its encoding isn't reversible? i.e., where encoding X to a string and then decoding X from the string doesn't give you an equivalent object.

You didn't provide context on how you're using the server function. If it's used in an ActionForm, then you might need to open an issue upstream or use a workaround to make sure there's always at least one element. If you're just using it as a server function otherwise, considering using the CBOR encoding to work around this.

**Comment by Vai3soh** [comment]
Thanks. Use "cbor" worked. Or use Option, and pass None if array is empty.

**Comment by gbj** [comment]
Closing this as an upstream issue with `serde_qs`.

**Comment by gbj** [comment]
Hey @Vai3soh When preparing the new release, I realized that we had actually already fixed this issue but not documented it properly: The correct solution here is to use
```rust
#[server(GetChildsWithFilter, "/api")]
pub async fn get_childs_with_filters(
  #[server(default)]
  included_tags: Vec<String>,
  #[server(default)]
  excluded_tags: Vec<String>,
) 
```
The `#[server(default)]` annotation should pass through a `#[serde(default)]` to those fields in the struct encoding/decoding, which is required by some crates like the URL encoding one.
