### ISSUE TITLE
Uncaught (in promise) CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0 await (async)		 (anonymous)	@	mngpost:24

### ISSUE THREAD

**Issue by jsoneaday** [leptos-rs/leptos#2224]
**Describe the bug**
Note does not happen consistently. I have these routes listed. ```
<Routes>
                    <Route path="/" view=Home />
                    <Route path="/admin" view=Admin>
                        <Route path="/mail" view=Mail />
                        <Route path="/addpost" view=AddPost />
                        <Route path="/mngpost" view=ManagePosts />
                        <Route path="" view=PageNotFound />
                    </Route>                    
                </Routes>```
If I load /admin/mail route and then load /admin/mngpost route and then manually type a new route on the url, load that route, and then hit the back button (to go back to the /admin/mngpost page) I get the error shown. 

**Leptos Dependencies**
console_error_panic_hook = "0.1.7"
leptos = { version = "0.5.4", features = ["csr", "nightly"] }
leptos_meta = { version = "0.5.4", features = ["csr", "nightly"] }
leptos_router = { version = "0.5.4", features = ["csr", "nightly"] }
regex = "1.10.2"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"

**To Reproduce**
1. Start the app as trunk serve --open
2. On browser type url 127.0.0.1:8080/admin/mail and enter
3. Then click on link /admin/mngpost
4. Now type 127.0.0.1:8080 and enter
5. Now click on browser's go back button

**Expected behavior**
Should go back to root url but fails to load with the error given

**Additional context**
This project is public and can be found here https://github.com/jsoneaday/rust-blog

**Comment by gbj** [comment]
The fact that this is an intermittent and fairly hard to reproduce error, and that it is a WASM parsing error, makes me think the source of it lies somewhere outside this library. I wonder, for example, whether there's a chance that it's a caching issue: i.e., if it happens when you are working in a loop of changing and recompiling the app, and if there's a point where the JS and WASM are out of sync, or something.

Alternatively, whether a `cargo clean` and rebuild fixes it. 

But I think there's something going on that is not related to Leptos per se.

**Comment by jsoneaday** [comment]
cargo clean sounds reasonable. I'll try that
