### ISSUE TITLE
Res and LazyServerFnMap should be pub 

### ISSUE THREAD

**Issue by benwis** [leptos-rs/leptos#2236]
Those should be public for external implementers

**Comment by gbj** [comment]
`LazyServerFnMap` is *partly* private by design. i.e., making it `pub` in the initial release would mean that any changes to it were breaking changes, if we decided to switch out dashmap or something.

If it turns out that it's useful to abstract over the server fn map so it can be shared across integrations (Actix and Axum modules internally, and external integrations for Viz, Spin, etc.) then we should probably create a minimal struct type that includes only the functionality we need and export that, instead of exporting the type alias itself, just so we can make any needed changes without breakage.

**Comment by benwis** [comment]
I'm going to close this, I did basically end up reproducing the type, and import behavior is a little inconsistent, but it's fineTM
