### ISSUE TITLE
How to Use CDN Url for Static Assets When Deploying with SSR?

### ISSUE THREAD

**Issue by CodingFlow** [leptos-rs/leptos#2281]
When deploying using SSR, I would like to specify an absolute path for all static client-side assets, including the initial client-side java-script file and wasm file. This will allow using a CDN for static assets. Currently, I have not found a way to alter the relative paths for static assets; a preceding slash `/` is always added. I'm using the [start-aws template](https://github.com/leptos-rs/start-aws). Is there a way to accomplish this?

**Comment by gbj** [comment]
I transferred this issue into the main repo because it's not related to `cargo-leptos`, but rather the glue code injected by the server integrations. It should be perfectly possible to introduce some logic here that does something like "at compile time, look for an environment variable named `CDN_PKG_PATH` and use that instead of `&option.site_pkg_dir`.

https://github.com/leptos-rs/leptos/blob/d4bdc36062368a2160aafb89ebc062634d09d03f/integrations/utils/src/lib.rs#L53-L59

https://github.com/leptos-rs/leptos/blob/d4bdc36062368a2160aafb89ebc062634d09d03f/integrations/utils/src/lib.rs#L103-L111

Any interest in making a PR?

**Comment by zoomiti** [comment]
I decided to pick up this because it should be a short and sweet PR. Just to clarify though, the env var should be checked at compile time?
