### ISSUE TITLE
Moving All The Time

### ISSUE THREAD

**Issue by owlwres** [leptos-rs/leptos#2505]
My immediate reaction to moving signals into closures and having multiple closures, where moving should indicate that the closure should take ownership, has been off-putting to me.

It is not pleasing at all to write move all the time, and why it should it even be necessary, because shouldn't the macro just take care of this for me?

**Comment by owlwres** [comment]
I am trying to do some introspection here that whether my issue is fundamentally with Rust copy semantics, but we are still inside of the macro, I'm not sure how much can be done inside of a macro.

**Comment by gbj** [comment]
The (component and view) macros are designed to do as little magic as possible. The view macro in particular does almost nothing surprising by default: it just expands an XHTML-like syntax for creating DOM elements into an equivalent Rust builder syntax, and directly inlines Rust expressions from the code you write in the macro into the arguments of those function calls. If you use  `cargo expand` or rust-analyzer to see the macro output you will see what I mean. 

So the macro simply does not do things like "analyze all the Rust code I write here and transform it (by inserting `move` before any `||` it finds). I do not think this would be good; it is always possible to insert `move` into the macro as needed, but it would not be possible to remove false-positive-inserted `move`s because they would be generated by the macro. 

I don't see an example if your post here, but I also wonder if you are regularly doing things like `move || some_thing()` or `move || some_thing.get()` when you could just be using `some_thing` instead. 

Do you have an example of what you mean?

(But yes more broadly your complaint is against Rust's decision to use capture-by-reference semantics by default even for `Copy` values. But this decision follows a similar principle to not inserting `move` automatically -- anything done implicitly and automatically can't be opted out of. Rust as a language will usually opt for explicitness over brevity.)
