### ISSUE TITLE
Portal strange behavior with reactive children

### ISSUE THREAD

**Issue by gzp79** [leptos-rs/leptos#2693]
**Describe the bug**
I've tried to implement a tooltip using portal and I've noticed that
- having a node_ref on the child of a Portal makes the node_ref assigned multiple times.
- the Portal's children are removed and appended on any reactive change (instead of updating the existing dom items). In chrome in element view the mounted div disappears and re-appears again - so I assume they perform a full remove/add cycle instead of an simple "update".

**Leptos Dependencies**

```toml
leptos-use = { version = "0.10", features = ["serde"] }
leptos = { version = "0.6", features = ["csr"] }
```

**To Reproduce**
```
#[component]
pub fn Tooltip<T>(
    #[prop(into)] trigger: NodeRef<T>,
    children: ChildrenFn,
) -> impl IntoView
where
    T: ElementDescriptor + Clone + 'static,
{
    let tooltip = create_node_ref();

    let UseElementBoundingReturn {
        top,
        //right,
        //bottom,
        //left,
        ..
    } = use_element_bounding(trigger);

    let tooltip_style = create_memo(move |_| {
        let top = top.get();
        [
            "position: absolute",
            "transform: translate(-50%, -100%)",
            &format!("top: {}px", top),
        ]
        .join(";")
    });

    view! {
        <Portal>
            <div style=tooltip_style.get() node_ref=tooltip>
                {children()}
            </div>
        </Portal>
    }
}

```    

**Expected behavior**
The elements are mounted only once and updated based on the reactive property changes.

**Comment by gzp79** [comment]
Is there any update, hint in the topic ?
The reactivity of the Portal works by replacing the whole dom element, Is it possible to make it only "update" the element on any change in a similar way as the other elements are working (according to my understanding).

**Comment by gbj** [comment]
You don't provide a complete reproduction here but I think it's enough to guess.

If I change 
```
style=tooltip_style.get()
```
to
```
style=tooltip_style // or move || tooltip_style.get()
```
the node ref is not filled multiple times. 

Normally, the first one wouldn't be reactive, and the second one.

Instead, what happens is that the first one gets registered with the Portal's own effect, while the second one behaves correctly. 

The same thing might explain the second issue/bullet point, although I don't think you provided a reproduction to show what you mean there.

Essentially, if you are re-triggering the Portal it's because you accidentally have what would otherwise be untracked reads in the children of Portal. 

#2693 adds an `untrack()` around the children of Portal so that the re-render doesn't happen here, but your untracked read will still be an issue.
