### ISSUE TITLE
`0.7-beta` Action prematurely cancelled when called within `Effect`

### ISSUE THREAD

**Issue by boyswan** [leptos-rs/leptos#2746]
```rust
#[server(GetDemo)]
pub async fn demo() -> Result<(), ServerFnError> {
    tokio::time::sleep(Duration::from_millis(500)).await;
    Ok(())
}

#[component]
fn Example() -> impl IntoView {
    let count = RwSignal::new(0);
    let action = ServerAction::<GetDemo>::new();
    let on_click = move |_| count.update(|c|*c += 1);


    Effect::new(move |_| {
      let _ = count.get();
      action.dispatch(GetDemo {});
    });

    view! { <button on:click=click>Trigger</button> }
}
```

If the button is clicked for the second time, before the first http request is resolved, the first request is canceled.

This does not happen if the action is dispatched from within the on_click handler - only when inside the effect.

**Comment by gbj** [comment]
This is working as currently designed, although I'm open to being argued out of it. i.e., the spawned action is canceled when the effect reruns, just like other owned resources are cleaned up.

**Comment by boyswan** [comment]
I can see the benefit of the functionality you describe, but I'm not sure the current design quite captures the nuance of when something should be cancelled, and also makes it challenging to achieve my intended behaviour of overlapping requests (from an effect).

Perhaps providing more explicit "cancelable" dispatch methods might help users understand _when_ an action is capable of being cancelled, such as `dispatch_cancelable`. It might then make sense to also provide a `cancel` method, which provides further control (ie. calling manually in `on_cleanup`). 

Whilst automatically cancelling as default behaviour does offer convenience, it comes at a cost of being quite opinionated. What if I _don't_ want my request to cancel if I was to navigate away?

**Comment by gbj** [comment]
Thinking about it more, I think you're 100% right. An action is more like a side effect than it is like a reactive node. It would make sense to cancel, for example, a resource load when its owner is disposed because that means the resource is being disposed: it makes no sense to cancel a dispatched action when its owner is disposed, in the general case.

I don't know why I hadn't thought of this before, but it seems to me that the obvious answer here is to return a handle that allows for cancelation from `dispatch`. If the user wants to run that on cleanup it's then very simple.
```rust
let handle = action.dispatch(/* ... */);
Owner::on_cleanup(move || handle.abort());
```
