### ISSUE TITLE
Feauture Request: Stream-managed state signal

### ISSUE THREAD

**Issue by littlebenlittle** [leptos-rs/leptos#2759]
**Is your feature request related to a problem? Please describe.**

It is common to update a value based on symbols received from IO devices. For example, adding and removing items from a collection when "Create" and "Delete" instructions are received over a websocket.

Signals derived from streams may not trigger effects for every update when those updates are very rapid.

```rs
let sig = create_signal_from_stream(futures::stream::iter([1,2,3,4]));
create_effect(|_| {
    console_log!("{}", sig.get())
};
```

In the above code, the console will likely only log "4" as it is the last value sent by the stream.

This is a problem for more complex state machines, where the local and remote environment must agree on which symbols were received and in what order. Right now it isn't clear what the timing cutoff is for guaranteed delivery of all stream values.

**Describe the solution you'd like**

One way to handle this situation is to create state signals whose values are managed by streams. The API might look like

```rs
enum Symbol {
    Create(String),
    Delete(String,
}

let collection: Signal<HashSet<String>> = create_stream_managed_signal(
    HashSet::new(),
    |state: HashSet<String>, symbol: Symbol| match symbol {
        Symbol::Create(val) => state.insert(val),
        Symbol::Delete(val) => state.remove(val),
    }
);
```

The most basic implementation I foresee would be a slight modification for the code for `create_signal_from_stream`, where the update is applied before the signal is written to.

One open question is how often this signal updates. Should that be best effort ASAP? Should it be user-configurable? I would appreciate input from those more familiar with Runtime implementation.

**Describe alternatives you've considered**

Clearly this could be a separate crate, but it seems fundamental enough to warrant inclusion in the main leptos system with input from maintainers.

**Comment by gbj** [comment]
Could you clarify how this would differ from reading from a Stream using the normal API (`while let Some(value) = stream.next().await`) and writing to a signal with the values, notifying as often as you'd like to?

**Comment by dmgolembiowski** [comment]
> Could you clarify how this would differ from reading from a Stream using the normal API (`while let Some(value) = stream.next().await`) and writing to a signal with the values, notifying as often as you'd like to?

I cannot speak for @littlebenlittle but it would be cute to see this work in tandem with a client-supplied parking lot to facilitate parking and resuming.

**Comment by littlebenlittle** [comment]
> Could you clarify how this would differ from reading from a Stream using the normal API (`while let Some(value) = stream.next().await`) and writing to a signal with the values, notifying as often as you'd like to?

Async task execution is non-deterministic, however (from my understanding, please correct me if I'm wrong) the current assumption is that the Runtime will _definitely_ be polled in between polls to `stream.next()`. Essentially, correct execution of a state machine built on signals is dependent on something that is only _usually_ true.

One case where this might fail is a program that pulls a large multi-part JSON object from an API. It then parses the response and produces the results individually as a stream. The parser may be very fast for some values and slow for others, so the non-blocking nature of an async task is useful. However when it's fast, the Runtime may not receive all signal updates, resulting in incorrect behavior.

**Comment by gbj** [comment]
By "runtime being polled" I assume you mean effects running? I agree that effects are not guaranteed to run every time a signal changes, but rather exist to synchronize the current value of a signal with something in the non-reactive world.

Streams and signals are quite different, where a stream := a stream of values, in which each value matters, and a signal := a value that changes over time. Signals are only concerned with the latest value, and not the intermediate values. This is very intentional and is designed to *minimize* the number of times a side effect runs, because it is designed for things like "update the UI" or "make a network request" in a paradigm in which a signal is understand as a valueful thing, not a stream of values.

In other words, this
```rust
    let sig = ReadSignal::from_stream(futures::stream::iter([1, 2, 3, 4]));
    Effect::new(move |_| leptos::logging::log!("{:?}", sig.get()));
```
will only log `Some(4)` and I am very confident that this is the correct behavior for a UI library.

If, on the other hand, you want to act on each of the values — that's exactly what the `while let` loop lets you do.

If you are trying to update some value (like a signal holding a state machine), then you can

```rust
    let mut stream = futures::stream::iter([1, 2, 3, 4]);
    let data = RwSignal::new(vec![]);
    spawn_local(async move {
        while let Some(next_value) = stream.next().await {
            data.update(|n| n.push(next_value));
        }
    });
    Effect::new(move |_| leptos::logging::log!("{:?}", data.get()));
```
This will not drop any values and will add them all to the `data` signal. This is why I'm asking how this differs from a `while let` that updates a signal": I can't tell the difference between what `create_stream_managed_signal` would do and what the loop above does. 

Or is the issue really that you want an `Effect` that really does run every time a signal changes?

**Comment by littlebenlittle** [comment]
Thank you for the detailed explanation! I think that clarifies the underlying conceptual problem I'm having, which concerns the API boundary between stream-based world and the signal-based world.

In some sense, the goal of a signal is to over-approximate the cumulative effect of a stream, producing these cumulative values when there is downtime in the stream processing. I understand your point about the `stream.next()` construction now, which is definitely correct given the above guarantee.

Is there anywhere in the leptos book that explains this stream-to-signal conversion in depth? It seems like a useful topic that may be obvious to those with a strong background in reactive programming, but may lead less experienced individuals (such as myself) to massively overthink the design of their programs.

**Comment by gbj** [comment]
> Is there anywhere in the leptos book that explains this stream-to-signal conversion in depth? 

No, there's not. It's not a frequently asked question (at least, this is the only time I can recall it being asked!)

**Comment by luckynumberke7in** [comment]
FWIW, I think this pattern mentioned is extremely useful and it is something I couldn't think of how to achieve in the reactive landscape.

These are exactly the kinds of discussions / explanations from Greg that help me elucidate how to efficiently handle the mid to more complex parts of reactive programming. 

This kind of thing would be valuable to me in the docs or a little reactive / leptos takeaway blog channel for conceptual snippets.
