### ISSUE TITLE
Implement `.write()` on `Store`/`ArcStore`

### ISSUE THREAD

**Issue by gbj** [leptos-rs/leptos#2936]

**Comment by brofrain** [comment]
@gbj
I was trying to implement this via brainlessly copy-pasting code from `Subfield`. It worked well for `Field`, but `ArcStore` and `Store` don't seem to trigger effects.

```rust
impl<T> Writeable for ArcStore<T>
where
    T: 'static,
{
    type Value = T;

    fn try_write(&self) -> Option<impl UntrackableGuard<Target = Self::Value>> {
        self.writer()
    }

    fn try_write_untracked(
        &self,
    ) -> Option<impl DerefMut<Target = Self::Value>> {
        self.writer().map(|mut writer| {
            writer.untrack();
            writer
        })
    }
}
```

I haven't been able to pinpoint where the problem lies exactly, but I suspect that `self.writer()` being untracked isn't the intended behavior?
I need a little help with this 🙂

**Comment by gbj** [comment]
This was [done](https://docs.rs/reactive_stores/latest/reactive_stores/struct.Store.html#impl-Write-for-Store%3CT,+S%3E) at some point, and I forgot to mark this closed.
