### ISSUE TITLE
`Signal<T, S = SyncStorage>` doesn't implement `Track`

### ISSUE THREAD

**Issue by maccesch** [leptos-rs/leptos#2976]

**Comment by gbj** [comment]
Note that it's not possible to implement `Track` as distinct from the behavior of `Get` for `Signal`, because derived signals can't be tracked without being called. Implementing `Track` here would cause (IMO) surprising behavior, because while calling `.track()` on a `ReadSignal` or `Memo` or other similar node simply tracks that node, calling `.track()` on a `Signal` potentially invokes that inner function, which may be relatively expensive.

A derived `Signal` that needs to be `.track()`ed is better represented as a `Memo`. 

If it's just a question of API design and you want to be able to take `#[prop(into)] Signal<_>` or something and then track it, you can use `with(|_| ())`, which will not clone the values of a `ReadSignal` or `Memo` that is converted into a signal, but will invoke a derived signal. (Of course this is basically what a `Track` implementation would do, so maybe I'm overthinking it.)

Open to being wrong.

**Comment by zakstucke** [comment]
Chiming in, not having track seems to prevent `read()`/`write()` being possible on signals, I'm finding these so ergonomic it would be unfortunate.

**Comment by gbj** [comment]
> prevent `read()`/`write()` being possible on signals

Again, this is because it *isn't* possible, and the trait system is trying to avoid lying to you, arguably at the expense of ergonomics. In fact, `.read()`/`.write()` will likely *never* be possible. `.with()` fakes it by actually calling `.get()` and cloning, but for derived signals there *is* not underlying read or write lock being returned.

I want to distinguish really carefully between "possible on signals" and "possible on the `Signal` wrapper type." `Signal` is specifically designed to allow boxing up derived signals, in addition to `ReadSignal`/`RwSignal`/`Memo` (all of which *do* support `.track()`, `.read()`, and `.write()` in the case of `RwSignal`). 

If you're in a situation where using `.read()` specifically is *necessary* and not just convenient, then you shouldn't accept `Signal`.

**Comment by zakstucke** [comment]
Whoops sorry definitely didn't mean to include `write()`, I was just hoping for `read()` on the signal type. 

Understood on the way Signal fakes `.with()`, but given it would be doing that anyway, couldn't we just... do the same thing for read by putting this cloned value in the read guard? As far as I understand it this is an internal implementation detail the user doesn't need to know about anyway. I definitely may be missing something in which case sorry.

I think this logic might also apply to what @maccesch was porting over from 0.6, if it was using that "faking it" clone prior anyway.


Wouldn't something like this work, it seems to compile:

```rust
    /// 
    pub enum SignalReadGuard<T: 'static, S: Storage<T>> {
        ///
        Read(ReadGuard<T, Plain<T>>),
        ///
        Memo(ReadGuard<T, Mapped<Plain<MemoInner<T, S>>, T>>),
        ///
        Derived(T),
    }

    impl<T, S> Deref for SignalReadGuard<T, S>
    where
    T: 'static,
    S: Storage<T>
     {
        type Target = T;
        fn deref(&self) -> &Self::Target {
            match self {
                SignalReadGuard::Read(i) => i,
                SignalReadGuard::Memo(i) => i,
                SignalReadGuard::Derived(i) => i,
            }
        }
    }

    impl<T, S> ReadUntracked for ArcSignal<T, S>
    where
        S: Storage<T>,
        T: Clone,
    {
        type Value = SignalReadGuard<T, S>;
        
        fn try_read_untracked(&self) -> Option<Self::Value> {
            match &self.inner {
                SignalTypes::ReadSignal(i) => i.try_read_untracked().map(SignalReadGuard::Read),
                SignalTypes::Memo(i) => i.try_read_untracked().map(SignalReadGuard::Memo),
                SignalTypes::DerivedSignal(i) => {
                    Some(SignalReadGuard::Derived(untrack(|| i())))
                },
            }            
        }
    }

    impl<T, S> Read for ArcSignal<T, S>
    where
        S: Storage<T>,
        T: Clone,
    {
        type Value = SignalReadGuard<T, S>;
        
        fn try_read(&self) -> Option<Self::Value> {
            match &self.inner {
                SignalTypes::ReadSignal(i) => i.try_read().map(SignalReadGuard::Read),
                SignalTypes::Memo(i) => i.try_read().map(SignalReadGuard::Memo),
                SignalTypes::DerivedSignal(i) => {
                    Some(SignalReadGuard::Derived(i()))
                },
            }
        }
        
        fn read(&self) -> Self::Value {
            self.try_read().unwrap_or_else(unwrap_signal!(self))
        }
    }
```

I imagine it would be similar for the track trait, just no special guard.

**Comment by gbj** [comment]
Added by #3031.
