### ISSUE TITLE
Re-add warnings to resource access outside suspense.

### ISSUE THREAD

**Issue by zakstucke** [leptos-rs/leptos#3038]
**Describe the bug**
Wow this one was tough to repro, the one I was mentioning as a secondary in #3033 

**Leptos Dependencies**
Current main

**To Reproduce**
Verified on `counter_isomorphic`, happens for both blocking and normal resources, only when the sleep is included.
Notice the extra `<div />` in Either::Left() which causes the mismatch, I'm assuming something doesn't realise the DOM switched from right to left, but I'm not knowledgable enough on the internals to conceptualise further!

```rust
use leptos::{either::Either, prelude::*};
use leptos_router::{
    components::{Route, Router, Routes},
    path,
};

#[component]
pub fn Counters() -> impl IntoView {
    let resource = Resource::new_blocking(
        || (),
        move |_| async move {
            #[cfg(feature = "hydrate")]
            send_wrapper::SendWrapper::new(gloo_timers::future::TimeoutFuture::new(10)).await;
            #[cfg(feature = "ssr")]
            tokio::time::sleep(tokio::time::Duration::from_millis(10)).await;

            "user_info...".to_string()
        },
    );

    view! {
        <Router>
            <Routes fallback={|| {
                view! { <p>404</p> }
            }}>
                <Route
                    path={path!("/")}
                    view={move || {
                        if resource.read().is_some() {
                            Either::Left(
                                view! {
                                    <div>
                                        <p>"Logged in!"</p>
                                    </div>
                                },
                            )
                        } else {
                            Either::Right(view! { <p>"Logged out!"</p> })
                        }
                    }}
                />
            </Routes>
        </Router>
    }
}
```

```
counter_isomorphic.js:461 panicked at /Users/zak/z/code/leptos/tachys/src/html/mod.rs:158:14:
called `Option::unwrap()` on a `None` value

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (http://127.0.0.1:3000/pkg/counter_isomorphic.js:467:13)
    at counter_isomorphic.wasm.console_error_panic_hook::Error::new::h924fea8cb3ceff58 (http://127.0.0.1:3000/pkg/counter_isomorphic.wasm:wasm-function[5441]:0x1be11b)
    at counter_isomorphic.wasm.console_error_panic_hook::hook_impl::h58ee9f32342db93f (http://127.0.0.1:3000/pkg/counter_isomorphic.wasm:wasm-function[1257]:0xff10c)
    at counter_isomorphic.wasm.console_error_panic_hook::hook::hdee489a937dc919b (http://127.0.0.1:3000/pkg/counter_isomorphic.wasm:wasm-function[7526]:0x1e01d9)
    at counter_isomorphic.wasm.core::ops::function::Fn::call::headd6e8fd1c7b033 (http://127.0.0.1:3000/pkg/counter_isomorphic.wasm:wasm-function[6522]:0x1d2043)
    at counter_isomorphic.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (http://127.0.0.1:3000/pkg/counter_isomorphic.wasm:wasm-function[2677]:0x16162f)
    at counter_isomorphic.wasm.std::panicking::begin_panic_handler::{{closure}}::h98de848d678bad07 (http://127.0.0.1:3000/pkg/counter_isomorphic.wasm:wasm-function[3617]:0x18b366)
    at counter_isomorphic.wasm.std::sys::backtrace::__rust_end_short_backtrace::h2bcfc60c3cf0a312 (http://127.0.0.1:3000/pkg/counter_isomorphic.wasm:wasm-function[8814]:0x1ecc8a)
    at counter_isomorphic.wasm.rust_begin_unwind (http://127.0.0.1:3000/pkg/counter_isomorphic.wasm:wasm-function[5768]:0x1c4b78)
    at counter_isomorphic.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (http://127.0.0.1:3000/pkg/counter_isomorphic.wasm:wasm-function[6045]:0x1c9ea1)
```

**Comment by gbj** [comment]
You are reading from a resource during SSR outside of Suspense. This warns on all previous versions, and maybe I need to reimplement that warning if I have not.

**Comment by zakstucke** [comment]
Wow of course, thanks very much! 

I guess I didn't think of this because of `blocking` and thinking suspense is to support streaming between ssr and hydrate lazily. 

Yeah a warning would be great here. I actually wrapped the output of the resource in a `Memo` too, so wasn't thinking of resources and was tough to track down.

**Comment by zakstucke** [comment]
I do have a question though, in this example it's for user loading and I definitely want this to happen before the client receives any html, hence thinking I wanted `Resource::new_blocking()`. 

So given needing the suspense to read this, I have to `<Suspense/>` my entire app. Suspense description says: 
`If any resource is read in the children of this component, it will show the fallback while they are loading.` 
Doesn't that mean all my resources, blocking or not, will end up loading before any of my app loads? 

Is there something better than `Resource::blocking` for async loading of stuff I always want before returning a response?

**Comment by zakstucke** [comment]
I've been looking into this, as far as I can see if I change the `leptos_routes_with_context` (I'm using axum) function to take an async callback for `additional_context` instead of a sync one, I could provide the user there, then in the app in a SharedValue get the user with `expect_context()`. Would this make sense / no better way / worth a PR if I can make it pretty?

**Comment by gbj** [comment]
I'm going to answer a few points from above in what feels like a good order to me, sorry if I miss anything important.

> Yeah a warning would be great here.

Agreed, I'll consider restoring the warning here the "action item" to close this issue.

>  it seems if I change the leptos_routes_with_context (I'm using axum) function to take an async callback for additional_context instead of a sync one, I could provide the user there

Here's the fundamental thing: This would work for the initial page load from the server, but *not* for subsequent navigations on the client, which are handled client-side. (Unless you're using islands and a multi-page-app/server-only navigation style, in which case every load is an initial page load from the server.) This is why we have the (sometimes convoluted) dance of server functions and resources and Suspense -- so that no matter how you load the page (from the server, or from the browser) you only need to write it one way and it works the same.

> I actually wrapped part of the output of the resource in a Memo too, so wasn't thinking of resources and was tough to track down.

This is, in my experience, the primary source of non-obvious hydration errors reported by smart people who know how to use the framework well: passing a Resource through sufficient layers of transformation that you've forgotten that it was ever a Resource, and then accessing it outside Suspense.

> So given needing the suspense to read this, I have to <Suspense/> my entire app.

In a sense, this is the way to fix the above issue. If you have a resource that you genuinely want to load before anything else happens, you can stick it in a top-level `Suspend` to `.await` it and then pass the actual value as a prop or via context. 

So, for example: 
```rust
#[component]
pub fn App() -> impl IntoView {
    view! {
        <Router>
            <Routes fallback=|| {
                view! { <p>404</p> }
            }>
                <ParentRoute path=path!("/") view=AuthCheck>

                    <Route path=path!("/") view=Home/>
                    <Route path=path!("/other") view=Other/>
                </ParentRoute>
            </Routes>
        </Router>
    }
}

#[component]
fn AuthCheck() -> impl IntoView {
    let resource = Resource::new_blocking(
        || (),
        move |_| async move {
            #[cfg(feature = "hydrate")]
            send_wrapper::SendWrapper::new(
                gloo_timers::future::TimeoutFuture::new(1000),
            )
            .await;
            #[cfg(feature = "ssr")]
            tokio::time::sleep(tokio::time::Duration::from_millis(1000)).await;

            Some("user_info...".to_string())
        },
    );

    let inner_view = Suspend::new(async move {
        let user_info = resource.await;
        provide_context(user_info.clone());
        (
            if user_info.is_some() {
                Either::Left(view! {
                    <div>
                        <p>"Logged in!"</p>
                    </div>
                })
            } else {
                Either::Right(view! { <p>"Logged out!"</p> })
            },
            Outlet(),
        )
    });
    view! { <Suspense>{inner_view}</Suspense> }
}

#[component]
fn Home() -> impl IntoView {
    let user_info = expect_context::<Option<String>>();
    format!("{user_info:?}")
}

#[component]
fn Other() -> impl IntoView {
    "Other Page"
}
```

**Comment by zakstucke** [comment]
Thanks a bunch. This makes sense. I think there's a bug with it (I've just tried to implement) but the fundamental idea makes sense, and agree this is the right way, without a much more complicated solution! I'll repro and open a separate issue.

> Agreed, I'll consider restoring the warning here the "action item" to close this issue.

🚀 

> So given needing the suspense to read this, I have to <Suspense/> my entire app. Suspense description says:
If any resource is read in the children of this component, it will show the fallback while they are loading.
Doesn't that mean all my resources, blocking or not, will end up loading before the client sees anything more than a top level suspense fallback?

This was the only bit you didn't cover, are suspenses localised to just their direct children so this wouldn't be an issue?

> Here's the fundamental thing: This would work for the initial page load from the server, but not for subsequent navigations on the client, which are handled client-side.

Makes sense, for this case it's outside the router, so I think my idea would've feasibly worked, but yeah for most cases it wouldn't, so wrong direction.

**Comment by gbj** [comment]
> So given needing the suspense to read this, I have to my entire app. Suspense description says: If any resource is read in the children of this component, it will show the fallback while they are loading. Doesn't that mean all my resources, blocking or not, will end up loading before the client sees anything more than a top level suspense fallback?

Let's try! 

If I update `Home` above so that it creates and reads from an inner resource, what happens?
```rust
#[component]
fn Home() -> impl IntoView {
    let user_info = expect_context::<Option<String>>();
    let inner_resource = Resource::new_blocking(
        || (),
        move |_| async move {
            #[cfg(feature = "hydrate")]
            send_wrapper::SendWrapper::new(
                gloo_timers::future::TimeoutFuture::new(2500),
            )
            .await;
            #[cfg(feature = "ssr")]
            tokio::time::sleep(tokio::time::Duration::from_millis(2500)).await;

            "inner resource".to_string()
        },
    );
    view! {
        {format!("{user_info:?}")}
        <Suspense fallback=|| {
            "Loading inner resource..."
        }>{move || format!("{:?}", inner_resource.get())}</Suspense>
    }
}
```

I get:
- No response while the blocking "user info" resource is loading
- A response after that should "Loading inner resource..." (the inner Suspense fallback)
- Then the full page 2.5s later

This is because the inner Suspense "catches" this resource, not the outer one. Suspense is designed to support exactly this kind of nesting. Perhaps a better way to put it in the docs is that Suspense catches any resource reads in the children *that are not already caught by another Suspense further down the tree.*

**Comment by zakstucke** [comment]
Awesome! Sounds perfect.

This maybe dumb, it seems too simple... but I've just thought I'll never see the warning this issue eventually implements because I'll have my app in a global suspense for user info. So, I just need to make sure to use suspense locally where I need it to avoid everything being captured by the global suspense, but even if I didn't everything should still just... work. 

Why not at a framework level add this outer`<Suspense />`? It removes the need for this warning entirely and this whole class of bugs, making suspense opt-in for fine grained loading, rather than something that can actually cause bugs. 

I'm probably missing something haha.

**Comment by gbj** [comment]
> Why not at a framework level add this outer `<Suspense />`? It removes the need for this warning entirely and this whole class of bugs, making suspense opt-in for fine grained loading, rather than something that can actually cause bugs.

Version one of an answer: because the framework is designed to promote the best user experience and best performance (and therefore best SEO), for the default case in which you can show *something* useful immediately before any data loads. Responding in 10ms (or whatever) with the shell of the page and a loading indicator of some kind and then streaming in the remaining part of the page is a better default user experience than waiting for resources read at the top level to load before returning anything.

Version two of an answer: It's not possible to do out-of-order streaming that replaces the `<html>` tag, for example. Leptos now exposes the entire app shell, so the *user* needs to put a `Suspense` somewhere in user code. Should the default shell included in examples have a top-level Suspense around the App? Maybe, I haven't tried it out. (I think it would cause a hydration issue actually, but maybe a Suspense inside the app itself... in which case we end up in the same situation as before :smile: )

**Comment by zakstucke** [comment]
I can't argue with that, makes sense as long as a nice simple warning works haha.
