### ISSUE TITLE
Starter Home button broke

### ISSUE THREAD

**Issue by jaroel** [leptos-rs/leptos#3395]
**Describe the bug**
Clicking the button on the homepage replaces the button text with '{counter value}0'.

I ran the axum starters with leptos 0.7.*.

https://github.com/user-attachments/assets/7059c4a7-90fe-404f-bb7e-1fe85ccbb7aa

**Comment by gbj** [comment]
Thanks! For the future, it's helpful if you fill out the issue template -- for example, it took me a false start before I realized that this bug only occurred on nightly, rather than stable, but I could've seen you were using nightly if you'd included the relevant section of the template showing your Leptos dependencies.

Should be fixed by #3396 in any case.

**Comment by gbj** [comment]
I should add, though — I don't mean this as a criticism, and my thanks for opening the issue are genuine! For example, just by opening an issue with a very simple reproduction (just clone the starter template and it's broken), you helped me fix a bug that I *hadn't* been able to diagnose in a help chat with someone on Discord. So, thanks again :smile:

**Comment by jaroel** [comment]
No worries, you're right! Happy to help! :)

**Comment by jaroel** [comment]
Yep, verified it now works as expected with release 0.7.2. Thanks!
