### ISSUE TITLE
Support for Lifetimes in Structs Deriving `Store` and `Patch`

### ISSUE THREAD

**Issue by hqdncw** [leptos-rs/leptos#3405]
**Describe the bug**
I'm using the `reactive_stores` crate and I'm encountering an issue when trying to use lifetimes with structs that derive `Store` and `Patch`. Specifically, I'm getting errors related to undeclared lifetime parameters.

**Leptos Dependencies**

```toml
reactive_stores = "0.1.2"
```

**To Reproduce**
```rust
#[derive(reactive_stores::Store, reactive_stores::Patch)]  // throws a compile error
struct Todo<'a> {
    label: &'a str,
    completed: bool,
}
```

**Expected behavior**
no compile errors

**Additional context**
```log
Diagnostics:
1. lifetime `'a` is missing in item created through this procedural macro [E0261]
```

**Comment by gbj** [comment]
I do not think this would be useful, as both Store and ArcStore require that their inner types be `'static`, i,e., the store needs to own its value and cannot contain non-static references. So even if the derive macro worked you couldn't actually use it for anything.

**Comment by 1xX69** [comment]
The problem is that Serde doesn't support zero-copy deserialization without using [lifetimes](https://serde.rs/lifetimes.html#understanding-deserializer-lifetimes). Maybe we could apply something like `Self-Referential Structs` here? something like [ouroboros](https://github.com/someguynamedjosh/ouroboros). Would this work?
