### ISSUE TITLE
Support a `toggle` property for booleans

### ISSUE THREAD

**Issue by ModProg** [leptos-rs/leptos#377]
I'd propose something like:

```
<Card elevated/>
```

if `Card` is defined as:

```rs
#[component]
fn Card(cx: Scope, #[prop(toggle)] elevated: bool) //...
```

with `toggle` obviously also implying `optional`.

This could be the default behavior for booleans (maybe supporting both syntaxes, i.e. both just `elevated` and `elevated=true` would be true and omitting it and `elevated=false` would be false).

**Comment by ModProg** [comment]
This could be implemented to support more than `bool`s if the requirement for `#[prop(toggle)]` was `From<bool>`.

**Comment by gbj** [comment]
Just so I understand: What's this supposed to do, and how is it different from the existing optional props?

**Comment by gbj** [comment]
> This could be the default behavior for booleans (maybe supporting both syntaxes, i.e. both just `elevated` and `elevated=true` would be true and omitting it and `elevated=false` would be false).

One concern I have is that this is not how boolean attributes work in HTML, so people's existing mental model will be  broken. `<input type="text" disabled="false">` in HTML is the same as `<input type="text" disabled>`

**Comment by ModProg** [comment]
Well, but that is already broken in leptos isn't it? Like `disabled=false` => no disabled `disabled=true` => `disabled="disabled"`?

**Comment by gbj** [comment]
I was going to do some work on implementing this this morning, and realized that there's actually a problem I don't think can be solved: Currently the view macro accepts a shorthand for component props where `value=value` can be collapsed to `value` if they have the same name. So
```
<MyComponent
  name=name
  class=class
  value=value
  toggled=toggled
/>
```
can be written
```
<MyComponent name class value toggled/>
```

So in the example
```
<Card elevated/>
```
will expand to 
```
<Card elevated=elevated/>
```
Because proc macros only have access to the syntax tree, not to *any* type or semantic information (which runs later), and because the `#[component]` and `view` macros operate independently, I don't think there's any way to indicate "no, by `<Card elevated/>` I mean the toggle style `<Card elevated=true/>` instead of the shorthand `<Card elevated=elevated/>`

So then this becomes a question of "which syntax sugar is sweeter?" To me, the case where `<Component value=value />` can be shortened to `<Component value/>` is more frequent and therefore more useful than `<Component value=true/>` being shortened to `<Component value/>`. What do you think?

**Comment by ModProg** [comment]
> So then this becomes a question of "which syntax sugar is sweeter?" To me, the case where `<Component value=value />` can be shortened to `<Component value/>` is more frequent and therefore more useful than `<Component value=true/>` being shortened to `<Component value/>`. What do you think?

I'd agree, especially because that is a syntax rustaceans are used to from structs.

One could introduce a custom syntax, e.g. `@elevated` for the flag, but that would reserve a possibly useful token and increase complexity for arguably not the most important shortcut.

**Comment by gbj** [comment]
Yeah, I'm cautious about adding special syntax so I'm going to close this one for now.
