### ISSUE TITLE
`hgroup` isn't supported

### ISSUE THREAD

**Issue by ModProg** [leptos-rs/leptos#378]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hgroup

I get this error trying to use it in the `view!` macro:
> cannot find function `hgroup` in crate `leptos::leptos_dom`

**Comment by gbj** [comment]
Oh, weird.

If you want to make an easy PR you just need to add it somewhere around here, following the same format as all the other elements (a comment usually from the MDN description, the tag name, and the `web_sys` element type with in this case is `HtmlElement`) Otherwise I can do it tonight some time

https://github.com/leptos-rs/leptos/blob/fc7199f188e1eda1b4529a98b7f27e326b9a5c98/leptos_dom/src/html.rs#L1045
