### ISSUE TITLE
Tailwind Example CSR Issues

### ISSUE THREAD

**Issue by SteveCookTU** [leptos-rs/leptos#394]
I have been playing around with the Tailwind example and noticed two issues with the CSR option.

1. It is noted to use Trunk for serving static versions. In the example, `wasm_bindgen` is used to define the entry function but trunk now uses the normal `main` function used for binaries.
2. After fixing the above, the css linked is no longer valid. The css file found in `pkg` actually contains javascript that looks to be page initialization (contains pre-load for wasm etc). My fix for this was to directly apply the stylesheet inside `index.html` by using `<link data-trunk rel="css" href="./style/output.css" />`. Also, removing the `Stylesheet` component from the App to prevent extra serving of files. I was unable to find any known issues regarding this and also no other workarounds. 

If I'm missing something for CSR that causes this issue I would love to know what is considered standard for Leptos as I have only just discovered it recently.

**Comment by gbj** [comment]
Oh sorry this README is out of date for the example. I should fix it up a little. This particular example is not compatible with Trunk at the moment.

**Comment by SteveCookTU** [comment]
I was able to get somewhat of an understanding by looking into other examples that I notice have been used as a reference point for recent changes. My main confusion was the general setup for CSR. 

I notice the examples all contain both SSR and CSR and was wondering if there was interest in a `Simple Server` and/or `Simple Client` rendering examples? Other than docs it may be a good idea to split the two for newcomers like myself.

**Comment by gbj** [comment]
The `counter`, `counters`, `fetch`, `parent_child`, and `router` examples are client-side-only using Trunk. The rest of them are server-side rendering with client-side hydration with `cargo-leptos`; some of these (like `hackernews`) also support client-side-only rendering.

I could see why it would be confusing that the examples are divided up by topic rather than rendering method. Maybe a note in the README about where to go for the simplest versions of each would be helpful, or, as you say, simple examples -- although the simple examples are `counter` (for CSR) and the `leptos-rs/start` starter (for SSR).

The Tailwind README comes from an older set of instructions on using Tailwind, so the client-side info doesn't map directly onto the example.

**Comment by SteveCookTU** [comment]
Thank you for the insight!

Going to close this issue then keeping what you mentioned in mind.
