### ISSUE TITLE
Hydration Mismatch on Subsequent Requests

### ISSUE THREAD

**Issue by seanaye** [leptos-rs/leptos#417]
I'm working on integration with [Aleph.js](https://github.com/alephjs/aleph.js)

On the first page load after wasm-pack compilation the app hydrates successfully (even on HMR after wasm-pack compiles)

Successful hydration:
<img width="853" alt="Screen Shot 2023-01-31 at 8 01 24 AM" src="https://user-images.githubusercontent.com/24496822/215813034-4d284973-5ff9-4672-a7dc-cc0bac2bc794.png">

However, on every subsequent page load the app fails to hydrate and instead creates a second app instance under the server rendered html. 

Unsuccessful hydration:
<img width="876" alt="Screen Shot 2023-01-31 at 8 00 35 AM" src="https://user-images.githubusercontent.com/24496822/215813086-b370e8ce-0081-4260-9d5a-467e4f47d3c9.png">

The server is sending different hydration html the second time and I cannot figure out why that is.

Repro url: https://github.com/seanaye/aleph.js/tree/seanaye/feat/leptos-support/examples/leptos-app

Steps:
1. Make sure you have `deno` installed
2. `Deno run -A dev.ts`
3. Open localhost:3000, page hydrates properly
4. Refresh page, hydration mismatch

**Comment by gbj** [comment]
Couple things:
1. Your `hydrate` function can be cleaned up a lot. In the browser, RouterIntegrationContext is provided by default, and you have a duplicated `console_error_panic_hook::set_once()`
```rust
#[wasm_bindgen]
        pub fn hydrate() {
            console_error_panic_hook::set_once();
            _ = console_log::init_with_level(log::Level::Debug);

            web_sys::console::log_1(&"hydrate".into());

            mount_to_body(|cx| {
                view! { cx,  <App/> }
            })
        }
```
2. On the server, you're kind of reimplementing the `render_to_string` function Leptos provides, but incompletely. Specifically, you're not resetting the hydration context, so the IDs keep ticking up on every reload. Here's a working version.
```rust
else if #[cfg(feature = "ssr")] {
        use wasm_bindgen::prelude::wasm_bindgen;
        use leptos::*;
        use leptos_router::{ServerIntegration, RouterIntegrationContext};
        pub mod routes;
        use routes::{App, AppProps};

        #[wasm_bindgen]
        pub fn ssr(url: String) -> String {
            let history = ServerIntegration { path: url };
            let router_integration = RouterIntegrationContext::new(history);
            render_to_string(move |cx| {
                provide_context::<RouterIntegrationContext>(cx, router_integration);
                view! { cx, <App/> }
            })
        }
    }
```

I should say your version is also leaking the reactive runtime on each request, because the runtime you create isn't disposed. (Compare the implementation of [`render_to_string`](https://docs.rs/leptos_dom/0.1.3/src/leptos_dom/ssr.rs.html#22-25))

I'd suggest taking a look at the Actix/Axum integrations if you want to develop this further to include things like streaming HTML rendering for `Resource`s and `<Suspense/>`, server functions, etc. Feel free to ask [in our Discord](https://discord.gg/YdRAhS7eQB) if you run into any hiccups.
