### ISSUE TITLE
Hydration error with <Outlet /> in router.

### ISSUE THREAD

**Issue by b4-io** [leptos-rs/leptos#431]
Sorry for being the hydration problem guy :disappointed:. Today i continued to had the hydration error and was able to find the culprit. 
For each `<Outlet />` used when defining my routes the hydration fails to find 1 marker. 

[Example repo.](https://github.com/b4-io/leptos-hydration-error).

#425 #421

**Comment by b4-io** [comment]
#425

**Comment by gbj** [comment]
Pretty sure this is actually the same as #422. I'll look into it.

**Comment by gbj** [comment]
Just for the sake of clarity: does the hydration mismatch warning cause anything that should be interactive in your app not to be interactive? I'll need to figure it out in any case but I'm just curious if you have an example where the hydration warning causes broken behavior rather than just the warning. (For example, if I put a button inside the Suspense there is still the mismatch but the button does actually hydrate correctly.)

**Comment by b4-io** [comment]
Yes, with the hydration missmatch when using suspense with a resource it completely fails to know where to insert the new data. I'll record a clip and show it.

**Comment by b4-io** [comment]
Just updated de repo to show that error

**Comment by gbj** [comment]
Thanks! This is helpful. The issue is definitely an internal/framework one; I've been doing some work tracking it down, and should be able to find a fix in the next few days.
