### ISSUE TITLE
Multiple Event listeners on one event type

### ISSUE THREAD

**Issue by ModProg** [leptos-rs/leptos#461]
The main benefit for my usecase is adding an event listener to the root element of a component, both inside and outside:

> 
> Component = `<input on:input= |_| do_some_thing()/>`
> Callsite: `<Component on:input=|_| do_some_thing_else()/>`
> 
> `do_some_thing` will never be called, but:
> 
> Component = `<div><input on:input= |_| do_some_thing()/></div>`
> Callsite: `<Component on:input=|_| do_some_thing_else()/>`
> 
> works as expected, and both `do_some_thing` and `do_some_thing_else` are called.
> 
> _Originally posted by @ModProg in https://github.com/leptos-rs/leptos/issues/448#issuecomment-1416117266_

Additionally, this allows easy composing of multiple event listeners on e.g. a button if you have one to add an animation and one to do the actual clicking:

```
<button on:click=ripple on:click= move |_| some.action() />
```

**Comment by gbj** [comment]
Thinking about it more: 

1. In the component case: I've set up component `on:` attributes (in #470) to use regular event listeners now instead of event delegation, so they don't wipe out the element listeners for the same event. This seems like a good way of avoiding the abstraction leak of needing to know what event listeners the component implementation is using, to avoid conflicting. So that part should be resolved.

2. In the element case: The reason these multiple event listeners are overridden at the present is because our event delegation system assumes one event listener of the same name per element. This is important for performance reasons when creating elements and assigning handlers.

You can opt out of this behavior and use regular event listeners by using the `on:____:undelegated` syntax like so
```
<button on:click:undelegated=ripple on:click:undelegated=move |_| some.action() />
```
From my perspective, this is kind of a performance antipattern and should probably be
```
<button on:click=|ev| { ripple(ev); some.action(); } />
```
i.e., composing by calling multiple functions within the listener rather than by creating multiple listeners. It probably won't matter in most applications but adding two separate listeners is a significant drag.

**Comment by ModProg** [comment]
>     1. In the component case: I've set up component `on:` attributes (in [fix: don't override element event listeners with component event listeners #470](https://github.com/leptos-rs/leptos/pull/470)) to use regular event listeners now instead of event delegation, so they don't wipe out the element listeners for the same event. This seems like a good way of avoiding the abstraction leak of needing to know what event listeners the component implementation is using, to avoid conflicting. So that part should be resolved.

This was my main need for this feature.

> You can opt out of this behavior and use regular event listeners by using the `on:____:undelegated` syntax like so

Then I think this can be closed.
