### ISSUE TITLE
`#[component]` support without cx:Scope

### ISSUE THREAD

**Issue by ModProg** [leptos-rs/leptos#467]
Maybe this is by design as a component without `cx:Scope` is very restricted, but if one doesn't use the `cx` I'm not sure if we should force a cx present`.

**Comment by gbj** [comment]
There would be no way for the `view` macro to know at macro time whether a given component would take `cx` or not. Not to mention a component that doesn't have a `Scope` almost literally can't do anything: it can neither interact with the reactive system nor render a view, since the `view` macro takes a `Scope` as well.

**Comment by ModProg** [comment]
Actually, we have a check here: https://github.com/leptos-rs/leptos/blob/main/leptos_macro/src/component.rs#L40-L54 . But I agree, there is no actual need for it.

**Comment by gbj** [comment]
That's in the `#[component]` macro. I'm saying that in the `view` macro, there's no way to know whether a particular component needs to be passed a `Scope` or not.
