### ISSUE TITLE
Is there a Unit-Testing Story

### ISSUE THREAD

**Issue by eiswind** [leptos-rs/leptos#489]
Do you have any plans on supporting unit-tests for components?
None of the current Rust Web-Frameworks I have seen has this, it a pity.

**Comment by gbj** [comment]
The end-to-end testing story is pretty good, using `wasm-pack test` (which as I understand it is now incorporated into `cargo test --target=wasm32-unknown-unknown`) which uses a headless browser. You can see an example of integration tests for a Leptos app in our [`counters`](https://github.com/leptos-rs/leptos/tree/main/examples/counter) example (in the `tests` directory). (`cargo-leptos` also comes with built in e2e testing via Playwright, although I haven't explored it too much.)

Unit tests for components in any browser-based framework are quite hard, because it usually means spinning up a headless browser or using something like JSDOM which doesn't necessarily precisely emulate real browsers anyway.

Take a look at the example of testing for the counter app. If there are specific improvements you think could be made to how we're enabling testing, let me know!

**Comment by eiswind** [comment]
The new docs look great!
