### ISSUE TITLE
Support `rkyv` encoding

### ISSUE THREAD

**Issue by 617a7a** [leptos-rs/leptos#528]
Could we add a feature flag to support [`rkyv`](https://github.com/rkyv/rkyv) encoding in `Serializable`?

Motivation: we use rkyv encoding for our API (built on Actix) and would like to load data from it using SSR. [More](https://david.kolo.ski/blog/rkyv-is-faster-than/) details [why](https://rkyv.org/motivation.html).

**Comment by gbj** [comment]
Sure! I've never used it -- Do you want to make a PR to add it?

**Comment by 617a7a** [comment]
In the works! Just making sure I don't break anything else 😂

**Comment by 617a7a** [comment]
Do you have any preferences/recommendations on how I should add support?

```rs
pub trait Serializable
where
    Self: Sized,
{
    /// Serializes the object to JSON.
    fn to_json(&self) -> Result<String, SerializationError>;

    /// Deserializes the object from JSON.
    fn from_json(json: &str) -> Result<Self, SerializationError>;
}
```

Maybe we could change this to a generic to/from and use `Vec<u8>`s? Depends what else uses it.

**Comment by gbj** [comment]
The whole idea of the `Serializable` trait is that it allows resource data to be sent as part of the HTML stream: quite literally as part of a `<script>` tag. So it doesn't *have* to be JSON, necessarily, but it does have to able to be encoded as a string to be sent from the server to the client. (Off the top of my head I'm not sure whether we use JSON parsing in the browser -- I think at the moment it's just sending strings and letting the client library decode them.) So if you're using a binary format you'd probably need to convert it to a base64 string or something to send it.

**Comment by 617a7a** [comment]
In that case, it might be better to just do client-side fetching, as one of the advantages is the lower data size. If we're converting it back to a string anyway... might be better to do things as an SPA.

**Comment by gbj** [comment]
I'd do some testing under real use cases, and with speed throttled if that meets your use case — in general beginning fetching resources on the server + streaming them will perform better than client-side fetching because the process is

**With `create_resource` + serialization**
- Client makes GET request => HTML + server begins loading data
- Client loads JS + Wasm
- Client is streaming + compiling Wasm
- ====> data from server usually arrives around here
- Client runs Wasm, resource is already there

**client-side fetching**
- Client makes GET request => HTML
- Client loads JS + Wasm
- Client compiles and runs Wasm
- Client makes GET request for data => rkyv
- Client has data

I'd be surprised if the extra data size of using a JSON format or base64-encoded rkyv offset the advantage of beginning loading it on the server, but it will depend a lot on all the variables (how large your data is, how long the API request takes, how large your Wasm bundle is, how fast the client connection speed is)

**Comment by 617a7a** [comment]
API calls are very fast (within same datacenter, so ~5-15ms tops). Client connection speed will be very low sometimes, too. I'm going to keep trying to get this working. Having data served directly from the server on first load will be a much better UX.
