### ISSUE TITLE
How can we run a unit test with a normally hydrate frontend?

### ISSUE THREAD

**Issue by eiswind** [leptos-rs/leptos#586]
Today I tried to setup a new playground with cargo-leptos (with the template).

I tried to add the test  from the counter example, but somehow it fails to find any div.

I have seen a comment regarding client side tests in main.rs. Do I need to add a main there?

BTW There are some imports missing on the Counter test example. Should I open a PR for that one?

**Comment by gbj** [comment]
> Today I tried to setup a new playground with cargo-leptos (with the template).
> 
> I tried to add the test from the counter example, but somehow it fails to find any div.

Could you share a reproduction repo?

> BTW There are some imports missing on the Counter test example. Should I open a PR for that one?

Yes, please!

**Comment by eiswind** [comment]
Thanks for the quick reply. 
I pushed a minimal reproducer to
https://github.com/eiswind/hello-leptos/blob/main/tests/mod.rs
The console.log shows that the div does not seem to be mounted at all.
Hope you can make something of it.

For the counter test example, I opened 
https://github.com/leptos-rs/leptos/pull/588

**Comment by gbj** [comment]
Ahhh okay here's a good one. It's simply because, if you run this with `wasm-pack test`, Leptos has neither the `ssr` (server-side rendering of HTML) nor `hydrate` (rendering in browser after SSR) features enabled, so the Leptos rendering does nothing.

If you run this was `wasm-pack test --features=hydrate` it works as expected.

I'd also note that `cargo-leptos` comes with integrated Playwright testing. You can find the tests in `end2end` and run them with `cargo leptos end-to-end`. Playwright is a pretty polished testing experience for e2e testing, although you do need to write the tests in JavaScript.

**Comment by eiswind** [comment]
OH! Thanks for helping me out with that one. It's working ! :)
