### ISSUE TITLE
Create contributors' guide

### ISSUE THREAD

**Issue by gbj** [leptos-rs/leptos#59]
Per @jquesada2016 in https://github.com/gbj/leptos/issues/53#issuecomment-1304910693 it would be a great idea to put together a short guide to make it easier for people to contribute.

I'm curious to hear from others what sort of stuff would be useful in there.

Outline of the various packages and what goes where? General approach of each? Normal flow of execution in the program?

What would be useful?

**Comment by jquesada2016** [comment]
I personally have two suggestions. I believe that since the crate is in the early stages, and major changes are likely to ensue, an overview of the approaches, or architecture of the overall project would be most useful. This can be, for example, explaining the core principles on how the reactive system manages to be `Copy`, the purpose of the `Scope`, etc. Also, what techniques are used for updating the DOM reactively. Are components treated specially? Etc. No need to be specific to current code, as this will likely change. Perhaps once 0.1.0, then more specifics could be included.

The thing I believe would help the most, especially because one would only need to do this once upfront, and then gradually as things change, is to add `#[deny(missing_docs)]`.

**Comment by luckynumberke7in** [comment]
@jquesada2016 had really the most important bits in my mind, especially given the nature of the reactive system being so drastically different to most modern mental models...as well as your included bits.

I don't think I have that level of input just yet, but thinking more to ease scaling  (which is likely in my opinion) without you pulling your hair out.

I think setting up a PR syntax is a good idea so future maintainers can more easily skim PRs, also include some form of Prettier, etc. so the code is unified in layout.

Maybe an iterative FAQ page for contributors -- for those specific instances of misunderstanding of whatever version the contributor guide will be (I can almost guarantee I'll be asking one of those FAQs xD)

If there is a specific way you are interpreting a library like Solidjs and extracting the required information to re-create in Rust, a quick example might also be nice.
