### ISSUE TITLE
[Bug] Hard-coded CSS gets overwritten by conditional CSS in certain cases

### ISSUE THREAD

**Issue by rakshith-ravi** [leptos-rs/leptos#735]
As discussed on discord, the following input does not work as expected:

```html
<div class:dark=color_scheme_signal class="dummy">
```

It ends up outputting only the `dark` class.

On the other hand, changing the order of the hard-coded class to be first, before the conditional class, seems to work well:

```html
<div class="dummy" class:dark=color_scheme_signal >
```

In this case, both `dummy` as well as `dark` gets set to the element in the DOM.

CC @benwis

**Comment by gbj** [comment]
Yeah, this is interesting! The framework honestly works in a pretty straightforward way. 
```xml
<div class:dark=color_scheme_signal class="dummy">
```
basically expands to something like (pseudocode)
```rust
// create div
let div = Div::new();

// set up effect to update one class
create_effect(cx, move |_| {
  let dark = color_scheme_signal();
  if dark {
    div.class_list().add("dark");
  else {
    div.class_list().remove("dark");
  }
});

// set class attribute
div.set_attribute("class", "dummy");
```
Hopefully you can see why this creates the broken behavior. The framework is doing exactly what you tell it, in the order you tell it.

But that's obviously not ideal.

So, the PR splits things up so that `class:` attributes are always placed after the `class` attribute and it doesn't wipe them out. It will still be possible to manually create this bug using the builder pattern, but I'm less worried about that.

**Comment by benwis** [comment]
Yeah, you definitely have to think about it to figure out why. I was kinda guessing it did this based on what I could tell of the expanded code. I wonder why they said it worked in 0.2? You must have changed something.

**Comment by gbj** [comment]
Interestingly it actually works (in my testing) in the optimized SSR version, which has to handle `class` in a special way and so ends up doing things in this correct order, so that could explain some of the difference in behavior.
