### ISSUE TITLE
feat: API routes that return only the data specified

### ISSUE THREAD

**Issue by benwis** [leptos-rs/leptos#757]
Routes that return only the content returned from the route. Could be an RSS feed or JSON or maybe even something else.

**Comment by gbj** [comment]
Thinking about this: I think it's a great idea, and I'm wondering what a good API for it would be.

```xml
<ApiRoute
  path="/rss.xml"
  response=|cx| {
    // so far, so good, right?
  }
/>
```

What's the type of `response` though, I wonder? Because we can definitely let it be something like
```rust
pub fn ApiRoute<P, R, Fut>(
  cx: Scope,
  path: P,
  response: R
) -> impl IntoView
where
  P: std::fmt::Display,
  R: Fn(Scope) -> Fut,
  Fut: Future<Output = ???>
{}
```
So that API route response functions can be `async`. And then `???` here could be, presumably, `Response<Body>` for Axum or `HttpResponse` for Actix or whatever for another framework. So basically an API route response would be an async function that takes a `Scope` and returns a `Response`. Taking `Scope` lets it have access to the `Request`. I'm not sure how we type the response in the router though.

Ooh or maybe the `<ApiRoute/>` component is provided by the integrations? Hm. Have to think a little more, but does that outline sound right?

**Comment by gbj** [comment]
So I finally got around to doing some work on this. Initially my idea was to be able to basically use any handler. I've built most of the infrastructure but the problem is that basically the server-only types can't compile to WASM, at least for Actix, so the `<Api/>` component I was envisioning going in the router can't really work. On the other hand, API routes can just be added as ordinary route handlers in your `main.rs`. 

Another possibility would be to restrict things here such that an "API route" basically means a route that returns data instead of a view: it's some `async` function, which doesn't necessarily have access to the server types (but which could call a server function in its body, as it will only run on the server anyway) that renders something to a type that implements `Serialize` and we return some JSON.

Is the latter useful enough that you'd want it for an RSS feed or something? (Or, for example, I'm working on DOCX export)

**Comment by benwis** [comment]
It's a tricky thing, for the blog example the idea of Posts, a Post list, and DB fetching are all occurring in Leptos, not in Axum. That's the kind of stuff you might want to return in an RSS feed. So I could either duplicate all that logic above Leptos.

Now that I consider it, since we have GET requests for server functions now, perhaps the answer is to open up the response types for them a bit. 

For RSS feeds, we'd need XML response types. For binary data that we don't want to encode(image payloads and such), perhaps a Bytes one?

**Comment by gbj** [comment]
> Now that I consider it, since we have GET requests for server functions now, perhaps the answer is to open up the response types for them a bit.
> 
> For RSS feeds, we'd need XML response types. For binary data that we don't want to encode(image payloads and such), perhaps a Bytes one?

I'm going to declare “mission accomplished” on this one as of #2158: it is possible, for example, to create an RSS feed using a server function with
1) a specified `endpoint = `, and
2) a custom encoding
