### ISSUE TITLE
feat: Allow for a more concise syntax when passing views as props

### ISSUE THREAD

**Issue by elliotwaite** [leptos-rs/leptos#766]
Instead of having to write this:
```
<Routes>
  <Route path="/" view=|cx| view! { cx, <Home/> }/>
  <Route path="/other" view=|cx| view! { cx, <Other>"children"</Other> }/>
  <Route path="/*any" view=|cx| view! { cx, "just text" }/>
</Routes>
```
Allow for something like this:
```
<Routes>
  <Route path="/" view=<Home/>/>
  <Route path="/other" view=<Other>"children"</Other>/>
  <Route path="/*any" view=<>"just text"</>/>
</Routes>
```
Would it be possible for the `view!` macro to support this type of syntax?

**Comment by bram209** [comment]
Would be nice if this was possible (didn't test code)

```rust
#[component]
fn ResourceOk<R, RV, IV, Props>(
    cx: Scope,
    resource: ReadSignal<Result<R, String>>,
    resource_view: RV,
) -> impl IntoView
where
    R: 'static,
    RV: FnOnce(Scope, Props) -> IV + 'static,
    Props: From<R>,
    IV: IntoView,
{
    todo!()
}
```

So you would be able to call it by:

```rust

struct User;

#[component]
fn UserProfile(cx: Scope, user: User) -> impl IntoView { }

#[component]
fn SomeComponent(cx: Scope) -> impl IntoView {
    let (name, set_name) = create_signal(cx, Ok(User {}));

    view! { cx,
        <ResourceOk resource=name resource_view=UserProfile  />
    }
```

**Comment by bram209** [comment]
I also wonder if the view! macro could return a closure that takes the scope as an argument. This way you don't always have to explicitly pass the scope as the first argument

**Comment by bram209** [comment]
> Another area this might apply to is when using views in code that's already inside a !view macro. 

This is not really feasible, considering that the `view!` macro parses rust code with the [`syn`](https://github.com/dtolnay/syn) crate, so it will ask syn to parse a full expression. `syn` is not aware that it is being used within a leptos context. So unless you fork `syn` and add a new variant to [`syn::Expr`](https://docs.rs/syn/latest/syn/enum.Expr.html) or write a full rust source code parser, I don't see how this can easily be implemented.

**Comment by elliotwaite** [comment]
@bram209, ah, I see. Thanks for the explanation.

So perhaps the alternative strategy of using custom components, like `<For>` and `<If>` (as mentioned in https://github.com/leptos-rs/leptos/issues/769), would be the better way of implementing this type of control flow while avoiding nested `view!` macros.

**Comment by vldm** [comment]
I am not sure that having syntax like this is a good idea:
```html
<Routes>
  <Route path="/" view=<Home/>/>
  <Route path="/other" view=<Other>"children"</Other>/>
  <Route path="/*any" view=<>"just text"</>/>
</Routes>
```

This one makes it incompatible with [HTML spec](https://www.w3.org/TR/2012/WD-html-markup-20120329/syntax.html#syntax-attributes).

> attribute names [must](https://www.w3.org/TR/2012/WD-html-markup-20120329/terminology.html#must-requirement) consist of one or more characters other than the [space characters](https://www.w3.org/TR/2012/WD-html-markup-20120329/terminology.html#space), U+0000 NULL, """, "'", ">", "/", "=", the control characters, and any characters that are not defined by Unicode 



```rust
view! { cx,
    <ul>
        {values.into_iter()
            .map(|n| <li>{n}</li>) // <-- Using `<li>{n}</li>` directly without the nested `view!` macro.
            .collect::<Vec<_>>()}
    </ul>
}
```

This one is probably impossible as @bram209 have mentioned.
Also both of this syntax makes it harder to read by mixing html and rust context.


But what have you considered making both construction more declarative?

For example:
```rust
<Routes>
  <Route path="/" > <Home/> </Route>
  <Route path="/other" /> <Other>"children"</Other> </Route>
  <Route path="/*any" />"just text"</Route>
</Routes>
```
it can become more verbose, because of closed tag, but also more html-like?

Or more complex example with `binding` conception:

```rust
<ul>
   <For each=values bind(n) > // Bind element of iteration to child context 
     <li>{n}</li>
   </For>
</ul>
```

Bind can be used as a generic way to pass variable from parent component to its childs.

What you guys think about it?

**Comment by gbj** [comment]
We could probably use the new `slot` approach for nested routes:
```rust
<Routes>
  <Route path="/" > 
     <Home/>
     <Route slot:nested path="/*any" />"just text"</Route>
  </Route>
  <Route path="/other" />
    <Route>
      <Other>"children"</Other>
     </Route>
     <Route slot:nested path="/*any" />{"just text"}</Route>
  </Route>
</Routes>
```
Although I think I actually find that less readable than the `view=...` version, because it's really hard to see at a glance what's a nested route and what's the view for this route.

**Comment by gbj** [comment]
Some good news on this one. 

First off, something like this already works if you just leave off `#[component]` on your top-level route view components:
```rust
<Routes>
  <Route path="/" view=Home/>
  <Route path="/other" view=Other/>
</Routes >
```
ie `view` takes a `Fn(Scope) -> impl IntoView` so if you leave off the component macro and just make them functions that take `Scope` you can feed the functions themselves in. 

But granted that's not ideal. 

Components by default are redefined into functions with two arguments, Scope and their props. But I did a little experimenting and I *think* I can get the component macro to define no-prop components as one-argument functions (ie ones that just take Scope) without breaking the `view`, which doesn't actually know how many props a component has. (Because a component with no props could either have no props, or be props with all default values.) This would allow no-prop components to be passed into props that take a function of scope, ie you could collapse every `fallback=|cx| view! { cx, <Loading/> }` to just `fallback=Loading`
