### ISSUE TITLE
Make Axum integration less bad

### ISSUE THREAD

**Issue by gbj** [leptos-rs/leptos#811]
The way I hacked together the `leptos_axum` code to allow for the fact that our reactive system is `!Send` is bad. Like, quite bad.
https://github.com/leptos-rs/leptos/blob/8b57ba7aa8498832cc5aade2764333dce2956dd9/integrations/axum/src/lib.rs#L296-L303
...and so on.

Spawning a new runtime per request and then blocking is not great.

Luckily, this has not stopped a bunch of people joining the community who are quite good. I'm opening this issue for accountability so the good people can help me make the bad code less bad.

Specifically, we've talked about the idea of creating a `thread_local` `LocalSet` and spawning these `!Send` futures into those instead. There may be other good ideas here, too.

**Comment by benwis** [comment]
I was also considering using actix_rt in Axum, but I think I'll try the LocalSet approach first, since it requires less boilerplate.

**Comment by FrankReh** [comment]
If I understand this issue here correctly, there is a tokio-util tool that could help or could get someone started with a more tailored approach.

https://docs.rs/tokio-util/latest/tokio_util/task/struct.LocalPoolHandle.html

It was built a few years ago by a person who wanted to get their multi-threaded tokio to play nice with a DB API that was !Send. What they and the tokio maintainer came up with is this type. It allows creating a pool of threads, but the pool could be a single thread, so not a pool at all, that has a current-thread tokio scheduler started on it, and which can have !Send jobs sent to it over a channel from the multi-threaded tokio. The !Send jobs can be sent to the thread over a channel because they are wrapped in a function factory that itself is Send, only the function that is created on the other side is !Send.

The results have to be Send, but that's no surprise.

**Comment by akarras** [comment]
The [local pool](https://docs.rs/tokio-util/latest/tokio_util/task/struct.LocalPoolHandle.html) looks very similar to what actix-rt should also provide- I think between those two options I would lean towards the Actix runtime.

I think the key here is we pretty much have to spawn a dedicated pool for running leptos tasks to make this run until we have a `Send` runtime. I'd guess that'd be a feature flag that Actix-rx and WASM should be able to opt out.

I do think it's worth trying and come up with a way to limit what parts of the reactive system need to be made `Send` in order to accomplish this. Technically, we only have to ensure that things are `Send` across await points. If there was a way to initialize a the Runtime, render whatever chunk we need, dispose the runtime, then hit our next await point, in theory that would work. There's a bit of a dance we'd have to do there, but could be easier than making the making everything `Send`. Then again, I'm only just now familiarizing myself with the reactive system and Axum integrations, so everything seems possible. 😄 

I plan on trying to integrate the actix-rt runtime to help @benwis have a sick blog post showing performance improvements though. I'm sure a few of us are trying different things at this point, so we'll see what sticks.

**Comment by benwis** [comment]
> If I understand this issue here correctly, there is a tokio-util tool that could help or could get someone started with a more tailored approach.
> 
> https://docs.rs/tokio-util/latest/tokio_util/task/struct.LocalPoolHandle.html
> 
> It was built a few years ago by a person who wanted to get their multi-threaded tokio to play nice with a DB API that was !Send. What they and the tokio maintainer came up with is this type. It allows creating a pool of threads, but the pool could be a single thread, so not a pool at all, that has a current-thread tokio scheduler started on it, and which can have !Send jobs sent to it over a channel from the multi-threaded tokio. The !Send jobs can be sent to the thread over a channel because they are wrapped in a function factory that itself is Send, only the function that is created on the other side is !Send.
> 
> The results have to be Send, but that's no surprise.

Nice find! The benefit I see with this is we don't have to change the tokio::main macro. Looking at LocalSet's today, it seems like it doesn't implement Send. This might be a much better approach.

**Comment by akarras** [comment]
Wow, the LocalPoolHandle really was perfect for this. As soon as I gave up the dream of actix-rt it basically just dropped right in. Nice callout @FrankReh 
PR #815 uses the LocalPoolHandle.

**Comment by benwis** [comment]
So the perf benchmarks suggest this is significantly more performant than the old one. Almost 2x as fast, only 40ms off Remix. Nice work @akarras and nice find @FrankReh!

Can't wait to see what happens if I give it a couple threads and some real hardware

**Comment by FrankReh** [comment]
Well I hope it works out. It's only because the Rust authors came up with the clean monikers `Send` and `!Send` otherwise the problem description here would not have triggered the connection for me. And the real work, nice work, was done by @Darksonn for ensuring a tool like this, to get !Send work done on another thread and to be able to package it as a Future with a JoinHandle return value, would have a place in the Tokio ecosystem in the first place - its PR was an interesting read.
