### ISSUE TITLE
ErrorBoundary not rendering in the "fetch" example

### ISSUE THREAD

**Issue by daver32** [leptos-rs/leptos#868]
It seems that the error handling doesn't work properly when combined with resources. 
<br>
To reproduce: Make `fetch_cats` return `anyhow::Result::Err(anyhow::anyhow!("foobar"));`.

Expected: The string `"foobar"` should render.

Actual: No error handling HTML renders.

**Comment by jetaggart** [comment]
I have the same issue, here is a repro with `trunk`

```rust
use std::error::Error;

use leptos::*;
use thiserror::Error;

fn main() {
    console_log::init_with_level(log::Level::Debug).expect("error initializing logger");
    console_error_panic_hook::set_once();
    log::info!("I see this logger");

    mount_to_body(|cx| view! { cx,
         <StringsView/>
    })
}

#[derive(Error, Clone, Debug)]
pub enum FetchError {
    #[error("Missing attribute: {0}")]
    Generic(String),
}

async fn fetch_strings(_: ()) -> Result<Vec<String>, Box<dyn Error>> {
    Err(FetchError::Generic("hello".to_string()).into())
}

#[component]
pub fn StringsView(
    cx: Scope,
) -> impl IntoView {
    let strings = create_local_resource(cx, || (), fetch_strings);

    let strings_view = move || {
        strings.with(cx, |data| {
            data.iter()
                .flatten()
                .map(|order| view! { cx, <span>{order}</span> })
                .collect::<Vec<_>>()
        })
    };

    let fallback = move |cx, errors: RwSignal<Errors>| {
        log::info!("I don't see this logger");

        view! { cx,
            <div class="error">
                <h2>"Error"</h2>
            </div>
        }
    };

    view! { cx,
        <div>
            <ErrorBoundary fallback>
                <Transition fallback=move || view! { cx, <div>"Loading (Suspense Fallback)..."</div>}>
                    {strings_view}
                </Transition>
            </ErrorBoundary>
        </div>
    }
}
```

**Comment by gbj** [comment]
Thanks. I actually wrote this example incorrectly, as a result of the fact that initially it just swallowed any errors, and added the `<ErrorBoundary/>` later.

This was what was broken in the example:
```rust
    // the renderer can handle Option<_> and Result<_> states
    // by displaying nothing for None if the resource is still loading
    // and by using the ErrorBoundary fallback to catch Err(_)
    // so we'll just implement our happy path and let the framework handle the rest
    let cats_view = move || {
        cats.with(cx, |data| {
            data.iter()
                .flatten()
                .map(|cat| view! { cx, <img src={cat}/> })
                .collect::<Vec<_>>()
        })
    };
```
If you take a look at the type inference there, you see that `cats_view` is actually is `Fn() -> Option<Vec<HtmlElement<_>>>` — there's no `Result<_, _>` involved at all. This is because `data.iter()` is an iterator over the Result, not over the inner `Vec` (hence the `.flatten()`, which flat-maps the `Vec` iterator into the `Result` one). `Result` only iterates over its `Ok` variant, or nothing if it's `Err`. This means that we inadvertently squashed the error case into the `None` (resource not loaded yet) case. As a result, the comment is actually inaccurate!

I've updated the example in the attached PR, as well as improving some of the error handling, so that it's more obvious what should be going on here.
