### ISSUE TITLE
Suppress debug_warn in request_animation_frame/request_idle_callback

### ISSUE THREAD

**Issue by takeisit** [leptos-rs/leptos#871]
Hi, I'm using `request_animation_frame` to focus a element or to [get client_width/height of a element](https://github.com/leptos-rs/leptos/discussions/342). 
After [a recent update](https://github.com/leptos-rs/leptos/commit/210c11a73388b29fac43ad1feeadaa0aac43acc5), leptos outputs the following warning to console.

```
"At {called_at}, you access a signal or memo (defined \
at {defined_at}) outside a reactive tracking \
context. This might mean your app is not responding \
to changes in signal values in the way you \
expect.\n\nHere’s how to fix it:\n\n1. If this is \
inside a `view!` macro, make sure you are passing a \
...
value without tracking, use `.get_untracked()` or \
`.with_untracked()` instead."
```

When using `set_timeout` or `set_interval` instead of `request_animation_frame`,
leptos outputs no warnings.

Are there any reasons?
Or is it just missed implementations of adding SpecialNonReactiveZone::enter/exit into them?

My code is:

```rust
mount_to_body(|cx| {
    let node_ref = create_autofocus_input_ref(cx);
    view! { cx,
        <input _ref=node_ref />
    }
})
```

```rust
fn create_autofocus_input_ref(cx: Scope) -> NodeRef<Input> {
    let elem_ref = create_node_ref::<Input>(cx);
    let from = js_sys::Date::now();

    create_effect(cx, move|_| {
        fn try_focus(elem_ref: NodeRef<Input>, timeout: f64, from: f64) {
            if let Some(elem) = elem_ref.get() {
                _ = elem.focus();
                log!("done");
            } else if (js_sys::Date::now() - from) < timeout {
                request_animation_frame(move||try_focus(elem_ref, timeout, from));
                log!("retry");
            } else {
                log!("timeout");
            }
        }

        request_animation_frame(move||try_focus(elem_ref, 2000.0, from));
    });

    // elem_ref.on_load(cx, |elem| { _ = elem.focus()}); // this does not work
    
    elem_ref
}
```

**Comment by gbj** [comment]
Honestly I think this would be a good case for _removing_ the `SpecialNonReactiveZone::enter/exit` from `set_timeout` and `set_interval` rather than adding it to `request_animation_frame`...

This is just warning you that
```rust
if let Some(elem) = elem_ref.get() {
```
is *not* a reactive get, and is the equivalent of
```rust
if let Some(elem) = elem_ref.get_untracked() {
```
The point of this is to reduce bugs for people new to the library, and to enforce the convention of using `_untracked()` when something is, in fact, untracked. I created exceptions in a couple places but looking over your example I almost wonder if I should remove some of them. For example, this example, at first glance, looks like it *might* be reactive—it's calling a signal `.get()` in a place that's visually inside a `create_effect`—but the `request_animation_frame` means that the effect isn't actually running when the `NodeRef` is read. Suppressing the warning on `set_timeout` here is a missed opportunity.

Does the code as you've written it actually work? I guess it probably does because the effect just creates an animation frame, by which point the node ref has been filled.

**Comment by takeisit** [comment]
Yes, it seems to work well (but with the warning) on my Chrome 112, although I'm not sure that it works in other environments.
![focus](https://user-images.githubusercontent.com/31598815/232225908-adcdee91-a97f-4cb8-b5bc-1b3237281a21.png)

After your comment, I tried no `create_effect` version like below. It works too.

```rust
fn create_autofocus_input_ref(cx: Scope) -> NodeRef<Input> {
    let elem_ref = create_node_ref::<Input>(cx);
    let from = js_sys::Date::now();

    fn try_focus(elem_ref: NodeRef<Input>, timeout: f64, from: f64) {
        if let Some(elem) = elem_ref.get() {
            _ = elem.focus();
            log!("done without create_effect");
        } else if (js_sys::Date::now() - from) < timeout {
            request_animation_frame(move||try_focus(elem_ref, timeout, from));
            log!("retry");
        } else {
            log!("timeout");
        }
    }

    request_animation_frame(move||try_focus(elem_ref, 2000.0, from));
    
    elem_ref
}
```

If there's a better way, I want to use it.

In this case, I don't need the reactivity of `NodeRef`.
So if `NodeRef` implements `get_untracked`, I'll use it.

**Comment by gbj** [comment]
Oh, of course, the issue here is that `NodeRef` doesn't have `get_untracked`. 

I'm not sure what the extra date logic is for but this simplified version works fine:
```rust
#[component]
fn App(cx: Scope) -> impl IntoView {
    let node_ref = create_node_ref::<html::Input>(cx);
    create_effect(cx, move |_| {
        if let Some(input) = node_ref.get() {
            request_animation_frame(move || {
                input.focus();
            });
        }
    });
    view! { cx, <input type="text" node_ref=node_ref/> }
}
```

**Comment by takeisit** [comment]
Oh! it's very nice! I was unaware of these ways. I use it. Thanks!
