### ISSUE TITLE
Is there any reasons to handle text in html element content as a expression?

### ISSUE THREAD

**Issue by vldm** [leptos-rs/leptos#883]
Hi, i am working on single file extension demo (like in vue), and during implementation found that code in hot-reload functionality:
```rust
            Node::Text(text) => {
                if let Some(value) = value_to_string(&text.value) {
                    views.push(LNode::Text(value));
                } else {
                    let value = text.value.as_ref();
                    let code = quote! { #value };
                    let code = code.to_string();
                    views.push(LNode::DynChild(code));
                }
            }
```
https://github.com/leptos-rs/leptos/blob/main/leptos_hot_reload/src/node.rs#L61

I see that syn-rsx use `NodeValueExpr` type for content text.
Is there any example  what text in html content can be treated as DynChid?

Maybe related to #833

**Comment by gbj** [comment]
That's an interesting question. So, at the present I just handle it that way for the sake of consistency with the types `syn-rsx` actually give. But out of curiosity I looked at [the actual `syn-rsx` parsing code for a `NodeText`](https://github.com/stoically/syn-rsx/blob/0013b1a571c5d3ba7045efce3a36ada5ec57af78/src/parser.rs#L100-L105):
```rust
    /// Parse the stream as [`Node::Text`].
    fn text(&self, input: ParseStream) -> Result<Node> {
        let value = input.parse::<ExprLit>()?.into();

        Ok(Node::Text(NodeText { value }))
    }
```
This looks like it accepts *any literal*, which in fact it does. I tested it with
```rust
    view! { cx,
        <div>2</div>
    }
```
i.e., the integer `2` instead of the string slice `"2"` and it compiles just fine... Leptos *doesn't* treat it as a static string (maybe it should?) but actually treats it as a `DynChild`... `rust-analyzer` tells me this expands to 
```rust
leptos::leptos_dom::html::div(cx)
    .child((
        cx,
        #[allow(unused_braces)]
        2,
    ))
    .with_view_marker("-0")
```

Maybe it should actually expand to a static string, since `value_to_string` thinks it handles literal integers:
https://github.com/leptos-rs/leptos/blob/6753ba21c4ae39e20112d4d1cdfd3133f0fd64c8/leptos_hot_reload/src/parsing.rs#L3-L14

So :shrug: Hopefully that's some helpful context and I'm open to tweaks in how either the `view` macro or the hot-reloading stuff handle this case.

**Comment by vldm** [comment]
Thanks! This is a very comprehensive answer.
At the beginning i though that you want to support some small expressions without braces, something like this
```
<div> 1 + x </div>
```

At my opinion this is a bad idea, and text in view! without quotes should be treated as static string (at least in element content place), even if it unquoted.

Should i close the issue, or keep it as context to this question:
>Leptos doesn't treat it as a static string **(maybe it should?)** but actually treats it as a DynChild...

**Comment by gbj** [comment]
> Thanks! This is a very comprehensive answer. At the beginning i though that you want to support some small expressions without braces, something like this
> 
> ```
> <div> 1 + x </div>
> ```
> 
> At my opinion this is a bad idea, and text in view! without quotes should be treated as static string (at least in element content place), even if it unquoted.

100% agree with you that that would be a bad idea.

> Should i close the issue, or keep it as context to this question:
> 
> > Leptos doesn't treat it as a static string **(maybe it should?)** but actually treats it as a DynChild...

I'll leave it open for this reason, just for me to confirm whether we're actually doing the right thing here. Thanks for raising this!

**Comment by vldm** [comment]
I also found another example, that i have missed at first time:
<span>"Value: " {value} "!"</span>

Is expanding to

```
    .child((
        cx,
        leptos::leptos_dom::html::span(cx)
            .child((cx, #[allow(unused_braces)] "Value: "))
            .child((cx, #[allow(unused_braces)] { value }))
            .child((cx, #[allow(unused_braces)] "!")),
    ))
```

This looks like fundamental feature, so i think all of this `if NOT value_to_string(&text.value)` things is to support this.

**Comment by gbj** [comment]
> I also found another example, that i have missed at first time: `<span>"Value: " {value} "!"</span>`
> 
> Is expanding to
> 
> ```rust
>     .child((
>         cx,
>         leptos::leptos_dom::html::span(cx)
>             .child((cx, #[allow(unused_braces)] "Value: "))
>             .child((cx, #[allow(unused_braces)] { value }))
>             .child((cx, #[allow(unused_braces)] "!")),
>     ))
> ```
> 
> This looks like fundamental feature, so i think all of this `if NOT value_to_string(&text.value)` things is to support this.

I *think* that in this case that's a [`Node::Block`](https://docs.rs/syn-rsx/latest/syn_rsx/enum.Node.html#variant.Block) and not a `Node::Text` but I may be wrong, and the open question still stands.

**Comment by vldm** [comment]
Yes, you are right, so my previous comment is not relevant.

**Comment by gbj** [comment]
This was a case of "gbj forgot how the renderer works."
```rust
.child((cx, 2))
```
and similar are exactly right: the implementation of `IntoView` for `(Scope, T: IntoView)` just calls `T.into_view(cx)`, which is implemented as a plain string conversion for primitives. So this doesn't do any of the expensive work of creating a reactive effect for static values. Technically it costs a `String` allocation at runtime that could be done by converting them to a `&'static str` at compile time, so I've added that in #887. 

Otherwise this all should be good so I'll close this for now. Thanks for raising it.
