### ISSUE TITLE
Add a website for leptos. Beginner-friendly Tutorial and Playground.

### ISSUE THREAD

**Issue by bomaneco** [leptos-rs/leptos#944]
Add a website for leptos. It should include a beginner-friendly tutorial to help new users get started with leptos. Additionally, it would be great to have a Playground where users can experiment with leptos in a safe and controlled environment. 

The leptos.rs domain name has been registered by someone else. It is accessible, but doesn't look like leptos's website.

**Comment by gbj** [comment]
There's a team working on a website. Anyone interested in helping out should join the Discord #website channel! We've done some prototyping but are taking some time to think about messaging etc. so it is a good launch, rather than rushing something.

You can find the beginner-friendly tutorial linked from the README of this repo. Here's a link: https://leptos-rs.github.io/leptos/

This includes links to a number of CodeSandbox playgrounds. If you want to play around with your own, you can use the Leptos template at https://codesandbox.io

We own leptos.dev (There's nothing there yet) I don't know who PengTao is but congrats to them on leptos.rs, which is, unforunately, a zero-posts Rust blog built with Astro 😅 

I'll leave the issue open until we launch in case anyone else is curious.

**Comment by ngmisl** [comment]
A starter blogging template would be very cool too

**Comment by gbj** [comment]
The Leptos website with links to the guide, API docs, and CodeSandbox playground is live for a soft-launch at https://leptos.dev, so I'm going to close this one as completed. We'll make it a little more visible once the website has gotten its sea legs.
