### ISSUE TITLE
JSON POST encoding for server functions [feaure request]

### ISSUE THREAD

**Issue by 3nt3** [leptos-rs/leptos#952]
In my opinion, there should be a way to encode data sent to/from server functions as JSON as it's a more familiar encoding for most web devs lol.

**Comment by gbj** [comment]
So the primary reason not to do this is that encoding/decoding takes place at runtime, and adding another encoding adds to the binary size even if you never use it. Since we've upgraded to `serde_qs`, the form-encoded option can handle most data structures. Leptos controls both the client and the server end of your server functions. Is there a reason you want to use JSON other than familiarity? Like I said, adding another encoding is not a zero-cost thing.
