### ISSUE TITLE
ActionForm does not respect Cbor encoding

### ISSUE THREAD

**Issue by gabydd** [leptos-rs/leptos#977]
when submitting an ActionForm it always submits with url encoding to the server, for example try to submit the second input in this reproduction and you will see the error on the server when it tries to deserialize url as cbor: https://github.com/gabydd/empty_input

**Comment by gabydd** [comment]
ah I think I figured out what is happening ``ActionForm`` creates a ``Form`` which always makes a post request: https://github.com/leptos-rs/leptos/blob/7fe9f82d899590b27cb1cbd0071a7cadd740098b/router/src/components/form.rs#L104 which of course is url encoded cause it is a regular form submit

**Comment by gbj** [comment]
Hm I have genuinely mixed feelings on this. I created the `ActionForm` when the only supported encoding was form-encoded `POST` requests, which works perfectly with the `<form>` approach because it works without WASM or before WASM has loaded. The browser does itself has no idea how to use CBOR, so using a CBOR-encoded server function with any kind of form has the built in potential for issues, if the browser doesn't support WASM or if WASM has not finished loading yet. 

We now have four separate combinations of encoding (and maybe more in the future), so it's probably best just to use the server action dispatch itself, and then fill in any of the missing logic. But I'm a little concerned about the potential for broken behavior. Still I guess this is already the case with `MultiActionForm` so may as well be consistent.

**Comment by gbj** [comment]
@gabydd What's the reason you're using CBOR + a form by the way? If it's the need for nested structs etc. in form data, I did also just merge #987 to support this with the URL/POST default encoding for server functions. I'm wondering if it might make the most sense to actually *only* support the URL-encoded GET and POST methods for `<ActionForm/>`, and to explicitly document that, which would mean that there's no mismatch between pre-WASM and post-WASM behavior, but also that `<ActionForm/>` works without additional encoding handling. There are a couple things like redirect handling etc. that are not trivial to do if we use the actual server function/action dispatch instead of the form handling, and it adds some binary size to handle the CBOR possibility in `<ActionForm/>` itself.

**Comment by gabydd** [comment]
I am not sure why I was testing with Cbor actually, I am not using it at the moment. I was going to suggest just documenting as well, that makes the most sense for me.
